### PR TITLE
Better validation for username and logic behind the calls to API in SetUsername component

### PR DESCRIPTION
**Pull request by LetItRock**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

**Release notes for users (delete if codebase-only change)**
- debounce search request to API to validate if username is not taken (instead of throttle); this will reduce the number of API calls;
- fix for the issue -> when throttled search function calls API but the username in state after that time was invalid;
- refactor for username validation logic;

### CODE REVIEW

**Review by mxstbr — DISMISSED** [review]
Ohh great catch, this looks amazing!

**Comment by brianlovin** [comment]
This is awesome! Looks like there's one small flow error there in the debounce; maybe our typing on the debounce should just make that third `immediate` argument an optional arg :)

**Review by brianlovin — CHANGES_REQUESTED** [review]
Quick flow change then this looks awesome!

**Comment by LetItRock** [comment]
Ok, I'll add it ;)

**Review by brianlovin — DISMISSED** [review]

**Comment by brianlovin** [comment]
Hey @mxstbr any idea why our circle builds are failing here at the checkout environment step? The errors here aren't like anything I've seen before - wondering if it's because of this PR incoming from @LetItRock's fork?

**Comment by brianlovin** [comment]
That didn't seem to work :P

**Comment by brianlovin** [comment]
Sorry for the holdup here - no idea what's going on with CI

**Comment by LetItRock** [comment]
@brianlovin ouu no problem with that ;)

**Comment by brianlovin** [comment]
@LetItRock I'm a big dummy, and totally had an oversight here - we use very similar code in `src/components/editForm/user.js` - would it be a huge pain to either apply these changes there, or just abstract a "username validator" component of sorts that we can use in both places? Sorry for being forgetful here and delaying the PR!

**Comment by LetItRock** [comment]
@brianlovin no problem with that, I can do it.

**Comment by LetItRock** [comment]
I've created separate component called UsernameSearch and it holds validation logic now. I've also added property size into it because on onboarding page it has different styles than on settings page.
Tested this out and it works fine. I didn't run it with Cypress because I have something wrong with config, hope nothing will fail.

**Comment by brianlovin** [comment]
The `test_static_js` failure there is a flow issue - just missing a type def for `onError` in the new component :)

**Comment by mxstbr** [comment]
Oopsie I merged in the wrong thing. Oneeee second

**Review by mxstbr — APPROVED** [review]
I cleaned up the flow types :blush: This looks awesome, thank you so much!

**Comment by LetItRock** [comment]
Cool! 😊

**Pull request merged**
