### PR TITLE
Dont cache image assets in serviceworker

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

It turns out Zeit now's new rate limiting protections were causing our ServiceWorker to err out when it tried caching all our assets:

screen shot 2018-04-06 at 11 48 02

That causes the entire ServiceWorker update (and thusly app update) to fail. :confused: This is a quick workaround which fixes the issue by not caching any of our external image assets, of which there were numerous. /cc @matheuss @rauchg et al.

I'm going to hotfix ship this to alpha to see if it fixes the ServiceWorker issues we've been seeing.

### CODE REVIEW

**Comment by mxstbr** [comment]
This is deployed on alpha.spectrum.chat, testing!

**Comment by mxstbr** [comment]
This fixes it!

screen shot 2018-04-06 at 13 37 08

We should ship this asap.

**Review by brianlovin — APPROVED** [review]

**Comment by brianlovin** [comment]
Thanks for hotfix - is this on prod?

**Comment by mxstbr** [comment]
this is only on alpha so far, wanna cut a prod release?

**Comment by brianlovin** [comment]
Oh my god this didn't make it on prod. The biggest of face smacks.

**Pull request merged**
