### PR TITLE
Filter deleted channels everywhere #2950

### LINKED ISSUE #2950: Filter deleted channels everywhere
**Note**: Running locally, with a fresh install/migration/seed and no modifications to code.

When I click a specific community on the index page sidebar I get the following error in the API console.

```Error: Cannot return null for non-nullable field Thread.channel.```

Error

The client looks like the following:

Error

When I click on a channel however.. it loads all the threads fine. Also..when I click everything..it loads threads fine as-well!

**Note**: On https://spectrum.chat it loads all the threads fine when you click on the community in the sidebar. 

Any ideas as to what the issue is? Thanks for any help!

### PR DESCRIPTION
**Pull request by a-golovanov**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api

Closes #2950

### CODE REVIEW

**Comment by brianlovin** [comment]
Re that test failure - for some annoying reason, when prettier reformats function declarations that exceed 80 chars it breaks the ability for async/await to register properly. The fix here is to rewrite the func to be one line and add `prettier-ignore` above it.

**Review by mxstbr — APPROVED** [review]
Amazing work, thank you so much! 🙌

**Comment by brianlovin** [comment]
This is amazing, thank you @a-golovanov 💜

**Comment by a-golovanov** [comment]
You make me blush 😊

**Pull request merged**
