### PR TITLE
Fix upload images during thread editing

### LINKED ISSUE #4741: Can't upload images when editing a thread
Thread https://spectrum.chat/spectrum/general/ability-to-upload-images-when-editing~df87a91c-bf61-4562-ae6e-f233a574686b

Note: drag and drop doesn't work, either

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

**Related issues (delete if you don't know of any)**
Closes #4741

Not sure how I missed this, sorry about that!

### CODE REVIEW

**Comment by brianlovin** [comment]
I pushed a commit with the upload photo and markdown icons in the bottom left of the action bar, but to be honest I'm not really sure how to wire that button up properly with the thread input. I thought I could just pass the props through. Any chance we can get that button working? Then this will be good to go

**Comment by mxstbr** [comment]
Done, but the button tooltip is cut off by the thread inputs. Any ideas how to fix that?
screenshot 2019-03-07 at 14 40 50

**Comment by brianlovin** [comment]
Remove overflow hidden on the action bar; this will be irrelevant after #4798 though since it adds a better tooltip component.

**Comment by mxstbr** [comment]
There is no `overflow: hidden` on the action bar.

**Comment by brianlovin** [comment]
Oh! We'll there's an overflow being hidden somewhere down in them weeds :P

**Comment by mxstbr** [comment]
I think the inputs overlay the tooltip z-index wise?

**Comment by brianlovin** [comment]
Begone tooltips! You shall return another day, this time with portals.

**Review by brianlovin — APPROVED** [review]
Let's get this fix out, good work!

**Pull request merged**
