### PR TITLE
Use parallelism

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

### CODE REVIEW

**Comment by brianlovin** [comment]
@mxstbr fairly sure this isn't working, but I've upgraded us to the highest plan on CircleCI that now allows for 6x parallelization. If we can get `test_web` to run on 6 containers it would be amazing. I don't think I've set up the `config.yml` properly or something though after going through the docs a time or two...could you take a look?

Will close #4755

**Review by mxstbr — COMMENTED** [review]
We are running e2e tests twice when the recorded ones fail due to the way we are checking the existence of the env variable. I will clean that up and also tackle the parallelization.

**Comment by mxstbr** [comment]
@brianlovin look at the e2e test logs:

```
Opening Cypress...
Parallelization is not included under your current billing plan.

To run your tests in parallel, please visit your billing and upgrade to another plan with parallelization.
```

We have to upgrade _Cypress_ to be able to use parallelization. I do not know if I have access to our org on Cypress, but I will try to do that.

**Comment by mxstbr** [comment]
Yeah I do not have access to the Cypress org. You will have to upgrade that, I will fix the conditional env var checking in the mean time!

**Comment by mxstbr** [comment]
This is fixed, now we will not run e2e tests two times if they fail! :100: That should already speed things up a lot (we are at ~12 minutes for a single, full run?), and then once you enable the parallelization in the Cypress settings we should be back down to a couple minutes hopefully

**Comment by brianlovin** [comment]
Since your config changes will save *some* time, I'll merge. Tomorrow could you poke at fixing the rest @mxstbr ?

**Pull request merged**
