### PR TITLE
ajust desktop draggable region area

### PR DESCRIPTION
**Pull request by ryota-murakami**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- desktop

**Release notes for users (delete if codebase-only change)**
- ajust desctop draggable region area

## overview

When, "home", "Messages", "Explore" Clicked, Electron reacting as a draggableRegion.
this is might be give a slightly frustration if user doesn't expected drag window.
so, this commit ajusted draggable region area to 10px of navbar top;

## Image
highlight element is the draggable area.

### Not Login
screen shot 2018-06-01 at 6 43 33

### Login
screen shot 2018-06-01 at 6 51 08

thnak you for your every feedbacks😄✨

### CODE REVIEW

**Comment by brianlovin** [comment]
What if we keep the entire nav bar as a draggable area, but just disable draggable on each of the tabs? I think having an invisible 10px hit area at the top of the navbar will still be confusing for people who try to drag slightly lower

**Comment by ryota-murakami** [comment]
> What if we keep the entire nav bar as a draggable area, but just disable draggable on each of the tabs? 

@brianlovin wonderful! more than my solution💯

I made this PR based on the behavior of slack's native app, but I think your suggestion is very good, I'll submit additional commit at a later date!

**Comment by brianlovin** [comment]
Sounds good!

**Comment by ryota-murakami** [comment]
or close this PR & create new PR after my work rather than push additional commits?

**Comment by brianlovin** [comment]
Up to you :)

**Comment by ryota-murakami** [comment]
Although I plan to destroy this commit, I think that it is more useful for the history of conversation to remain in PR, so I will continue to work with this PR :)

**Comment by ryota-murakami** [comment]
change icon to no-draggable, following feedback. https://github.com/withspectrum/spectrum/pull/3236#issuecomment-393701680 Ready for Review😀

**Comment by ryota-murakami** [comment]
@brianlovin ping: this is prepared, up to you whether adopt proposal😀👍

**Comment by ryota-murakami** [comment]
ping👉

**Comment by brianlovin** [comment]
Hey, sorry - will get to this soon. Been heads down on a few other things :)

**Comment by ryota-murakami** [comment]
@brianlovin Never mind, let's proceed in order from prior work😄

**Comment by brianlovin** [comment]
This is working great, thank you @ryota-murakami :D

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
