### PR TITLE
Select first thread on dashboard on SSR

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

### CODE REVIEW

**Review by brianlovin — APPROVED** [review]
LGTM, this should help inbox experience a ton!

**Comment by brianlovin** [comment]
Oh, just fyi @mxstbr this will need to be redone in react 17 because `componentWillMount` is going away

**Comment by mxstbr** [comment]
Yeah I know, we'll need to redo a lot of stuff

**Comment by brianlovin** [comment]
True 👍👍

**Pull request merged**
