### PR TITLE
Add support for Slack-style :emojis: to chat input

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

Note that this does not implement a suggestion popover for the emojis while you're typing, it only converts `:smile:` to :smile:

### CODE REVIEW

**Comment by brianlovin** [comment]
This is nice, will be more useful of course when it has a popover for suggestions. I wish we could user https://blog.tommoor.com/emojione-picker/ but not have to use emojione and just let it use native platform emojis.

**Comment by brianlovin** [comment]
Also the test failure for not being able to compile the source files isn't inspiring a lot of confidence :P

**Comment by mxstbr** [comment]
Unfortunately the popover for suggestions will require a move away from `react-mentions`, it does not support having both mentions and emoji suggestions 🙄 

Will move to something more low-level like `react-input-trigger` most likely, will dig into that soon.

**Comment by brianlovin** [comment]
> Unfortunately the popover for suggestions will require a move away from react-mentions, it does not support having both mentions and emoji suggestions 🙄

Couldn't we just add a different trigger `:` and create a map of emoji names to emoji ouputs?

https://github.com/signavio/react-mentions/blob/master/demo/src/examples/MultipleTrigger.js

**Comment by mxstbr** [comment]
I thought the same thing, but we cannot because the `markup` and `displayTransform` options are set on the `MentionsInput` for all `Mentions`. Our values for user mentions do not fit with emojis at all.

I submitted a feature request for this (https://github.com/signavio/react-mentions/issues/300), but I am not sure if they will get around to implementing it.

**Comment by brianlovin** [comment]
Ah man, okay. Your proposal in that issue looks ideal, would be awesome if it could work out.

**Comment by krvajal** [comment]
How is this going along? Is the approach no longer relevant @mxstbr? If it is still relevant and given the fact that `react-mention` now supports per mention customisations I will like to continue the work from when you left it over.

**Pull request closed without merging**
