### PR TITLE
Better thread meta images

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

**Related issues (delete if you don't know of any)**
Based on and closes #2910

This improves our thread meta images by generating an image from the title and community slug, instead of showing the community profile photo. Examples:

Normal title, long community slug:

Extremely long title, normal community slug:

> Note: This isn't perfect yet, ideally it would show an ellipsis, but unfortunately the imgix text API only allows us to automatically add an ellipsis on one-line text 🙄 Good enough for now though

### CODE REVIEW

**Comment by mxstbr** [comment]
Welp, not ready yet:

screen shot 2018-08-09 at 16 02 00

Simple fix though, on it!

**Comment by mxstbr** [comment]
Fixed:

screen shot 2018-08-09 at 16 12 01

@uberbryn looks like this is a bit cut-off, can you upload the background image in a slightly longer format to imgix? Thanks! :pray:

**Comment by mxstbr** [comment]
Imo it's also kinda weird that the spectrum logo is in the bottom left corner and pretty big. WDYT about getting rid of that @uberbryn?

**Comment by superbryntendo** [comment]
let's try it with `txtlead=4` and `txtalign=left`

txtlead will add some padding between lines of text and it's kinda awkward with it centered.

I think we could also apply a little more padding to the bottom. It's currently centered on the entire image, and we probably want it to be centered within the purple area.

In the Figma doc for Marketing Assets, there's a couple mockups with variants on the logo placement and sizing now. One with just the logomark and the other with a 20% smaller logo. The original thinking was just that it needs to be readable at display sizes, but I agree that it seems a bit large as-is.

image

We *could* just do the logomark and apply their url just to the right of it?

**Comment by superbryntendo** [comment]
image

**Comment by mxstbr** [comment]
Done with the updates! :tada:

Short title, long community slug:



Long title, short community slug:



This good @uberbryn?

**Comment by mxstbr** [comment]
Actually, gotta increase the font size of the slug a bit, one sec

**Comment by mxstbr** [comment]
This is what this version will look like on Twitter:

screen shot 2018-08-10 at 15 17 29

**Comment by mxstbr** [comment]
- [x] Increase line height
- [x] Center URL with logo

**Comment by mxstbr** [comment]
@uberbryn cleaned up based on your suggestions, here's what the latest version looks like:



Good to go?

**Review by superbryntendo — APPROVED** [review]
🚢

**Pull request merged**
