### PR TITLE
Refetch critical data when a network connection is lost and restored

### LINKED ISSUE #3043: Refetch all queries on reconnect
We should use this Apollo Client option I just now discovered (thanks to @ryota-murakami) to refetch all queries if the user disconnects, then reconnects to the network: https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-config-options-notifyOnNetworkStatusChange

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [x] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

Have you ever been on Spectrum, then closed your laptop/phone, and then returned later and wondered if you were looking at stale data? I was never sure (and most of the time the answer is: yes). Sometimes when your hardware starts back up you might see the flash of the 'offline' banner as the site reconnects to the API. But then savvy users know that they still need to refresh the whole app in order to get fresh data.

This is especially frustrating when you leave the inbox open on a computer, but are forced to refresh the page whenever you come back from closing your laptop lid. Similarly, if you are participating in a conversation on your phone, lock your phone, then unlock your phone, it's entirely possible that there will be messages sent since the last fetch, and you won't see them rendered in the thread.

This PR aims to solve this by implementing a check in critical areas of the site that checks for reconnections (both network and websocket) in order to trigger a refetch of the parent query.

Couple notes:
- I can't actually test this locally because we use websockets, and it's hard to spoof a websocket disconnect/reconnect in the dev tools. So we'll want to test each reconnect case in an alpha setting, and will need two devices.
- I made a `src/hooks` directory, although we should rename that since it's not technically a hook. But not sure where else to put the helper function right now

Closes #3043

### CODE REVIEW

**Review by mxstbr — DISMISSED** [review]
Yesssss! Let's also do this when the app regains focus?!? (i.e. when the tab was backgrounded) See https://stackoverflow.com/questions/7389328/detect-if-browser-tab-has-focus, which points towards using https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API which also works as expected on Electron! https://github.com/electron/electron/blob/master/docs/api/browser-window.md#page-visibility

That way one always has fresh data 😍

**Comment by brianlovin** [comment]
> Yesssss! Let's also do this when the app regains focus?!? (i.e. when the tab was backgrounded)

Good idea. Know off the top of your head if there's a browser API that exposes this info? Otherwise can dig in tomorrow.

**Comment by mxstbr** [comment]
Yeah just edit the comment, you want to use the page visibility API: See https://stackoverflow.com/questions/7389328/detect-if-browser-tab-has-focus, which points towards using https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API which also works as expected on Electron! https://github.com/electron/electron/blob/master/docs/api/browser-window.md#page-visibility

**Comment by brianlovin** [comment]
Most excellent! PS we should use that same API to set an `idle` status on the user record to determine whether or not to send notifications

**Comment by mxstbr** [comment]
By the way, the easiest way to test this locally is to just turn off and then back on the API, that should simulate a lost connection perfectly fine.

**Comment by brianlovin** [comment]
https://github.com/withspectrum/spectrum/pull/4290/commits/d0488092ad47dc12929bd8596c30c17237a6b4b5 should handle this, unfortunately the API only detects things like browser tab/window changes, not app changes (e.g. command tabbing to a separate app). So it's not bulletproof, but will still be useful, esp for people who might pin Spectrum

**Comment by mxstbr** [comment]
Looks good code-wise, want to test this on alpha?

**Comment by brianlovin** [comment]
Yep! Going to do a prod cut now then put this on alpha

**Comment by brianlovin** [comment]
Tested all of these on alpha, and they work! I found one minor bug in the messages view that I'm patching now, then gonna ship :)

**Pull request merged**
