### PR TITLE
flow: done api/routes/api/slackImporter.js TODO

### PR DESCRIPTION
**Pull request by ryota-murakami**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

## overview
extends `express$Request` in order to get `req.user` property.
https://github.com/flowtype/flow-typed/issues/114#issuecomment-308006263

thanks🙏

### CODE REVIEW

**Review by mxstbr — DISMISSED** [review]
Ohh that's super nice! Can we use that new `Request` with the `req.user` property across all middlewares and routes?

**Comment by ryota-murakami** [comment]
@mxstbr thanks for your review!

>  Can we use that new Request with the req.user property across all middlewares and routes?

Yes of course, i'll try next my spare time. someday🙌

**Comment by ryota-murakami** [comment]
@mxstbr i'v finished work for replace all express$Request -> Request.
include some flow fix work, thanks😀

**Comment by ryota-murakami** [comment]
ping👉

**Comment by ryota-murakami** [comment]
ping👉 @mxstbr

**Comment by ryota-murakami** [comment]
@mxstbr If you sill willing this PR, could you please review it🙇‍♂️

Thank you so much😀

**Pull request closed without merging**
