### PR TITLE
Close toolbar on image add or editor focus

### PR DESCRIPTION
**Pull request by mknepprath**
**Status**
- [ ] WIP
- [X] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

**Release notes for users (delete if codebase-only change)**
- Editor toolbar now hides after adding an image or giving the editor focus.

Changes to handle #1731  😄

### CODE REVIEW

**Comment by brianlovin** [comment]
@mknepprath love the direction here, agree this should be fixed. Why don't we make it so that any click outside of the editor toolbar closes the toolbar? You can use this component to accomplish that: https://github.com/withspectrum/spectrum/blob/alpha/src/components/outsideClickHandler/index.js with an example implementation here: https://github.com/withspectrum/spectrum/blob/alpha/src/views/communityMembers/components/editDropdown.js#L222

**Review by brianlovin — CHANGES_REQUESTED** [review]
Let's make this capture any external clicks as intent to close the editor toolbar

**Comment by mknepprath** [comment]
@brianlovin Sure!

**Comment by mknepprath** [comment]
@brianlovin Love it! That's a handy component. Might be easier to view the changes with whitespace ignored - https://github.com/withspectrum/spectrum/pull/2731/files?w=1

Let me know if you have any preferences as far as import or method order.

**Review by mxstbr — APPROVED** [review]
This works perfectly, thank you so much for contributing! 💜

**Comment by brianlovin** [comment]
🎉🎉🎉

**Pull request merged**
