### PR TITLE
Fixes all the <main> changes by replacing the wrappers with <main> vs adding an extra element

### PR DESCRIPTION
**Pull request by superbryntendo**
**Status**
- [ ] WIP
- [ ] Ready for review
- [x] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

### CODE REVIEW

**Comment by brianlovin** [comment]
Excellent so far man. So far found two views where the mobile tab bar is pushed off bottom:
- direct messages view
- notifications view

Everything else is good so far; of course, this is only from resizing and we may find some more problems when this is on alpha safari ios :)

**Comment by Tom-Bonnike** [comment]
😱 sorry about that 😄 

Things you might want to test too:
- That there is always only a single `id="main"` attribute on a single page
- That there is always only a single `<main>` tag on a single page

**Comment by brianlovin** [comment]
No worries at all @Tom-Bonnike - a lot of the issues were firefox specific; when I was testing your earlier branch I was testing on chrome where everything was perfect. Thanks for the heads up as well!

**Comment by superbryntendo** [comment]
@Tom-Bonnike No worries dude! Thanks for helping us out here - we super appreciate it as we're not experts on accessibility by any means (though we'd like to be!).

The core problem with the layout as it is rn is just that the higher-level containers are fairly brittle. It's something I'd like to solve, but haven't had time for yet. So, you kinda just got caught in my old mess.

The way I adjusted the elements, I don't think it should be possible to have >1 of those elements in a view... did you encounter a view where that happened?

**Comment by Tom-Bonnike** [comment]
Haha, okay! 😁 
Nah I didn’t, it was just an heads up, just in case.

**Comment by brianlovin** [comment]
😍😍😍

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
