### PR TITLE
Message replies

### LINKED ISSUE #2142: Quoted replies
It'd be neat to be able to quote-reply to a specific message in a thread, similar to what WhatsApp does:

quoted-replies-whatsapp

That would make long threads a lot more manageable!

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)
- athena

**Release notes for users (delete if codebase-only change)**
- You can now quote previous messages in your own message to help the readability of long threads!

**TODO**

- [x] Track parent messages
  - [x] GraphQL `message.parent` field
  - [x] Store `message.parentId`
- [x] Show parent messages quoted inline
- [x] Be able to quote messages from the UI
- [x] Verify that quoted message is in same thread in the API

WIP screenshot based on designs by @uberbryn in https://www.figma.com/file/OmPWwUKus1ruaYCMrRdn2oCG/Quote%2FReply: 

screen shot 2018-04-20 at 12 02 32

This is a replacement PR for #2258 (because I fucked up a merge there and wanted to do some fundamental changes to the data model), closes #2142

Instead of going with `message.quotedMessage` (like I did in #2258) this goes with `message.parent`, which makes a lot more sense if you think about it. It'll also allow us to maybe display things in a tree structure in the future maybe potentially if we ever wanted to.

### CODE REVIEW

**Comment by mxstbr** [comment]
@uberbryn this is basically done, I need two quick inputs from you to finish it off:

- [x] Reply icon
  screen shot 2018-04-20 at 14 02 02
- [x] How do we want to display the currently quoted message in the chat input? It's currently not displayed at all, but the information could all be there.

**Comment by mxstbr** [comment]
Should quoting a message trigger a mention notification?

**Comment by brianlovin** [comment]
@mxstbr yeah it probably should, but should de-duplicate if the OP is mentioned in the reply body itself.

**Comment by brianlovin** [comment]
> How do we want to display the currently quoted message in the chat input? It's currently not displayed at all, but the information could all be there.

We should probably treat it similar to how we treat image uploads now; there should be an ability to cancel out of the reply.

**Comment by superbryntendo** [comment]
image

preview of my changes ^

**Comment by superbryntendo** [comment]
That QuoteWrapper and it's children can probably just be directly popped into the input like the pasted photos are, then. I think that'll make it pretty clear and help the experience feel consistent.

**Comment by brianlovin** [comment]
Imo the left bar on the message being replied to isn’t necessary; it’s an extra visual element that adds noise when it’s already super clear that this is a reply.

**Comment by superbryntendo** [comment]
@brianlovin I think it's normally clear that it's *different* from a normal message, but not immediately clear why. I think the additional clarity of purpose is worth these very minor changes.

**Comment by mxstbr** [comment]
@uberbryn awesome! I made that happen in the last commit:

screen shot 2018-04-23 at 12 54 38

This is ready for a last review and then ship!

**Comment by brianlovin** [comment]
@mxstbr I think we just need a way to clear it - I'm assuming that cmd+a and backspace will remove the quote? Or would it be possible to add "Cancel reply" link in there to remove it?

**Comment by superbryntendo** [comment]
Getting super close, @mxstbr!

- [x] The composer doesn't clear the reply when you send the message
- [x] Offer "x" button to remove staged quotes
- [x] Remove staged quotes on backspace in empty input

We should also make sure this works ok with the photo staging state like we discussed this morning. Perhaps we should offer "x" buttons on the corners of staged quotes and staged photos? In the meantime, if you're at the beginning of the composer and hit backspace, it'd be nice as a means to clear whatever the last item staged is.

Related: what happens when you quote an emoji or image message?

**Comment by superbryntendo** [comment]
Just tested quoting emoji and images. We're good 👌

**Comment by mxstbr** [comment]
Staging photos and quotes together works kinda well I guess:

screen shot 2018-04-24 at 13 49 47

I'll add the same UI we have for the photo to the quote and then we should be ready to ship maybe?

**Comment by mxstbr** [comment]
Latest commit makes it so that we clear both the media preview and the quoted message on backspace in the empty input, demo:



Working on the UI

**Comment by mxstbr** [comment]
Last commit adds the same "X" button we have for media previews to message reply previews:

screen shot 2018-04-24 at 14 08 11

Here's what it looks like for media previews:

screen shot 2018-04-24 at 14 08 20


I think that could definitely be improved, but I'm not sure how 😅@uberbryn any ideas?

**Comment by brianlovin** [comment]
Only bug I found: if I want to reply with an image, but not with any text, the flow doesn't work. Hitting the send button will send the image, but the reply will not be cleared

**Comment by brianlovin** [comment]
cc @uberbryn on those styling fixes - I made it so the send button will always be at the bottom, otherwise we end up with it floating in crazy places as the chat input expands vertically.

**Comment by brianlovin** [comment]
screenshot 2018-04-24 10 51 29
screenshot 2018-04-24 10 51 44

We should probably just let the media input icon stay at the bottom too, huh?

**Review by mxstbr — COMMENTED** [review]
Looks great to me! I'll wait for @uberbryn to review the styling, then let's ship this!

**Comment by mxstbr** [comment]
**TODO:**

- [x] Add e2e test(s) for this
- [x] Fix flow

**Comment by mxstbr** [comment]
Found some more todos:

- [x] Inline code in quotes is invisible

  screen shot 2018-04-26 at 17 50 28

- [x] Quotes don't show up in DMs
- [x] Send mention notifications when somebody quotes a message

**Comment by superbryntendo** [comment]
Good catches!
  

  
  

  
  
>

**Comment by mxstbr** [comment]
Fixed those catches and deployed all changes (except for athena, i.e. you won't get mention notifications yet) to alpha!

Give it a good round of catches, and then feel free to ship it today. :100:

**Comment by mxstbr** [comment]
This is working pretty great so far! I found an interesting edge case which is long messages, quoting those is really awkward:

screen shot 2018-04-27 at 13 48 07

Imagine if I sent that reply, ugh. It wouldn't look good. There's two things here that'd be great to tackle, although they shouldn't block this PR:

1. Truncate quoted messages visually, and expand them on click: (stupid mockup below, that still needs an indicator that the message was truncated and that you can click on it to expand)

  screen shot 2018-04-27 at 13 49 10

2. Be able to quote parts of messages maybe? Kinda like how you can select-and-respond on Medium we could make it so you're able to select-and-quote only part of a message. We'd probably have to make it so that clicking on it would link to the message, but imo that could be a neat feature.

Either of those shouldn't block this PR, although if you can come up with a quick fix it'd be great to get 1. done before. No biggie if not.

**Comment by brianlovin** [comment]
Good catch @mxstbr - I could see two flows here exactly as you describe:

1. User highlights text of a message bubble then clicks reply - only that highlighted text is rendered in the reply
2. User replies to a long message - we truncate the plain text at ~140chars or so
3. The result of both of these is that clicking the replies *must* scroll the user to a message - the only concern I have here is that this will break in threads where we paginate upwards (e.g. load earlier messages) because it's possible that the parent message will not be loaded yet. Any ideas on how to solve that one?

**Comment by brianlovin** [comment]
Hey @mxstbr and @uberbryn going to have to block this, sorry. Two more fixes needed:

1. It looks like we are missing some fields in a graphql query or something, possibly related to adding the new parent message type that doesn't have its subfields defined? 
screenshot 2018-04-27 08 28 43

2. We are not supposed to be nesting `<p>` tags
screenshot 2018-04-27 08 28 52

You can see it happening here:
screenshot 2018-04-27 08 29 02

I spent ~30mins trying to debug that, but this code is...a bit confusing on the frontend tbh.

**Comment by mxstbr** [comment]
> It looks like we are missing some fields in a graphql query or something, possibly related to adding the new parent message type that doesn't have its subfields defined?

Yeah I saw that but it still works soooo... 😅 

> We are not supposed to be nesting <p> tags

Good catch, fix incoming.

----

> the only concern I have here is that this will break in threads where we paginate upwards (e.g. load earlier messages) because it's possible that the parent message will not be loaded yet.

Automatically paginate upwards until you reach the page with that message maybe?

**Comment by brianlovin** [comment]
> Automatically paginate upwards until you reach the page with that message maybe?

Godspeed. Lol but for real this sounds *really* hard to pull off.

**Comment by brianlovin** [comment]
One other consideration for discussion: how does this handle deleted parent messages?

**Comment by mxstbr** [comment]
> how does this handle deleted parent messages?

Properly: doesn't show them. Since this isn't architected in a way where we duplicate data (COUGH NOTIFICATIONS COUGH) deleted messages are just treated as if the message didn't have a parent.

**Comment by brianlovin** [comment]
> (COUGH NOTIFICATIONS COUGH)

Yeah... :(

But makes sense, thanks for testing that!

**Comment by brianlovin** [comment]
Also:

> Yeah I saw that but it still works soooo... 

We should definitely fix this though, as those types of errors are the kinds of things that will break optimistic updates, and just break the apollo cache in general.

**Comment by brianlovin** [comment]
Also @uberbryn this seems to be a new bug introduced with the wrong right padding:

screenshot 2018-04-27 09 01 58

**Comment by mxstbr** [comment]
> We should definitely fix this though, as those types of errors are the kinds of things that will break optimistic updates, and just break the apollo cache in general.

Yeah but we don't have that data in that optimistic update and I'm not sure how we're supposed to get it :confused:

**Comment by brianlovin** [comment]
I'll take another look now

**Comment by brianlovin** [comment]
Yeah this is tricky; one workaround would be to get access to the store in the optimistic response object construction, but that's not possible without some hoc/closure hacking (ref https://github.com/apollographql/apollo-client/issues/1802)

I'll leave this for now I guess :/ I don't like the warnings in the console here though.

In the meantime, I found one other edge case if you try to reply to a message that was deleted (but is visible in your UI because you havne't refreshed). Working on it.

**Comment by brianlovin** [comment]
Afaik this is good to go - I made a followup issue for improvements based on the above discussions #2969 

I'll get all the updates to alpha for a few more rounds of testing, can ship next week to prod!

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
