### PR TITLE
Problem cloning using ssh so add http link

### LINKED ISSUE #2760: Cannot clone your git repository
Trying to run following cmd git clone git@github.com:withspectrum/spectrum.git but all i get is following error

Cloning into 'spectrum'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

It looks like you have blocked something from people to clone your git repisitory :/ could you please fix it?

/Thanks

### PR DESCRIPTION
**Pull request by satyarohith**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

closes #2760

### CODE REVIEW

**Comment by brianlovin** [comment]
Would it be worth adding a link to https://help.github.com/articles/error-permission-denied-publickey/ under the `ssh` command, in case people hit the `Permission denied` error?

**Comment by brianlovin** [comment]
Or add explanation that https cloning is a fallback option if ssh cloning fails? Just trying to think what would be most clear to a newcomer

**Comment by satyarohith** [comment]
@brianlovin agreed! working on it.

**Review by mxstbr — APPROVED** [review]
Looks great to me!

**Pull request merged**
