### PR TITLE
Frecency thread feeds

### LINKED ISSUE #3718: Top Threads
**Plan**

We want to show the "top conversations" in some thread feeds on landing pages (community view, channel view), instead of just ordering them by last active, to make sure (new) users can jump right into active, engaged conversations. Potentially, we could also be able to use this to show a list of top conversations across the entire platform.

The simplest solution to that is [frecency](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Frecency_algorithm) (frequency + recency), an algorithmic idea from Mozilla. (they use frecency to sort the URL bar suggestions) Instead of just ordering by recency, in our case threadLastActive, you also take the frequency of activity into consideration.

We want to end up with a single number that we can order threads by, the "frecency score". There are a couple notes this algorithm will need to hit:

1. The more activity there is the higher a thread is ranked
2. New threads bubble up quickly if they get activity
3. Old threads can re-bubble up if they get a lot of activity

For threads, there are four properties that together can accomplish these:

- Thread age (for 2.)
- Last active age (for 3.)
- Message count (for 1.)
- Reaction count (for 1.)

All of these need to be weighted, (1 like ≠ 1 message in terms of importance) which means we end up with a calculation that looks like this:

```JS
(messageCount * messageCountWeight)
  + (reactionCount * reactionCountWeight)
  - (threadAgeInDays * threadAgeWeight)
  - (lastActiveInDays * lastActiveWeight)
```

In terms of the weighting, this is a first idea I came up with:

- Message weight: 1
- Reaction weight: 0.2 (i.e. 5 likes = 1 message)
- Thread age weight: 0.25 (i.e. 4 days old = 1 message)
- Last active weight: 0.5 (i.e. 2 days ago = 1 message)

This is obviously just a starting point I made up in my head, I have no clue if that'll give us nice results. I based it on the thoughts that messages are the most important, last active age is more important than thread age and that reactions are the least important. This is very much tbd depending on what gives us nice results.

**Technical notes**

- Since this will be used fairy often, we want an index on the score `r.db('spectrum').table('threads').indexCreate('frecency_score', thread => rank(thread));`
- That means all the properties used in the calculations need to be stored in the `threads` table
- That means we have to denormalize message and reaction counts
- Calculating age in days: `r.round(r.now().sub(thread('createdAt')).div(86400))` (86400 seconds in a day, r.now().sub() gives epoch time)

**Open Questions**

- How do we test this algorithm for nice results?
- How could we incorporate the quality of conversation in the calculation? (maybe unique number of participants?)
- Should we time-bucket somehow, or is thread last active enough? (i.e. a message posted 14 days ago only counts for 50% of a message posted yesterday, a message posted 90 days ago only counts for 10% of a message posted yesterday)

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [x] WIP
- [ ] Ready for review
- [x] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api

**Run database migrations (delete if no migration was added)**
YES

**Related issues (delete if you don't know of any)**
Closes #3718
Based on #3726 (until that's merged you'll also see those changes here)

----

- [x] Add `frecency_score` index to threads
- [ ] Figure out how to sort results by calculation
- [x] Implement in GraphQL API
  - [x] `Community.threadConnection`
  - [x] `Channel.threadConnection`
  - [ ] Others?
- [ ] Implement in old community and channel views?

### CODE REVIEW

**Comment by mxstbr** [comment]
~~After running `r.table('threads').orderBy({ index: r.desc('frecency_score') })` I can already tell you this doesn't work well yet (with the suggested weights from #3718), because it just returns all the threads with 100+ messages at the top. :roll_eyes: We're going to have to find a solution to that... somehow. Maybe we do need to go with time bucketing? 😕 Ugh that'll be so much more complex...~~

**EDIT:** Nevermind I am such a dummy—one cannot `.orderBy('frecency_score')` since that's not a field on the records, so that just didn't do anything 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 

Gotta figure out how to sort by this now, maybe an index was the wrong approach after all! Ugh

**Comment by mxstbr** [comment]
I implemented this in the GraphQL API for `Community.threadConnection` as another argument:

```GraphQL
community(slug: "styled-components") {
  threadConnection(sort: TOP) { # or sort: NEW, which is the default so the current behavior doesn't change
    ...
  }
}
```

WDYT about that?

**Comment by mxstbr** [comment]
Banging my head against how to get this score and then `.orderBy` it in the query. Might have to do something else after all...

**Comment by mxstbr** [comment]
I think I have a plan for how we're going to do this. It's going to be a bit more complicated than anticipated in the beginning, but not too bad:

- Store all threads of a community in a [Redis sorted set](https://redis.io/topics/data-types#sorted-sets) with a key value pair of `threadId: threadScore`
- On new likes or messages to a thread add a new `updateThreadScore` job to bull
- Calculate the new score async in the background from one of our workers (mercury?), then do a `ZADD` to Redis which automatically updates the ranking
- The API then only has to fetch a list of thread ids from Redis and then fetch those threads, which should be super fast

The only thing I'm not sure about yet is how we're going to incorporate thread age decay into the score. Theoretically whenever any single thread gets a new message we'd need to recompute all the communities' threads scores based on their new age, which would be very expensive and annoying. Going to brew on that a little bit more...

**Comment by mxstbr** [comment]
This idea by bitly might work for us? Decaying at read time: https://word.bitly.com/post/41284219720/forget-table

**Comment by mxstbr** [comment]
I think I know how we're going to implement decaying!

Rescoring threads on every read would quickly overwhelm our servers as threads are loaded often. On top of that, recomputing the score based on age every time is unnecessary, since we only count the age in days.

So, let's recompute at read time but only every 24h! Something like this:

- Threads get a `scoreCalculatedAt` property
- That property is set to the current date whenever the score is computed in the worker, no matter why
- When loading a thread if `scoreCalculatedAt < 24h ago` we just return the thread
- If `scoreCalcuatedAt > 24h ago` we add a new job to recompute the score (and return the thread with the current score)

That way, we decay over time without overwhelming our servers! :tada:

Other notes:

-  Every `recalculateScore` job needs to have a generic key (something like `recompute-{threadId}-score`) so that if multiple messages are sent or multiple likes are added (or any other combination of actions on the same thread) in quick succession while the score hasn't been recomputed yet we don't recompute it for every single action
- We could add those "hotness indicators" @uberbryn designed icons for way-back-when really easily once we have the scores. If a thread is in the top 10 of a community currently (i.e. shown on the frontpage) it gets a "very hot" indicator, if it's in the top 25 it gets a "slightly hot" indicator and if it's in the top 50 it gets a "little bit hot" indicator, or something like that

**Comment by brianlovin** [comment]
Awesome thinking here man! Seems like a reasonable approach all around :)

Maybe the score calculation can happen in Mercury and we could do some reputation integrations in the future for threads that are hot

**Comment by mxstbr** [comment]
I just realized we don't even need to store the list in Redis: we could just put the `score` on the thread object itself? That means thread objects would have two new properties, `score` and `scoreUpdatedAt` or something like that.

> Maybe the score calculation can happen in Mercury

Yeah that's what I was thinking too, sounds like a job for mercury 👍

**Comment by mxstbr** [comment]
Started anew since most of the changes in this branch are unnecessary: #3798

**Comment by brianlovin** [comment]
> Started anew since most of the changes in this branch are unnecessary

Sounds good - want to just close this when it's wrapped up?

**Pull request closed without merging**
