### PR TITLE
[WIP] [Mobile v1] Thread feeds: Make sure all possible states are cov…

### PR DESCRIPTION
**Pull request by ryota-murakami**
**Status**
- [x] WIP
- [ ] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)
- mobile

i just create PR, currently under working & investigating:grinning:

**↓ progress note**

### What kind of states are there in web ver Thread card?(under investigationg) and covered mobile ver?

* [ ] **Pinned**
screen shot 2018-05-14 at 2 29 01

* [ ] Actived
* [ ] ${num} messages
* [ ] New Messages!
* [ ] New THREAD!
* [ ] Locked
* [ ] Openchat
* [ ] Channel Name(`Jobs` in the image)
screen shot 2018-05-14 at 2 34 39

### CODE REVIEW

**Comment by mxstbr** [comment]
Yay, thanks for investigating!!

**Comment by brianlovin** [comment]
FYI #3097 has a bunch of changes to thread cards :)

**Comment by ryota-murakami** [comment]
@mxstbr i'm sorry, i closed this PR accidentally, could you re-open it?

**Comment by mxstbr** [comment]
You seem to have deleted the branch, so I can't :confused:

**Comment by ryota-murakami** [comment]
@mxstbr oh that's wired, i renew the branch as alter name.
screen shot 2018-05-16 at 22 19 34

**Pull request closed without merging**
