### PR TITLE
Track first mobile Amplitude events

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- mobile

**Related issues (delete if you don't know any existing issue(s) that could be related to this PR)**

Ref: #3265

This adds first tracking of view events to the mobile apps. This is
based on #3291, so until that's merged you'll also see those changes
here.

Sidenote, we should make sure to track everything automatically as we
build features in the mobile apps from now on! I'll try and get
everything backfilled as good as possible.

### CODE REVIEW

**Comment by brianlovin** [comment]
Ah damn, those conflicts are coming from the setTitle PR I just merged a couple ago - sorry about that! Want to knock those out and then we can ship this.

What do you have in mind regarding automatic event tracking?

**Comment by brianlovin** [comment]
> I'll try and get everything backfilled as good as possible.

If it's cool, can we just make this branch be the complete backfill to reach parity with what we track on web? At least, as far as we can go with what's built on mobile so far. That way after we merge this branch, we know that everything new will need tracking but everything that exists is already good to go.

**Comment by mxstbr** [comment]
> If it's cool, can we just make this branch be the complete backfill to reach parity with what we track on web?

I think it already is potentially? We track sending messages on the backend, so really there isn't much else in the mobile app yet 😅

**Comment by brianlovin** [comment]
Okay! Went ahead and fixed the merge conflicts, I'll keep an eye out for anything else :)

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
