### PR TITLE
Thread Tagging

### LINKED ISSUE #4405: Thread Tagging
We should add an optional thread tagging system similar to GitHub labels.

**High level description**

A whitelist of tags should be able to be defined on a community-level, which can then be used by moderators and owners to tag individual threads.

** Technical sketch**

- Store tags in a `communitiesThreadTags` table, with records that look like this:

  ```JS
  {
    id: 'fdgyit-123',
    title: 'some-string',
    communityId: 'dfqg-community-234'
  }
  ```

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [x] WIP
- [ ] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

**Release notes for users (delete if codebase-only change)**
- Added the ability to tag threads from a list of community-defined tags

**Related issues (delete if you don't know of any)**
Closes #4405

**Todo**

- [x] Add GraphQL types 
- [x] Implement GraphQL types
  - [x] Community.threadTags
  - [x] Thread.tags
  - [x] addTagsToThread
  - [x] removeTagsFromThread
  - [x] addThreadTagsToCommunity
  - [x] removeThreadTagsFromCommunity
  - [x] Add threadTags loader and use in resolvers
- [x] Implement thread tagging UI
  - [x] Open modal which shows list of tags
  - [x] Select and un-select certain tags
  - [x] Fix updates
  - [ ] Polish
- [x] Implement community thread tag list settings UI
  - [x] Show list of tags
  - [x] Add tag with title
  - [x] Remove tag
  - [x] Polish
- [x] Proper tag icon
- [ ] Implement tag filtering backend
- [ ] Implement tag filter UI
- [ ] Implement tag UI on thread feed cards

### CODE REVIEW

**Comment by mxstbr** [comment]
This first commit adds a first couple types to the GraphQL schema.

New mutations:

- addTagsToThread
- removeTagsFromThread
- addThreadTagsToCommunity
- removeThreadTagsFromCommunity

New fields:

- Community.threadTags
- Thread.tags

None of the thread filtering by tags yet. 

@brianlovin does that cover all the functionality we need? Are the names a-okay?

**Comment by mxstbr** [comment]
I'm not sure what the best way to go about filtering results by tags is and how to store the thread-tags relation.

Right now, I stored a `tags` field on thread objects:

```JS
{
  id: 'thread-asdf-1',
  tags: ['tag-asdf-1', 'tag-asdf-2']
}
```

This makes it relatively trivial to render the tags with a thread (the `tags` resolver simply does a `loadMany(...thread.tags)` to load the tag titles) but unfortunately makes filtering thread lists by tag pretty hard.

My idea was to use a multi index on the thread objects to efficiently get all threads with a certain tag, something like:

```JS
r.db('spectrum').table('threads').indexCreate(
  'channelIdAndTag',
  // For each thread, add an indexes for each tag they have that is
  // ['thread-asdf-1', 'tag-asdf-1']
  (thread) => thread('tags').map(tag => ([thread('id'), tag])),
  { multi: true }
)
```

This makes it easy to get all threads in a channel with a specific tag:

```JS
r.db('spectrum')
  .table('threads')
  .getAll(['channel-asdf-1', 'tag-asdf-1], { index: 'channelIdAndTag' })
```

Unfortunately, this doesn't allow filtering threads without any tag and filtering threads with more than one specific tag. 

We could also store the tags of a thread in a `threadsTags` join table:

```JS
{
  threadId: 'thread-asdf-1',
  tagId: 'tag-asdf-1'
}
```

That would require a join to show the tags on a thread, but would allow filtering by any number of tags (`r.table('threadsTags').getAll('tag-1', 'tag-2', { index: 'tagId' })`). Unfortunately this would be pretty expensive as soon as you start accounting for private channel memberships, as you have to join with the threads table and filter that by channel IDs—not ideal either.

@brianlovin you're the expert on that front, but maybe using Algolia would be preferable for this? Index any tag change, and then allow "searching" by tag, would that be possible? I imagine something like this in `dbThreadToSearchThread`:

```JS
  return {
    channelId: thread.channelId,
    communityId: thread.communityId,
    threadId: thread.id,
    ...
    tags: await getTags(...thread.tags),
  };
```

Could that work?

**Comment by mxstbr** [comment]
Getting somewhere with the UI! This will need a lot more polish (and an icon, cc @superbryntendo) but one can now add and remove tags to and from communities. 

I'll be working on the modal to tag threads next!

**Comment by mxstbr** [comment]
Latest commit makes the edit thread tags modal functional, although for some reason Apollo Client doesn't update the local cache with the new tags and thusly changes aren't reflected until you refresh—I'm not sure why that is 🤔

**Comment by mxstbr** [comment]
Figured it out, fixed in latest commit!

**Comment by brianlovin** [comment]
Spent quite a while writing and rewriting thoughts here @mxstbr. This is very tricky.

In general I'm opposed to rendering thread feeds based on Algolia, only because that is a massive dependency to put on a third party vendor. If Algolia went away today and we lost search, it wouldn't kill Spectrum. If we lost thread feeds, it would. So while it's technically possible to search by tag and channelId, we probably shouldn't in the use case of thread feed filtering.

One thing that jumps out in particular is:

> Unfortunately this would be pretty expensive as soon as you start accounting for private channel memberships, as you have to join with the threads table and filter that by channel IDs—not ideal either.

We should make it so that matching permissions is *not* expensive. We have to do this anyways for basically everything we send to the client, so it *should* be as fast and performant as possible. Dataloader is currently helping us here, and maybe it will make this filtering by permissions not a big deal. If it is a bottleneck, let's figure out how to get fast permissions baked into context or something :/

Otherwise we should consider denormalizing more fields onto the `threads` model so that we simply need to do:

```js
const threads = await getThreadsByCommunityIdAndTag(communityId, [ tag1, tag2 ])
const permissions = await loaders.usersChannels.load(userId)

const filteredThreads = threads.filter(thread => {
  const isPublicThread = !thread.isPrivateChannel // if we denormalize
  const userIsMemberOfChannel =  permissions.some(usersChannel => {
    return usersChannel.channelId === thread.channelId && usersChannel.isMember
  })
 
  return isPublicThread || userIsMemberOfChannel
})

return filteredThreads
```

I also think we should consider denormalizing the `threadsTags` even more so that they look like:

```js
threadId: string,
channelId: string,
communityId: string,
tagId: string
```

That way we can do things like `getThreadsByChannelIdAndTag` or `getThreadsByCommunityIdAndTag` - of course, we'll just have to account for this denormalization if threads get moved between channels. 

Does this sound like a logical path? Basically my suggestion here is denormalize to make this less painful :P

**Comment by mxstbr** [comment]
> In general I'm opposed to rendering thread feeds based on Algolia, only because that is a massive dependency to put on a third party vendor.

I'm not sure I understand this point.

The only thing that would immediately go away if Algolia went away is searching by thread tags, just like right now you can search by community or channel. Searching by thread tags isn't like the most important use case or anything and it's not going to destroy Spectrum if it doesn't work for a couple days, right?

**Comment by brianlovin** [comment]
Some questions:
- should tags only be visible to team members? since they're the only ones that can add and manage them, maybe it's good to just consider thread tagging an internal mechanism for now
- we need a way to remove tags from threads if the tag gets deleted. otherwise it's possible for a thread to have several tag ids that don't actually point to anything in the db. not deal-breaking, but just leads to lots of unsanitary data. the only problem is i'm not sure how to do this, without iterating through every thread in the community whenever a tag is deleted, to see if the thread contains that tag. *or* we create a multi-secondary-index on the threads table for the tags array, but then that blows up storage a bit. wdyt?

**Comment by brianlovin** [comment]
@mxstbr just pushed up my work from today - still haven't gotten to sorting and filtering from the frontend, because i'm still not exactly sure how it should work or what the user experience should be there. will have a think on this, but seems like we're running out of time to ship this before xmas. 

want to review the changes i made so far in:
- creating/editing tags
- thread tags modal
- rendering the tags on thread previews (this still need a bit of work...would love ideas)

**Comment by mxstbr** [comment]
> should tags only be visible to team members? since they're the only ones that can add and manage them, maybe it's good to just consider thread tagging an internal mechanism for now

If that's the case then we need to make that clearer in the UI. I don't feel strongly either way, if you think about GitHub their tags they are also only managed by team members but visible to everybody.

> we need a way to remove tags from threads if the tag gets deleted. otherwise it's possible for a thread to have several tag ids that don't actually point to anything in the db.

I honestly think it's not worth the engineering/perf work to properly sanitise this, the storage impact is minimal anyway and if it gets out of hand we can build it down the line (I really don't think it will). The API handles this case gracefully anyway IIRC.

----

UI looks great to me locally, colors are good too! 👍 The tags on the feed cards are a bit awkward but it's fine imo.

If you're okay with it, what would you think about shipping this without the ability to filter by tag and following up with that later? This should already help support communities manage their load, even without the ability to fiilter, just by making it easier to see at a glance who needs help and who doesn't, right?

**Comment by brianlovin** [comment]
> If that's the case then we need to make that clearer in the UI. I don't feel strongly either way, if you think about GitHub their tags they are also only managed by team members but visible to everybody.

The difference for me is that if you render tags on thread previews (eg in the inbox), it will become impossible to scan because each community might use the same colored tag to mean different things. The inbox would basically be a mess either way.

> I honestly think it's not worth the engineering/perf work to properly sanitise this, the storage impact is minimal anyway and if it gets out of hand we can build it down the line (I really don't think it will). The API handles this case gracefully anyway IIRC.

Fair enough :)

> The tags on the feed cards are a bit awkward but it's fine imo.

Agreed, will try to polish a bit more. @superbryntendo if you want to pull this branch at some point, run `db:migrate` and test out the thread tags that'd be great to get your input.

> If you're okay with it, what would you think about shipping this without the ability to filter by tag and following up with that later? This should already help support communities manage their load, even without the ability to filter, just by making it easier to see at a glance who needs help and who doesn't, right?

I just think the filtering part is the only thing that really makes thread tagging useful. So yeah we could ship this branch as an iteration, but the filtering part is where I think the real value will be found for communities.

**Comment by brianlovin** [comment]
@mxstbr some thoughts on how to pull this off:
1. Use vulcan for updating tags in aloglia as they are added/removed; this can happen async
2. Store array of tag ids on algolia threads index. Follow https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/how-to/filter-arrays/?language=javascript#dataset-example for making sure that array can be used as a filter (note: added shared algolia login to 1password)
3. Pass an optional array of tags strings to the `searchThreads` query input in graphql
4. In `api/queries/searchThreads.js` where we perform a thread search within a community view, we loop through the array of tags and append them to the filter string that algolia requires. So instead of `communityId: "foo"` as the filter, we will end up with `communityId: "foo" AND (tags: "tag1" OR tags: "tag2" OR tags: "tag3")`

Algolia should be able to handle the rest.

So then on the client you just have a button that executes the `searchThreads` graphql query with an array of `tagIds` as one of the props. I believe this approach will make it trivial for admins to select one or more tags and return any thread that matches one of those tags.

That behavior could also be different, I suppose, so that if you had multiple tags selected it would only return threads containing ALL of them. Eg. `communityId: "foo" AND tags: "tag1" AND tags: "tag2" AND tags: "tag3"`

Let me know if this makes sense; if it's not clear I will try to carve out some time to do this, just been tough with other things coming up this week :*

**Comment by brianlovin** [comment]
Continued working on this today @mxstbr it's just going to take a while; I'm working on first getting jobs in Vulcan to make sure that tags are synced to Algolia when they are added/removed from a thread, and when a tag is deleted entirely from the community.

The next step after that is to work on the community profile view to enable an admin to view a feed of threads based on selected tags. There's some design work to be done here; I'm thinking of consolidating 'Trending' and 'Latest' into a single dropdown, and then in that dropdown providing a third filter to view threads with a certain tag.

The community view hasn't been touched in a *long* time, so there's some pretty gnarly frontend code there that I'll have to work through.

If you want to keep working on this in parallel with me, since I'm stopping for the day today, it would be useful if you wanted to tackle the Vulcan jobs. Essentially we just want to always keep the tag ids stored in algolia in sync with the threadTags stored in our db. If you don't get to this, no worries.

**Pull request closed without merging**
