### PR TITLE
Temporarily disable alpha autodeploy while testing a design

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**

### CODE REVIEW

**Review by mxstbr — COMMENTED** [review]
Wanna comment it out so I don't have to figure out how to do this again in two weeks? :sweat_smile:

**Comment by brianlovin** [comment]
Surely :)

**Review by mxstbr — APPROVED** [review]
Let's merge this, and then in your message refactor branch uncomment it again so we don't forget to re-enable it once/if we ship that!

**Comment by brianlovin** [comment]
Will do!

**Pull request merged**
