### PR TITLE
Migration to remove old usersNotifications

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Run database migrations (delete if no migration was added)**
YES

@mxstbr you can run this locally and quit it after a couple seconds to see it running async

### CODE REVIEW

**Review by mxstbr — COMMENTED** [review]
Apart from impact on live db cluster (see test screenshots in Slack), this LGTM. Is there any way we can reduce the impact? Maybe stagger the queries, run the next batch 2s after the last one finished or something like that? Would that help?

**Comment by brianlovin** [comment]
> Maybe stagger the queries, run the next batch 2s after the last one finished or something like that? Would that help?

Possibly? I could throw a timeout on it?

**Comment by brianlovin** [comment]
@mxstbr this migration is done. I've also added a cron job to repeat the cycle each day. Ready to ship if it looks good to you!

**Review by mxstbr — APPROVED** [review]
LGTM!

**Pull request merged**
