### PR TITLE
Bug bash day

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)
- hermes

Working through some sentry bugs.

https://github.com/withspectrum/spectrum/pull/3188/commits/f147761ee7cee262981191048659b2b4d39ea2fe => https://sentry.io/space-program/spectrum/issues/558113660/?query=is:unresolved

https://github.com/withspectrum/spectrum/pull/3188/commits/5e4479aeb18e5cfe11b47a8888215f94373e7540 => https://sentry.io/space-program/spectrum/issues/564742242/?query=is:unresolved

https://github.com/withspectrum/spectrum/pull/3188/commits/a3be231a4b9b3637c0396ec029b2f3b09c70b700 => https://sentry.io/space-program/spectrum/issues/545394207/?query=is:unresolved and https://sentry.io/space-program/spectrum/issues/562870198/
cc @mxstbr ^^ => I don't want to go too far down the rabbit hole of supporting super old versions of IE, but we are seeing a fairly regular stream of bugs affecting edge and even IE11. We can simply extend the default polyfills provided by polyfill.io as seen in this commit, although I'm not sure what other things we'll have to keep adding to this over time. I spent a while this afternoon trying to find a more cohesive way to polyfill this kind of stuff, but obviously it just adds complexity if we try to keep bundle size small for users on modern browsers. The two added in this commit add a few hundred bytes for bugs affecting maybe a few dozen users. Wdyt?
Documentation: https://polyfill.io/v2/docs/examples#aliases
Actually, this is affecting hundreds of users: https://sentry.io/space-program/spectrum/issues/562170782/?query=is:unresolved

https://github.com/withspectrum/spectrum/pull/3188/commits/e4a3538eb9fcd4dcda134f8e1250d8d063798a0a => https://sentry.io/space-program/spectrum/issues/565877960/?query=is:unresolved

https://github.com/withspectrum/spectrum/pull/3188/commits/0ad80a183b6fa3a9dcd49f335c6efd9285a58ba9 => https://sentry.io/space-program/spectrum/issues/530053952/events/21267481078/ - this one is pretty important as we have some invalid emails getting into our db which have been causing trouble in hermes (to the tune of 257 events in the last 30 days)

https://github.com/withspectrum/spectrum/pull/3188/commits/b50082d25ce5524bb163fd9f2182eafa8fe09783 => https://sentry.io/space-program/spectrum/issues/513764806/?query=is:unresolved - @mxstbr let's chat about this one specifically. Any thoughts on how we could properly flowtype all of our loaders? Flow should have caught that we don't have an `isDeleted` field on a `DBThread` 😅

https://github.com/withspectrum/spectrum/pull/3188/commits/f7067317a31e66a3427c340ab308ae4958653ab3 => this is a temporary fix to prevent https://sentry.io/space-program/spectrum/issues/566970820/?query=is:unresolved from crashing the frontend. Issue opened  at https://github.com/withspectrum/spectrum/issues/3190 to discuss the proper fix

https://github.com/withspectrum/spectrum/pull/3188/commits/00d58086919acc6a9362ae4b5445ddab3b702910 => https://sentry.io/space-program/spectrum/issues/498612908/?query=is:unresolved - additionally I've improved some of the default behaviors when a person presses `esc` or clicks outside of the search results :)

### CODE REVIEW

**Comment by brianlovin** [comment]
Kk this is ready for review + discussion @mxstbr - each commit is pretty self contained. Let's discuss about:

- polyfilling IE to handle `Array.find` and `Symbol.iterator`
- how to best flowtype our loaders

**Comment by mxstbr** [comment]
> Any thoughts on how we could properly flowtype all of our loaders?

Yes, I looked into this but it's hard and not worth the effort atm imo.

> polyfilling IE to handle Array.find and Symbol.iterator

I thought the point of `polyfill.io` was that it automatically detects which browser a user's using and only sends them the most minimal polyfill? Oh well if this fixes things it's fine with me!

**Review by mxstbr — APPROVED** [review]
LGTM, thank you!

**Comment by brianlovin** [comment]
> I thought the point of polyfill.io was that it automatically detects which browser a user's using and only sends them the most minimal polyfill?

I thought so, too :/

**Pull request merged**
