### PR TITLE
Add mention suggestions to chat input

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [x] WIP
- [ ] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

### CODE REVIEW

**Comment by mxstbr** [comment]
@brianlovin this is functional!! :tada: Now it's just a matter of making the mention suggestions look nice, would you mind looking at that?

**Comment by mxstbr** [comment]
Note that the mentions in the chat input still look like text-only. I tried for a while to adjust the styling to look like mentions in messages, but due to the way `react-mentions` is implemented (it overlays a div of the same size as the textarea) it is basically impossible to change any styling except for the background color.

Unfortunately, any background color I tried looked bad, so I have decided to just leave it as-is and "only" add the suggestions popover!

**Comment by brianlovin** [comment]
@mxstbr amazing work! Going to pull and review this today :)

**Comment by brianlovin** [comment]
Hey @mxstbr spent the afternoon digging into this - quite tricky to get this styling right. Will need more time to work on this.

**Comment by mxstbr** [comment]
Sounds good, let's aim for Monday?

**Comment by brianlovin** [comment]
@mxstbr this is ready for a review. Note the major change in my code: 
- when messages from a thread load, i pass a callback to the thread container with the messages list. this messages list is then sorted and filtered into an array of users where users are either the thread author or a thread participant. I chose to do this instead of using the graphql thread.participants field because i want to prevent an extra fetch at the db (since messages list already contains this info) and because i don't want to add the `thread.participants` field overhead to graphql queries if @ mentions don't get used.
- this list of participants is then shown by default as soon as the user types `@` - this prevents a network request if someone is trying to mention a participant or the thread author
- this also works in DMs

Additionally cleaned up some styling - it's not perfect, but looks better than it did :)

**Comment by mxstbr** [comment]
That is super nice!! Will dig into this today, thanks for taking a look with your arm ✨

**Comment by mxstbr** [comment]
My latest commit improves upon your great idea a bit more.

Rather than hiding the participants as soon as a search query is entered, I also search the participants array and prepend it to the search results! This feels really really good, I love it. 

This is ready for another review! ✨

**Comment by brianlovin** [comment]
Awesome tweak to that search logic, thanks @mxstbr! I'll get this live today :)

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
