### PR TITLE
Render slider at full thread URLs on the client-side

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

This makes it so we render the thread slider if a user visits a proper thread URL (e.g. `/spectrum/general/whats-up~asdf123`) from the frontend, but still shows the full thread view when the URL is visited generally.

Based on this example: https://reacttraining.com/react-router/web/example/modal-gallery

**TODO**

- [x] Figure out how to close the slider
- [x] Replace all links to ?thread on the frontend
- [x] ~Remove redux state~~ nvm we need this after all

### CODE REVIEW

**Comment by mxstbr** [comment]
I think we can ship this as-is without reworking the slider to be a modal that shows the full thread view, but that would be an _epic_ follow-up PR @brianlovin.

**Comment by mxstbr** [comment]
Just gotta replace all links to `?thread` on the frontend and this is ready for a first test and review! Right now it only works on the community view.

**Comment by brianlovin** [comment]
@mxstbr this is awesome! Yup, we could definitely follow-on with showing the full thread view in the modal

**Comment by mxstbr** [comment]
@brianlovin I have replaced all `?thread` URLs throughout the entire frontend with links to the full thread URLs opened as modals! :tada: 

There is one small todo remaining where in some edge cases (new reaction notifications) we do not have the full thread data, only the ID, and thusly cannot open those links in a modal. I need to add support to open/redirect `/thread/<id>` URLs in the modal, but honestly that will be fairly hard and I think this is good enough to ship as-is?!

Definitely at least ready for a review here, and I think we can ship with new reaction notifications opening clicks on the link in the text to the thread in a new tab.

**Comment by brianlovin** [comment]
> Definitely at least ready for a review here, and I think we can ship with new reaction notifications opening clicks on the link in the text to the thread in a new tab

This is so good dude!! Amazing work here. Let's ship and iterate.

Also, this kind of makes me want to try a 2-column inbox :O

**Review by brianlovin — APPROVED** [review]

**Comment by mxstbr** [comment]
Yep I was about to say, what if the inbox was two columns like the new reddit? No need for separate inboz thread experience, consistency...

**Comment by brianlovin** [comment]
I would very much like to experiment with this, at least :)

**Pull request merged**
