### PR TITLE
Mobile buttons

### LINKED ISSUE #3313: [Mobile] Proper buttons
Right now we just use the standard react-native `<Button />` across the board, but that doesn't look very great honestly:

screen shot 2018-06-13 at 11 06 34

We should re-create our button setup from the web client.

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review 
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- mobile

**Related issues (delete if you don't know any existing issue(s) that could be related to this PR)**

Closes #3313

### CODE REVIEW

**Comment by mxstbr** [comment]
This is done—I'm happy with the component API!

It still doesn't _look_ perfect by any means (especially with icons) and doesn't cover everything we'll need, buuuut it's enough to use it throughout the app and then iterate on as we go along and need different states.

This is the API, critique very welcome!

```
type Props = {
  onPress: () => any,
  title: string,
  state?: 'disabled' | 'loading',
  size?: 'large',
  color?: (props: { ...Props, theme: Object }) => string,
  icon?: GlyphTypes,
  // NOTE: Passed in via withTheme, no need to pass manually
  theme: Object,
};
```

**Comment by brianlovin** [comment]
@mxstbr it's really nice! I made a couple small tweaks on the styling + layout, and renamed the `title` prop to `label` as that seems to be a bit more ergonomic when composing button props. But agreed, open to iteration here for sure and adding more types as needed! Thanks for doing this, looks great so far :)

**Review by brianlovin — APPROVED** [review]

**Comment by mxstbr** [comment]
> and renamed the title prop to label as that seems to be a bit more ergonomic when composing button props

Fwiw the reason I went with `title` in the first place is because the core ReactNative `<Button />` uses title—I don't really care though :blush:

**Comment by brianlovin** [comment]
Oh damn, didn’t see that. Okay I’ll switch that back for better dx, thanks for the context!!

________________________________

**Comment by mxstbr** [comment]
No worries, really not that big of a deal.

**Pull request merged**
