### PR TITLE
[A11Y] - Introduce VisuallyHidden component

### PR DESCRIPTION
**Pull request by AgtLucas**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

As discussed [here](https://github.com/withspectrum/spectrum/pull/2717#issuecomment-378935245), this PR introduces the `<VisuallyHidden>` component, which allows us to hide a text visually but still provide its value to screen readers.

**Usage:**

A very basic example could be the Explore option in the header:

screen shot 2018-04-05 at 16 27 47

```jsx
<span>
  Explore <VisuallyHidden>our awesome communities</VisuallyHidden>
</span>
```

Please, don't take the example above serious, I'm sure there are way better use cases for this component throughout Spectrum's codebase. :)

### CODE REVIEW

**Review by mxstbr — APPROVED** [review]
The lock file changes are kinda weird but whatever—thank you so much, this looks perfect!

**Comment by AgtLucas** [comment]
@mxstbr Probably it's because my Yarn version :(

**Comment by brianlovin** [comment]
This is great! Would love to see more examples where this could be useful and we can start adding them in as we go. I imagine any case where we have an icon-only. button would be perfect.

**Comment by AgtLucas** [comment]
@brianlovin The icon-only, depends. Is the icon a SVG? If so, we can provide some title for the SVG itself. :)

**Comment by brianlovin** [comment]
> The icon-only, depends. Is the icon a SVG? If so, we can provide some title for the SVG itself. :)

Ah, all our icons are SVG so that is probably better!

**Comment by brianlovin** [comment]
Ah shoot I merged this too soon - I'll add a quick fix, but just a small thing in the future @AgtLucas we require all new files to be flow-typed. Going to add that quickly.

**Comment by brianlovin** [comment]
https://github.com/withspectrum/spectrum/pull/2739 for ref :)

Also I don't think we need `React` in scope if we're just exporting a styled component.

**Comment by AgtLucas** [comment]
@brianlovin Ah ok! Good to know!

Probably I've missed the CONTRIBUTING guide, my bad!

**Comment by brianlovin** [comment]
I'm actually not sure if we mention that in the contribution docs anywhere...

**Comment by brianlovin** [comment]
Ah we do - it's in root `README.md` in the `rules` section - all good!

**Pull request merged**
