### PR TITLE
Media Providers

### PR DESCRIPTION
**Pull request by Ponjimon**
**Status**
- [x] WIP
- [ ] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

So, this was just an idea of mine, and it's WIP but it would be nice if we could have that in the future.
It works so far and could easily be extended with basically any service that allows to embed their stuff via iframes. What do you think?

### CODE REVIEW

**Comment by mxstbr** [comment]
@brianlovin @uberbyrn didn't we implement this a while ago? Where did that code go?

**Comment by brianlovin** [comment]
Nope we didn’t - this looks awesome though and definitely a better approach than my one-offs! I’m wondering if we could move all the other regexps into this media provider format?

**Comment by Ponjimon** [comment]
Hahaha, okay, I see why flow was not enabled in those files yet :D A bunch of errors...

Currently struggling with this: https://pnda.me/2vleIKK

Any idea why this is happening? Not sure why this wouldn't work

**Comment by mxstbr** [comment]
That doesn't work because you're spreading an array into an object. :blush: I'm not 100% sure what you're trying to do in that code?

**Comment by mxstbr** [comment]
I implemented this again in #4564, we now automatically embed youtube videos, codesandboxes, codepens, etc!

Even though we did not merge this, I based much of the idea and code on this, thank you for the contribution @lookapanda! :pray:

*Here is the final version in case you are curious: https://github.com/withspectrum/spectrum/blob/alpha/shared/draft-utils/add-embeds-to-draft-js.js*

**Pull request closed without merging**
