### PR TITLE
Maybe fix req.user bug

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [ ] Ready for review
- [x] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

Replaces #3955

### CODE REVIEW

**Comment by mxstbr** [comment]
Deploying to alpha.

**Comment by mxstbr** [comment]
Seems to work fine on alpha, but then again the last version did for me too... :confused: @brianlovin shall we deploy this to prod?

**Comment by mxstbr** [comment]
Deployed to prod 🤞

**Comment by mxstbr** [comment]
Seems to work fine! :100:

**Review by brianlovin — APPROVED** [review]
LGTM :)

**Pull request merged**
