### PR TITLE
Unified community sidebar

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

**Todo**

- [x] Unify the sidebar on the community view, thread view and channel view
- [x] Highlight active channel in sidebar
- [x] Remove sidebar from new thread modal

### CODE REVIEW

**Comment by brianlovin** [comment]
This is much better, but lacks an affordance to get "back to the home view" of the community if you're viewing a channel or thread. I still think we should ship this, but I imagine people will get confused with "how to get back to the community landing page"

**Comment by brianlovin** [comment]
There is also not a way to access channel settings anymore with this sidebar...trying to think of a solution here.

**Comment by brianlovin** [comment]
Pushed up small iteration to add channel settings link to list item.  This is fine for now but maybe we should show list item actions on hover in the future.

**Comment by brianlovin** [comment]
E2E will need to be updated to account for lost channel profile card and trending threads

**Comment by brianlovin** [comment]
Reverting that change - just way too noisy. The gear icon still exists at the sidebar heading, so that should be enough for now

**Comment by mxstbr** [comment]
Yeah you are right that could be confusing. We might need some sort of "breadcrumbs"-style top bar?

**Comment by mxstbr** [comment]
Jfc I messed this branch up nooooooo

**Comment by mxstbr** [comment]
Unmessed it up with some solid git magicery! 😍 This is ready for a review @brianlovin, including the new full-width thread modal!!

**Comment by brianlovin** [comment]
First thing I noticed is that you can't click the overlay to dismiss the thread modal :)

Second small nit immediately is that the community profile peeks out to the left side in the background. Ideally the thread would match the width of both columns, right?

**Comment by mxstbr** [comment]
Fixed the overlay clicking—not sure how best to solve the layout issue of the community profile peeking out a little bit, I can't figure out the right grid syntax. Any ideas/mind taking a look at that and cleaning it up?

**Comment by brianlovin** [comment]
> not sure how best to solve the layout issue of the community profile peeking out a little bit, I can't figure out the right grid syntax. Any ideas/mind taking a look at that and cleaning it up?

Just realized this is likely impossible - the peeking is because of the scrollbars that might appear in the community feed, but not in the thread modal. Going to ignore this nit for now.

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
