### PR TITLE
fix(Routes): improve props type

### PR DESCRIPTION
**Pull request by ryota-murakami**
**Status**
- [x] Ready for review

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

improve `<Routes />` component props type.
current code doesn't being explicit about `maintenanceMode` param and using it into the component but only use to `if` condition, flow will not say error that(i don't know up until now)

- try flow
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxgQDRgDeYAwnDnAHantEC+YUeVmADkeCtWGpUlGOQDOcsAFkAnizaduYUgA8CXACaL1uTQQA89HgD4GqAJBj2B0ngAUASjtgfv++igwNwIAC3Q5ADpsQWxI9nJMUi8rMGBgMHY4bTxBPDA4SkoAVxz0dgBzVF9fB0dSAhL2IPMDdAA3a3pQ8KiYuITSHnNgVo6PBx5USbAgA

thank you :grinning:

### CODE REVIEW

**Comment by ryota-murakami** [comment]
about `try flow` link, you have to select flow type at `v0.66.0` manualy.
that page selected latest `v0.72.0` as a default(occuring error)

screen shot 2018-05-13 at 9 44 33

**Review by mxstbr — APPROVED** [review]
Thanks for this! We only ever had to use this once before, so it wasn't documented—since this won't even work anymore (due to our caching) we should probably just remove all the maintainance mode code entirely. Mind opening a new issue about that?

**Comment by ryota-murakami** [comment]
@mxstbr oh i see, i'm motivated about that!
can i open **remove all unused maintenance mode code** issue?
probably i'll start work after https://github.com/withspectrum/spectrum/pull/3084

**Comment by mxstbr** [comment]
Yes please open it!

**Pull request merged**
