### PR TITLE
Spinner changes button sizes 1919

### PR DESCRIPTION
**Pull request by cutjavascript**
**Status**
- [x] WIP
- [ ] Ready for review
- [ ] Needs testing

**Release notes for users (delete if codebase-only change)**
- Fix for https://github.com/withspectrum/spectrum/issues/1919

Need help to make sure in right direction. Regression tests have to be run

### CODE REVIEW

**Comment by cutjavascript** [comment]
Basically need to know if there are test cases or any automation scripts to use to check this??

**Comment by cutjavascript** [comment]
@mxstbr  , is it okay if circleci: test_web fail, do I need to pass each and every test?

**Comment by brianlovin** [comment]
No worries on e2e test failing, it's super flaky right now, we're working on it here: https://github.com/withspectrum/spectrum/pull/2674

**Comment by brianlovin** [comment]
Unfortunately we don't have any automated tests to check this for all our button types :/ 

At one point I had explored setting up a storybook instance for component testing, but it never got anywhere.

To automate this we'd need to hook into a component testing library somehow - let me know if you're interested in exploring that. Otherwise we can at least get a manual pass on this by just rendering a bunch of buttons on a view and toggling all the loading states :P

**Comment by cutjavascript** [comment]
I would be interested in exploring that👍.
Point me in the right direction

**Comment by brianlovin** [comment]
After #2821 ships we'll have a much better way of testing this!

**Pull request closed without merging**
