### PR TITLE
Update banning users docs

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

If we ban a person we should also ensure they never get weekly digests, daily digests, new thread notifs, new dm notifs, etc.

### CODE REVIEW

**Comment by tomscholz** [comment]
Wouldn't it make sense to implement this kind of stuff into the admin ui?

**Comment by brianlovin** [comment]
Yes - this is all temporary measures since building the UI + backend for it will be >1hr, and so far we've had to ban 0 people, and banning someone with this method will take <5mins, so the tradeoff is still in favor of doing this manually for now :P

**Comment by tomscholz** [comment]
Makes sense ^^

**Review by mxstbr — APPROVED** [review]
APPROVE

**Pull request merged**
