### PR TITLE
Re-enable request-level rate limiting

### PR DESCRIPTION
**Pull request by mxstbr**
- [x] WIP

Reverts withspectrum/spectrum#4660

Have to investigate why it did not work before first though!

### CODE REVIEW

**Review by brianlovin — DISMISSED** [review]
LGTM but I'll let you deploy and monitor since this broke the deployment last time, right?

**Comment by mxstbr** [comment]
Yes this is not ready! Have to figure out why it breaks 😅

**Comment by brianlovin** [comment]
Oh duh, I didn't read the WIP label :P

**Comment by mxstbr** [comment]
I think the issue I hit with the deployment of this was just the connection error due to having too many deploys with 20 instances.

I am going to deploy this to prod API and see what happens, if it breaks I will quickly revert. Thank god for DataDog so we actually know immediately whether anything is broken or not ✨

**Comment by mxstbr** [comment]
This is deployed in prod for the API and works! :tada: Going to try hyperion and then merge if that works too ✨

**Comment by mxstbr** [comment]
This also works for hyperion! :tada: I also cleaned up the hyperion error page to look nice like the other one:

screenshot 2019-02-21 at 13 30 10

Going to ship this :100:

**Comment by mxstbr** [comment]
Actually, nevermind I found a bug: we need to not-rate-limit static files from hyperion, otherwise we will hit that rate limit error immediately after one page load.

**Comment by mxstbr** [comment]
Hyperion rate limits are a bit too low for production:

screenshot 2019-02-21 at 14 22 26

Going to up those a bit and try again!

**Comment by brianlovin** [comment]
Good stuff @mxstbr - is this live now?

**Comment by mxstbr** [comment]
This is live in the API, but I have not tested the new hyperion limits in production yet.

**Comment by mxstbr** [comment]
This is live with `10 req / 20s` and seems fine in DataDog! Going to merge :100: :fire:

**Pull request merged**
