### PR TITLE
First pass at mobile toast system

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- mobile

Still WIP but this would be nice to pair on @mxstbr, if we can this week. Need to figure out how to handle a "queue" system for toasts so that only one shows at a time.

### CODE REVIEW

**Comment by mxstbr** [comment]
> Need to figure out how to handle a "queue" system for toasts so that only one shows at a time.

I've spent some time thinking about this, but honestly have no clue how to go about building that. I think it's not worth it to add all that complexity just to make sure we only show one toast at a time, it's not that big of a deal to have two there. (and even that's pretty damn unlikely unless you repeatedly do some action) Let's just not focus on this and get this done instead?

**Comment by brianlovin** [comment]
Gotcha; okay I'll do another pass at this and simplify the code a bit then to ignore trying to queue things for the time being and just make sure that things stack neatly in case multiple come in at the same time

**Comment by brianlovin** [comment]
Alright @mxstbr - this took me a bit longer than I'd hoped, but I think it's in a much better place and can *roughly* handle stacking. To test locally just long-press a thread item in the home feed and either lock/unlock it. Once we merge this I'll open another PR to implement more toast responses to actions throughout the app :)

**Review by mxstbr — APPROVED** [review]
Wowzers, this is super sweet! Nitpick: I feel like the alerts could be a tiny bit smaller (less height), but it's not a biggie so I'll ship this!

**Pull request merged**
