### PR TITLE
Dont use localStorage as an auth mechanism

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [x] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

This is on alpha and needs further testing. The goal of this PR is to move away from having 2 confusing mechanisms for determining if a user is logged in: a server response to the `getCurrentUser` query vs localstorage.

I just moved the `withCurrentUser` hoc from our mobile work into the web app, and replaced any instances where we were pulling `currentUser` from redux (e.g. localstorage) with that wrapper. This required some refactoring to make sure that thread param redirects continue to work, that `/me` redirects work, etc. I've tested quite thoroughly locally with both client-side rendering and ssr with local hyperion.

### CODE REVIEW

**Comment by brianlovin** [comment]
Since this PR is fairly heavy and lots of small import/export changes, the main logic to review would be `src/index.js`, `src/routes.js`, `src/components/withCurrentUser`, `src/components/thirdPartyContextSetting`, `src/components/redirectHandler`, and `hyperion/renderer/index.js`

**Comment by brianlovin** [comment]
Not totally sure whats going on with these e2e tests; they run locally so...will figure it out tomorow

**Comment by mxstbr** [comment]
This sounds like a great plan, will dig into this later today with a thorough review!

**Comment by brianlovin** [comment]
I ran every spec file locally (one at a time) and they pass, so if they keep failing it's likely a problem with the tests running in sequence or with our testing env

**Comment by mxstbr** [comment]
Ah damn sorry, I forgot to review this today! One sec

**Comment by mxstbr** [comment]
Overall looks good from a skim of those vital changes you mentioned above, let's see if we can get e2e tests to pass and then do a deploy on alpha!

**Comment by brianlovin** [comment]
The cypress videos + screenshots have been helpful here; unfortunately the output is very different than if I run the tests locally, so will try to debug slowly :P

**Comment by brianlovin** [comment]
Okay I give up @mxstbr - could you take a look at this tomorrow? Getting some weird errors in CI around `cannot read property 'slug' of undefined` but can't get this to happen locally.

**Comment by mxstbr** [comment]
I will!

**Comment by mxstbr** [comment]
I can't seem to sign in with GitHub locally on this branch? It just redirects me to the login page.

**Comment by mxstbr** [comment]
Even with the session cookie set and manually going to `localhost:3000/?authed=true` it throws me back to the marketing homepage.

**Comment by mxstbr** [comment]
When I go to a community view with the session cookie set:

screenshot 2018-11-20 at 09 40 17

That's probably why e2e tests fail? 😅

**Comment by mxstbr** [comment]
Yeah I can't seem to sign in, not sure what's going on

**Comment by mxstbr** [comment]
Huh, it seems like I also can't sign in with GitHub on the alpha branch locally, hitting the same behaviour, so maybe that isn't it. Digging in!

**Comment by mxstbr** [comment]
Weirdly enough it only doesn't work when clicking the GitHub button on /login—when I go to `localhost:3001/auth/github` manually it works perfectly fine 🤔

**Comment by mxstbr** [comment]
Anyways that's a separate issue, this branch is now working locally. Going to look at those e2e failures!

**Comment by mxstbr** [comment]
I can replicate the e2e test failures of the public thread view locally ("Cannot read property slug of undefined"), will dig into those!

**Comment by mxstbr** [comment]
It's the `redirect-old-route` compnoent, where `thread.community.slug` is undefined for some reason. Will dig into why that broke.

**Comment by mxstbr** [comment]
Latest commit fixes some first of those broken e2e tests!

**Comment by mxstbr** [comment]
Boooom, let's get this on alpha?

**Comment by brianlovin** [comment]
Damn dude, thank you! Yes, I'll test this on alpha...might as well just merge this and #4275 into alpha right now and do an alpha cut. Will roll back either change if they're not working, or just aim for a prod cut later today

**Comment by brianlovin** [comment]
Oh, one more thing: do you think we should try to remove the `spectrum` item from localStorage for existing users?

**Comment by mxstbr** [comment]
Sounds good, was just deploying #4275 to alpha but I guess I'll let you deploy both of them then!

**Comment by mxstbr** [comment]
No, let's just leave it for now?

**Comment by brianlovin** [comment]
Cool, want to give this an approval and I can merge into alpha

**Review by mxstbr — APPROVED** [review]

**Pull request merged**
