### PR TITLE
Add configs to cypress and circleci

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

Worked with the Cypress team to get a dashboard set up with recordings so that we can have better debugging tools for random test failures :)

### CODE REVIEW

**Comment by mxstbr** [comment]
I assume you added some secret environment variable to CircleCI? If so, this won't work for anybody outside of us three—any forked Pull Request doesn't get passed the secrets, since otherwise forks could just put an `echo $SOME_VERY_BIG_SECRET` in the `circleci/config.yml` and log out all our secrets.

**Comment by brianlovin** [comment]
Yes I did :)

**Review by mxstbr — APPROVED** [review]
Great, just make sure this doesn't entirely fail on forks without the secret but still runs the tests!

**Comment by brianlovin** [comment]
Yeah, we'll see how things go with future PRs!

**Pull request merged**
