### PR TITLE
Turn off SW caching

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [x] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

By simply turning off the caching aspect of our ServiceWorker, we should fix our ServiceWorker woes while everything else will keep working perfectly fine. (specifically push notifications and SW updates) This will need a lot of testing in prod to make sure it doesn't break anything.

- [x] Test non-caching config
- [x] Remove custom `<Link>` and updating stuff since we don't actually care about updating the SW anymore

### CODE REVIEW

**Comment by brianlovin** [comment]
@mxstbr would love to ship and test this - any thoughts on testing strategies here to make sure it's working?

**Comment by mxstbr** [comment]
Should probably ship to alpha?

**Comment by brianlovin** [comment]
Ship it!

**Comment by brianlovin** [comment]
@mxstbr I'll let you throw this on alpha when you have some time to dig into it, just fyi. Just so this doesn't sit too long :)

**Comment by mxstbr** [comment]
Deploying to alpha!

**Comment by mxstbr** [comment]
This is live on alpha, seems to work fine?

**Comment by brianlovin** [comment]
Alright! I'll prep a prod cut :)

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
