### PR TITLE
Add scroll down to newest post in threads

### PR DESCRIPTION
**Pull request by sivakar12**
Issue #2830 

**Status**
- [x] WIP
- [ ] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

### CODE REVIEW

**Comment by sivakar12** [comment]
How do you want the text to be styled? Is there an existing component that can be used?

**Comment by brianlovin** [comment]
Not sure on the styling yet, but we can take a look at that for you.

After a quick look at the code, we also probably want a way for the 'scroll to bottom' indicator to re-appear if the user scrolls back up. Basically it should contextually appear if the user is >N pixels from the bottom of the messages.

**Comment by brianlovin** [comment]
And I'm not sure what N should be there - since different viewport sizes might have a different threshold where it would make sense for this to appear.

**Comment by sivakar12** [comment]
The issue said this was about getting to the bottom at the start. 
If it has to be always there, you can't just put it in the top because the thread details and action bar scroll with the page. It has to float in a corner, taking up space the whole time. 
Is that necessary? Does the user want to scroll to the bottom that often? They don't need to scroll down to send a message

**Comment by brianlovin** [comment]
I see what you're saying; I suppose a first version can just be a one-time click - we don't have an existing component that could work here for styling though. Will have a think on it though!

**Comment by sivakar12** [comment]
Can you check this out?
The style is similar to that of null messages text.
The scroll down offer shows only once. And in the case the thread is automatically (as when the user is a participent/creater or when the last message sent is by the user) the scroll down offer is not shown.
Also when the there is no need to scroll, the offer is not shown. The temporary logic now is that if scrollHeight < clientHeight + 200, don't show the message

**Comment by brianlovin** [comment]
@sivakar12 will try to take a look at this soon! Thanks!

**Comment by brianlovin** [comment]
Hey @sivakar12  - I pushed up styling fixes, but I still thing this branch needs some work. I'm hitting way too many cases where it doesn't appear when I'd expect, or flashes in briefly while a thread is still loading.

I don't have too much time to dig into this, but if you're interested in pushing through on this here's a loose checklist of what the behavior should be:

- indicator should appear if a thread loads, has messages, and does not get auto scrolled to the bottom
- indicator should not appear if more messages are loading - if you open a thread with >50 messages there is a pagination event that causes this to flash
- indicator should go away if the user manually scrolls to the bottom

There were some implementation details here that break this:
- `if (isDifferentThread)` - why do we have this? what if the first thread that loads needs the scroll indicator?

Extra notes:
- the `makeScrollDownOffer` class method is never used

**Comment by sivakar12** [comment]
I have cleaned up the code. Now the presence of the 'Scroll Down' depends only the scrolled depth. If scrollTop + clientHeight + 200 < scrollHeight it shows. The 200 is hard-coded for now.
But the offer only shows when the user starts scrolling, not at the start. (React is not allowing us to set the state in componentDidUpdate.) Is it OK the way it is or does something need to be done?

**Pull request closed without merging**
