### PR TITLE
Upgrade to latest flow

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

This needed a lot of `$FlowFixMe` and `$FlowIssue`s - some of the new flow requirements are quite cumbersome, but I also don't want to be lazy about this. Want to give this a skim @mxstbr? 

Note that in `shared/db/create-query.js:81 and :82` I had to use an `any` type otherwise all `createWriteQuery` invocations were throwing a flow error. This probably isn't ideal :P

### CODE REVIEW

**Comment by brianlovin** [comment]
One of the main things I had to `$FlowFixMe` on is a new feature where Flow freaks out if you don't properly type Array methods like `.map` or `.filter` eg https://github.com/withspectrum/spectrum/pull/4268/files#diff-c393bb57a1a5e11e817e6fe9a6e1f90dR63

**Comment by mxstbr** [comment]
> Note that in shared/db/create-query.js:81 and :82 I had to use an any type otherwise all createWriteQuery invocations were throwing a flow error. This probably isn't ideal 📦 

That is really bad since it means all our db queries are untyped :confused: I dug into this for a couple minutes but couldn't seem to fix it, Flow always complains about the rest-spread usage. I'd rather not upgrade but keep our db queries typed instead...

**Comment by brianlovin** [comment]
> I'd rather not upgrade but keep our db queries typed instead...

Can we aim for both? Can you tell if this is a Flow problem that would warrant us filing an issue for with their team? Or is our implementation just not correct yet?

**Comment by mxstbr** [comment]
This is just us not being able to use advanced Flow features 😅

**Comment by brianlovin** [comment]
@mxstbr I hear ya, but it would also be really nice to get caught up + improve the local experience so that my local flow version and our flowconfig are in sync :P

**Comment by mxstbr** [comment]
I'm not sure why your globally installed version matters? I use `yarn run flow` in all my projects which uses the version installed in the dependencies of that project, which works fine. Upgrading would still be nice, though maybe too much effort. I tried for a while and couldn't fix this.

**Pull request closed without merging**
