### PR TITLE
Run all e2e tests

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

For some reason we forgot to remove a `.only` in the e2e tests, which meant that only a single one was run.

### CODE REVIEW

**Comment by ryota-murakami** [comment]
oh, thanks @mxstbr😄

**Review by brianlovin — COMMENTED** [review]
That’s my bad 😬

**Comment by ryota-murakami** [comment]
no worry @brianlovin 😆

**Comment by mxstbr** [comment]
@brianlovin are those test failures real failures or random ones

**Comment by brianlovin** [comment]
Those look like potentially legit failures, I'll dig in

**Comment by mxstbr** [comment]
I investigated them—they were real failures, but in the test setup not the frontend itself. Last three commits should've fixed the failing tests, fingers crossed! 🤞

**Comment by mxstbr** [comment]
Fuck yes. Ran all e2e tests and they all passed in CI! 😍 Thanks @ryota-murakami for making this work!!

screen shot 2018-05-27 at 14 00 33

Admin shipping

**Pull request merged**
