### PR TITLE
Stop fetching and deprecate Thread.participants

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

This is a really expensive fields to load from the db, we load it for every thread all the time but really don't use it anymore since we removed the face piles from the cards.

This patch removes all stray usage of Thread.participants from the frontend (all the functionality is preserved with `currentUserLastSeen`), stops fetching it from the API and marks the field as deprecated.

### CODE REVIEW

**Comment by mxstbr** [comment]
Note that this is pretty much the only expensive query running on `usersThreads`, but `usersThreads` is one of the top three most read tables—no longer fetching this for every thread should help alleviate quite a bit of db load!

**Comment by mxstbr** [comment]
For some reason this broke the `graphql-depth-limit` validation rule, it's throwing errors now. 🤔 Maybe the reformatted GraphQL types?

**Comment by mxstbr** [comment]
Failing e2e test is "edit message signed in should render edit buttons on current users messages:" but the edit message button shows up locally and works perfectly fine, so probably unrelated!

**Comment by brianlovin** [comment]
> Failing e2e test is "edit message signed in should render edit buttons on current users messages:" but the edit message button shows up locally and works perfectly fine, so probably unrelated! 

Can you test this e2e spec locally to confirm it passes?

**Comment by brianlovin** [comment]
Triggering a manual re-run on that failed CI test just in case it was a fluke

**Review by brianlovin — DISMISSED** [review]
Cursory approval based on the code, but ideally we get the test suite to pass fully before merging just to be sure

**Comment by mxstbr** [comment]
Hmm strange, because the thing it's testing (editing messages) 100% works locally. Will dig in tomorrow!

**Comment by brianlovin** [comment]
> This element '<button.style__StyledTextButton-sc-1yf4mot-2.dKkisf.style__StyledSolidButton-sc-1yf4mot-1.csqDYP>' is not visible because its content is being clipped by one of its parent elements, which has a CSS property of overflow: 'hidden', 'scroll' or 'auto'

Just an overlapping element somehow that's covering the button

And failing navbar spec:

> Cannot read property 'edges' of undefined

Hm shit, that feels like a flaky test but maybe we're not guarding properly

**Comment by brianlovin** [comment]
Woo!

**Review by brianlovin — APPROVED** [review]

**Comment by mxstbr** [comment]
You da best!

**Pull request merged**
