### PR TITLE
Ensure users have emails before trying to send community approval email

### LINKED ISSUE #4693: Private community request approved queue is err'ing
```
TypeError: This library (validator.js) validates strings only
at athena/queues/private-community-request-approved.js in recipients.filter.user at line 46:21
```

Sentry: https://sentry.io/space-program/spectrum/issues/725378313/?query=is%3Aunresolved

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- athena

Should close #4693

### CODE REVIEW

**Review by mxstbr — DISMISSED** [review]
LGTM

**Comment by brianlovin** [comment]
@mxstbr I think the latest commit is slightly better approach here

**Review by mxstbr — APPROVED** [review]
Makes a lot of sense 😅 Wanna ship this together with #4691 today? `yarn run deploy all --prod` 😍

**Comment by brianlovin** [comment]
Yeah, just nervous I'm going to break the frontend again...I'll keep an eye out

**Pull request merged**
