### PR TITLE
Fix new community onboarding flow

### LINKED ISSUE #4905: New community creation flow in desktop is bad
- opens the web app post-creation
- doesn't update the sidebar communities list

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

Closes #4905 - the key fix here was the `fetchPolicy`, @mxstbr let me know if you see any issues with this

### CODE REVIEW

**Comment by brianlovin** [comment]
This failing e2e is unrelated and ridiculously flaky

**Review by mxstbr — DISMISSED** [review]
There must be a different solution to this. Changing this fetchPolicy will cause us to always do a network request for data we already have while switching between communities, which seems unnecessary.

Let me dig into this.

**Comment by mxstbr** [comment]
Fixed by using `refetchQueries` in the latest commit, want to review that and then we can ship! 👍

**Comment by brianlovin** [comment]
Ah, thanks so much for the idea there! That's much better and still fixes the problem :)

**Pull request merged**
