### PR TITLE
Remove team badge on community profile

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

When I view the ZEIT community it feels like overkill that we render the team badge 20 times in the 'team members' section list. It's too repetitive and isn't adding anything to that component. The badge is super helpful in a chat context or in a list where owners are mixed with regular members. Wdyt @mxstbr ? Other commits are small nits

### CODE REVIEW

**Review by mxstbr — COMMENTED** [review]
Let's add least render the badge next to the list title so new users know how to tell team members?

**Comment by brianlovin** [comment]
> Let's add least render the badge next to the list title so new users know how to tell team members?

Just wondering if this is necessary, too. Is the word 'team' in the badge clear enough in the conversation context? I think I understand what you're going for with building a consistent meaning for the badge, just want to make sure it's not adding unnecessary elements

**Comment by brianlovin** [comment]
Those failed e2e tests pass locally, pushing an alpha merge to kick off a new test.

**Review by mxstbr — APPROVED** [review]
I don't care that much, so let's ship it!

**Pull request merged**
