### PR TITLE
Private channel mod fixes

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)
- athena

**Release notes for users (delete if codebase-only change)**
- Fixes several permissions and notifications bugs for moderators managing private channels

This definitely needs to ship soon; I missed a few checks across the board to make sure community moderators are able to perform all the expected actions when managing channels. This also fixes notification logic for private channels as people request to join and are then approved.

### CODE REVIEW

**Comment by brianlovin** [comment]
Hold up, one more thing to fix

**Review by mxstbr — DISMISSED** [review]
LGTM, wanna do another prod cut?

**Comment by brianlovin** [comment]
@mxstbr got one more fix there - let's get this on alpha first and I'll work with the moderator who reported these problems to confirm fixes :)

**Review by mxstbr — DISMISSED** [review]

**Comment by brianlovin** [comment]
One legit test failure in there due to removing the redirect after saving community info; second test was random failure and I confirmed all things pass locally.

**Comment by brianlovin** [comment]
One random failure in that last test, and the branded login settings management fails but I can not figure out why - passes just fine locally. Even with the cypress dashboard reply + video i can't see what's going on there :(

**Pull request merged**
