### PR TITLE
returns the gradients to the text bubbles

### PR DESCRIPTION
**Pull request by superbryntendo**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**

- hyperion (frontend)

### CODE REVIEW

**Comment by mxstbr** [comment]
Have you tested this with code blocks in messages? (not inline code) That's what @brianlovin was concerned about and why he removed it in #2855

**Comment by superbryntendo** [comment]
Of course @mxstbr. I understand the reasoning behind the change, but I don't think the solution making the default experience harsher visually in order to reduce some visual noise in a much smaller percentage of messages is the right approach.

I have meetings tomorrow and I'd really like this back to normal before I demo to others.

**Comment by brianlovin** [comment]
Imo the gradient is becoming distracting as we add more formatting options to the bubbles.

**Comment by superbryntendo** [comment]
I think the code block messages should probably have a p different treatment anyway - the borders and stuff are really weird. we could probably make those flat with some nice line-number treatments too.

**Comment by mxstbr** [comment]
Wanna just tackle that in this PR right away? (apart from the line numbers which'll be hard)

**Comment by superbryntendo** [comment]
No. I want this back before I demo tomorrow please.

**Comment by superbryntendo** [comment]
We can tackle that soon. I think this is materially better in the default case and not worse in the codeblock case.

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
