### PR TITLE
Dm bugs

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

This took quite a lot of refactoring and tedious bug hunting, but I think the DM view is a bit tidier and more well-behaved now. There were certain instances where the infinite loader was accidentally triggering pagination over and over again, degrading performance on the view. I also found cases of over-aggressively POSTing mutations to update seen statuses. 

I've also written several new e2e tests for the messages view, including tests to make sure the tab badge behaves properly (hopefully!).

### CODE REVIEW

**Review by mxstbr — DISMISSED** [review]
Code LGTM overall, which specific part was triggering the bug for Timothy?

**Comment by brianlovin** [comment]
Worked on this PR all day, when in fact the *real* bug is here: https://github.com/withspectrum/spectrum/pull/4486/commits/69e93003295e79ce4d360bd2c7517ca9292e3c22

(Not worried about it though, as the rest of the PR still addresses some other pretty critical bugs, namely the DM threads list infinitely paginating and slamming the db).

So @mxstbr: https://github.com/withspectrum/spectrum/pull/4486/commits/69e93003295e79ce4d360bd2c7517ca9292e3c22 is really really frustrating. Basically what happens is that we tell our loader to get the last message of each thread, given an array of thread ids:

```js
export const __createDirectMessageSnippetLoader = createLoader(
  threads => getLastMessageOfThreads(threads),
  'threadId'
);
```

But what happens if `getLastMessageOfThreads` returns `null`? Well, it turns out that the loader can't properly parse the results. See my comment here:

```js
function indexResults(results, indexField, cacheKeyFn) {
  var indexedResults = new Map();
  results.forEach(res => {
    // if res is null at this point, the entire loader will fail
    const key =
      typeof indexField === 'function' ? indexField(res) : res[indexField];
    indexedResults.set(cacheKeyFn(key), res);
  });
  return indexedResults;
}
```

My hacky solution is simply to return a dumb object if `getLastMessage` returns null:

```js
.then(res =>
  Array.isArray(res) && res.length > 0
    ? res[0]
    : { threadId, content: { body: null } }
);
```

It seems like the root cause of this is that somehow a `directMessageThread` was created in the database, but the original message that triggered its creation was *not* persisted to the database. This is likely from our uptime issues last week, where individual queries may have failed mid-mutation.

However, given just how sensitive the `create-loaders.js` file is about null results, I'm honestly surprised we haven't run into this sooner.

Any ideas on how to make this more rigorous?

**Comment by mxstbr** [comment]
If the loader returns `null` we should just return `null`, there's no need to "fake" a response. If a record doesn't exist then it doesn't exist, no matter which record.

So the proper fix for that issue should be to make `create-loader` handle `null` records properly, rather than throwing an error by adding another conditional to not do `res[indexField]` if `res` is `null`. Going to work on that!

**Comment by mxstbr** [comment]
I can't replicate this locally. If I delete the last message in a thread, it correctly shows the previous one. If I delete all messages in a DM thread, it correctly shows "No messages yet…".

How do I replicate the original bug?

**Comment by mxstbr** [comment]
Given your description above 67572f9 should fix the issue properly by simply returning `null` if the database also returned `null`, but I can't verify without replicating and I can't seem to get into a state where this breaks—would you mind checking yourself whether this works or not?

**Comment by mxstbr** [comment]
Oh I'm a dummy I was using this branch, which already had your fix 😅 I can replicate, let's see if my fix fixes it!

**Comment by mxstbr** [comment]
I can confirm that commit 67572f9 fixes the issue!! :tada: Will ship this and do a prod cut if tests pass 🤞

**Review by mxstbr — APPROVED** [review]
Thanks so much for digging into this, people will love it! :100:

**Pull request merged**
