### PR TITLE
Fix e2e tests

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

@brianlovin we need to run resetdb both before() and beforeEach(),
because otherwise the cy.visit('/whatever') runs before the beforeEach()
so it'd 404.

### CODE REVIEW

**Comment by mxstbr** [comment]
Hmm, I made the API auto-restart on crash (by using Nodemon) yet the tests still fail 🤔 Something else must be going on here. Going to dig in and profile now.

**Comment by mxstbr** [comment]
Just merged my CircleCI refactor try from #2742 which seems to have passed on CI—if it doesn't work here I'll remove that change again.

**Comment by mxstbr** [comment]
Only a single test failed in that last run oh my god. 🤞

**Comment by mxstbr** [comment]
So close, and that one failure is an actual failure. (fixed in the last commit) Let's hope that this is it! 🤞 

screen shot 2018-04-10 at 12 54 48

**Comment by mxstbr** [comment]
Argh now they're failing again :cry: I thought for just a second I'd fixed it.

**Comment by brianlovin** [comment]
Unable to figure out the proper way to patch in a check for the existence of the testing db, but I think #2810 is probably a better place for that patch to come in. Since this PR fixes a bunch of tests and frontend code, let's ship it.

**Pull request merged**
