### PR TITLE
Serve fake JS file that hard refreshes page if old JS bundle is fetched

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [ ] Ready for review
- [x] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

This might fix our caching issues where folks app breaks after a new deploy. Gotta test on alpha though for sure!
!-- If there are UI changes please share mobile-responsive and desktop screenshots or recordings. -->

### CODE REVIEW

**Comment by mxstbr** [comment]
I could not reproduce the bug on alpha so this is now live in production with deploy https://spectrum-xnwkiyrmvy.now.sh

**Review by brianlovin — CHANGES_REQUESTED** [review]
We should not `window.alert` though - why not just reload?

**Comment by mxstbr** [comment]
I am not sure that there is no edge case where it won't infinitely reload users, so I'd rather they can opt-out of that, if that makes sense 😜 

It's also a bit jarring to use the app and just randomly get a full reload, as we know from our first updating experience (some links are full refreshes if there is an app update).

**Comment by mxstbr** [comment]
Nope.

**Pull request closed without merging**
