### PR TITLE
remove unnecessary $FlowFixMe

### PR DESCRIPTION
**Pull request by ryota-murakami**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

thanks😀

### CODE REVIEW

**Comment by ryota-murakami** [comment]
Oh, Flow doesn't enable

**Comment by ryota-murakami** [comment]
Enable Flow & fix Error.

**Comment by brianlovin** [comment]
@ryota-murakami - we should probably just take the time to properly flowtype the redux state, huh? That way we can more safely inject redux state into component props.

sidebar: At some point we could easily start chipping away at redux and probably remove it entirely in favor of two things:
1. `React.createContext()`
2. Add a `withCurrentUser` hoc to the web, same as we are doing on mobile: https://github.com/withspectrum/spectrum/blob/alpha/mobile/components/WithCurrentUser/index.js - this just abuses the apollo cache so we don't need redux :)

**Comment by brianlovin** [comment]
Also: not suggesting that you should have to do those things, just saying it's probably where we could all start moving in the near term to reduce as much unnecessary boilerplate

**Comment by ryota-murakami** [comment]
@brianlovin I see, I agree with your aspect. boilerplate doesn't productive.
But Redux was used to toasts mechanism and working fine, so I think we don't have to remove entirely Redux, just enough reduce/clean up/avoid abuse.

BTW: I like Redux but I dislike boilerplate😜 https://github.com/ryota-murakami/redux-boilerplate-less-architecture

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
