### PR TITLE
Deployment script :sparkles:

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

The script handles aliasing and clearing the cache after deploying hyperion.

**Usage**

```sh
$ yarn run deploy api        # Deploys api.alpha
$ yarn run deploy hyperion   # Deploys hyperion.alpha
$ yarn run deploy api --prod # Deploys api.spectrum.chat
$ yarn run deploy athena --prod # Deploys athena.workers.spectrum.chat
$ yarn run deploy all --prod    # Deploy all servers to prod
```

### CODE REVIEW

**Comment by mxstbr** [comment]
Ignore these @spectrum-bot errors, the scripts do not need to be flow typed and we also do need the console.logs there!

**Review by brianlovin — APPROVED** [review]
YEAAHHHH dude this is amazing. Have you tested all server deploys?

**Comment by mxstbr** [comment]
Yep hyperion tends to time out with instance verification, but other than that it works! :tada: Did an entire prod cut today!

**Comment by brianlovin** [comment]
💜💜💜💜

**Pull request merged**
