### PR TITLE
feat: use helmet

### PR DESCRIPTION
**Pull request by tuananh**
Fixes: #2775 

**Status**
- [ ] WIP
- [x] Ready for review
- [x] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)
- pluto

### CODE REVIEW

**Comment by brianlovin** [comment]
@tuananh could you add some more thoughts here on what's going on and what problem this is solving? Additionally, is there any reason this would only land on api/hyperion/pluto and not the rest of our workers?

**Comment by tuananh** [comment]
@brianlovin i saw issue #2775 was up for grab. Searching for import express only yield those sub projects depends on it. 

> We should use Helmet to protect our servers and users from some common attack vectors: https://expressjs.com/en/advanced/best-practice-security.html#use-helmet

**Comment by spartDev** [comment]
A good idea would be to create a security middleware to make `helmet` and security in general more granular.
```js
function securityMiddleware(server) {

  // Don't expose any software information to hackers.
  server.disable('x-powered-by');
  // The xssFilter middleware sets the X-XSS-Protection header to prevent
  // reflected XSS attacks.
  // @see https://helmetjs.github.io/docs/xss-filter/
  server.use(helmet.xssFilter());

  // Frameguard mitigates clickjacking attacks by setting the X-Frame-Options header.
  // @see https://helmetjs.github.io/docs/frameguard/
  server.use(helmet.frameguard('deny'));

  // Sets the X-Download-Options to prevent Internet Explorer from executing
  // downloads in your site’s context.
  // @see https://helmetjs.github.io/docs/ienoopen/
  server.use(helmet.ieNoOpen());

  // Don’t Sniff Mimetype middleware, noSniff, helps prevent browsers from trying
  // to guess (“sniff”) the MIME type, which can have security implications. It
  // does this by setting the X-Content-Type-Options header to nosniff.
  // @see https://helmetjs.github.io/docs/dont-sniff-mimetype/
  server.use(helmet.noSniff());
}
```

Also a good idea would be to use [hpp](https://github.com/analog-nico/hpp) to protect against HTTP Parameter Pollution attacks.

And what about CSP (Content Security Policy) ?

**Comment by mxstbr** [comment]
I don't think we can use helmet out of the box, as some of the protections will probably break the app. @spartDev's custom whitelist looks good to me from a glance at it, but would still need testing.

> And what about CSP (Content Security Policy) ?

I don't think we can use that as it'd require quite an intricate setup?

**Comment by spartDev** [comment]
@mxstbr Helmet have a contentSecurityPolicy module ([with good documentation](https://helmetjs.github.io/docs/csp/)) and is easy to setup:
```js
const cspConfig = {
  directives: {
    defaultSrc: ["'self'"],

    // Allow scripts hosted from our application.
    scriptSrc: ["'self'"]

    styleSrc: ["'self'", "'unsafe-inline'", "blob:"],
    imgSrc: ["'self'", "data:"],
    fontSrc: ["'self'", "data:"],

    childSrc: ["'self'"]
  }
};
```

The only tricky part (but not so difficult) is allowing inline script (data store rehydration by redux for example), 
you have to dynamically generate nonces to allow inline`<script>` be safely evaluate.

```js 
// Attach a unique "nonce" to every response. This allows use to declare
// inline scripts as being safe for execution against our content security policy.
// @see https://helmetjs.github.io/docs/csp/
server.use((request, response, next) => {
 response.locals.nonce = uuid();
  next();
 });

...

const cspConfig = {
  directives: {
    scriptSrc: [
      ...

      // Note: We will execution of any inline scripts that have the following
      // nonce identifier attached to them.
      // This is useful for guarding your application whilst allowing an inline
      // script to do data store rehydration (redux/mobx/apollo) for example.
      // @see https://helmetjs.github.io/docs/csp/
      (request, response) => `'nonce-${response.locals.nonce}'`,

      // Required for eval-source-maps (devtool in webpack)
      process.env.NODE_ENV === 'development' ? "'unsafe-eval'" : '',
    ].filter(value => value !== ''),
};
```

then in you render:
```js
<script nonce=${res.locals.nonce}>window.__INITIAL_STATE__=${serialize(store.getState(), {
    isJSON: true,
  })}}</script>
```

if @tuananh need some help I will be happy to help him.

**Comment by mxstbr** [comment]
We can also set `global.__webpack_nonce__` to the nonce, then styled-components automatically picks it up and adds it to all `style` tags. If you want to tackle CSP that'd be awesome, I'd love to have it!

**Comment by tuananh** [comment]
lemme dig those and maybe submit another pr.

**Pull request closed without merging**
