### PR TITLE
shows a cheat sheet of supported markdown features

### LINKED ISSUE #2864: Add markdown hints to chat input
As soon as you type anything into Slack's chat input it shows a cheat sheet of supported markdown features:

screen shot 2018-04-15 at 14 14 39

Now that our chat input also supports some markdown (the ~same subset except for quotes) we should also add a similar cheat sheet so folks are aware of that!

### PR DESCRIPTION
**Pull request by spartDev**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

**Release notes for users (delete if codebase-only change)**
- shows a cheat sheet of supported markdown features when typing a message

close #2864

### CODE REVIEW

**Comment by brianlovin** [comment]
@spartDev any chance you could share before/after screenshots of this change on mobile + desktop?

**Comment by spartDev** [comment]
Of course !

before:
screen shot 2018-04-16 at 00 44 59

after: 
screen shot 2018-04-16 at 00 45 24

I did not touch the mobile

**Comment by brianlovin** [comment]
Re mobile - I misspoke, I just meant responsive view of the app :) Also I don't think we support `~strike~` yet :)

**Comment by spartDev** [comment]
Before: 
screen shot 2018-04-16 at 01 08 25

After: 
screen shot 2018-04-16 at 01 09 08

I removed the `~strike~`

**Comment by brianlovin** [comment]
Nice! Sorry I'm just noticing more things - I think we use double asterisks for bold and single for italics. Same with underscores - double is bold, single is italic.

**Comment by spartDev** [comment]
done !
screen shot 2018-04-16 at 01 26 42

it's not a bit confusing to have multiple way to write **bold** and _Italics_ ?

**Comment by brianlovin** [comment]
Agree - let's just choose one syntax and stick with it. How about asterisks? And for people who know md syntax we'll of course still support underscore.

**Comment by spartDev** [comment]
Agree with asterisks ! ;-)

**Comment by spartDev** [comment]
By the way I wanted to write a cypress test but I did not manage to launch it locally. Any advice ?

**Comment by brianlovin** [comment]
Did you run into any errors running cypress? Happy to help debug - just shoot over where things are getting stuck

**Comment by spartDev** [comment]
when I launch test i have this error:
```bash
CypressError: cy.exec('node -e "const teardown = require('./shared/testing/teardown.js')().then(() => process.exit())"') timed out after waiting 60000ms.`
```
`shared/testing/teardown.js` does not exist

**Comment by brianlovin** [comment]
Just to double check - that file does exist locally for you in the repo right? And cypress is just failing to find it?

**Comment by spartDev** [comment]
the file does not exist locally

**Comment by spartDev** [comment]
sorry the file exist and cypress is just failing to find it

**Comment by brianlovin** [comment]
Hm, that's not ideal. Are you running `yarn run cypress:open` from the root of the project?

**Comment by spartDev** [comment]
after running `yarn run cypress:open` here are my logs:
```bash
GET /__/ 200 29.854 ms - -
GET /__cypress/runner/cypress_runner.css 200 51.133 ms - -
GET /__cypress/runner/cypress_runner.js 200 342.989 ms - -
GET /__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.7.0 200 2.451 ms - 77160
GET /__cypress/iframes/integration/thread/chat_input_spec.js 200 8.295 ms - 747
GET /__cypress/tests?p=cypress/support/index.js-730 200 1533.939 ms - -
GET /__cypress/tests?p=cypress/integration/thread/chat_input_spec.js-310 200 1986.878 ms - -
HEAD / 500 17.730 ms - -
HEAD / 500 16.777 ms - -
HEAD / 500 24.270 ms - -
```

what about `HEAD / 500 24.270 ms - -` ?

**Comment by brianlovin** [comment]
I have similar logs when my test starts running:

```sh
$ cypress open
GET /__/ 200 29.798 ms - -
GET /__cypress/runner/cypress_runner.css 200 43.456 ms - -
GET /__cypress/runner/cypress_runner.js 200 253.295 ms - -
GET /__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.7.0 200 2.157 ms - 77160
GET /__cypress/iframes/integration/user/delete_user_spec.js 200 9.338 ms - 745
GET /sw.js 200 37.349 ms - -
GET /__cypress/tests?p=cypress/support/index.js-878 200 1378.183 ms - -
GET /__cypress/tests?p=cypress/integration/user/delete_user_spec.js-242 200 1742.267 ms - -
HEAD / 500 45.164 ms - -
HEAD / 500 50.874 ms - -
HEAD / 500 56.319 ms - -
GET /users/mxstbr/settings 200 2.899 ms - -
GET /static/js/bootstrap.js 200 24.474 ms - -
GET /analytics.js 503 0.925 ms - -
GET /static/js/bundle.js 200 391.093 ms - -
GET /sockjs-node/info?t=1523836999130 200 7.130 ms - -
GET /static/js/CommunityView.chunk.js 200 32.499 ms - -
GET /static/js/UserSettings.chunk.js 200 11.721 ms - -
GET /users/mxstbr/undefined 200 3.868 ms - -
```

Can you commit your test so we can look at the code here?

**Comment by spartDev** [comment]
@brianlovin test committed

**Review by mxstbr — DISMISSED** [review]
I cleaned up the integration test, and also got rid of our `toPlainText` usage since that is actually really really slow.

This LGTM code-wise, I'll defer to @brianlovin for a last UX approval and then we'll ship this! Thank you so much for your contribution 💜

**Comment by brianlovin** [comment]
I made some small styling changes, including a decision to hide this on mobile as markdown probably sees less usage there, and on mobile we'd want to optimize for content area. Hope that works!

**Review by brianlovin — APPROVED** [review]

**Review by brianlovin — APPROVED** [review]

**Comment by brianlovin** [comment]
Ah this needs the latest alpha to avoid that danger failure. Afaik this is good and I'm going to admin merge for now :)

**Comment by brianlovin** [comment]
Thanks so much @spartDev! I'll get this up on alpha.spectrum.chat today :)

**Pull request merged**
