### PR TITLE
Fix the thread flyout behavior

### PR DESCRIPTION
**Pull request by gdad-s-river**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

**Release notes for users (delete if codebase-only change)**

1. (fix for #2917) — Wrapped Flyout and Thread Settings Icon Button with React Popper to improve [and handle well] cutting out of dropdown due to scrollable container (react popper automatically switches its position from top ↔️ bottom); removed unnecessary styles to complement this change.

2. (fix for https://github.com/withspectrum/spectrum/issues/2917#issuecomment-382850059) — Wrapped Flyout with OutsideClickHandler to handle click outside of it (to handle its closing), instead of setting a transparent div over the whole page to handle closing of the dropdown.

[Gif](https://firebasestorage.googleapis.com/v0/b/people-of-nith-eb630.appspot.com/o/spectrumbugfix.gif?alt=media&token=c2cc1116-d0b9-48e8-8ab7-5f411a008c42) of improved behavior
---
Small [issue unrelated] typo fix
- Typo correction (Uppercase to Lowercase) of package name in package.json

### CODE REVIEW

**Comment by gdad-s-river** [comment]
@brianlovin. Hello! I could use some help to understand what is happening here, namely why ci tests are failing, and the 'expected' awaiting status.

**Comment by brianlovin** [comment]
@gdad-s-river the ci failing should have been fixed with https://github.com/withspectrum/spectrum/pull/2930 - any chance you could pull the latest alpha code and re push to this PR to trigger a new build?

**Comment by gdad-s-river** [comment]
@brianlovin I've a small question. Using `outSideClickHandler` does one think differently — 

One hits the delete thread option ▶️ modal window opens ▶️ user hits cancel, then since it's outside of the Flyout, the flytout hides (which is not the case when a full screen extra div is used to handle outsideclick). Even though there are not tests regarding this, i wanted to ask what to do about this behavior.

**Comment by brianlovin** [comment]
@gdad-s-river that's just fine for it to close behind the modal if a person selects 'delete' in the dropdown :)

**Comment by brianlovin** [comment]
Looking through the CI failures now, it looks like 7 of them are related to the action bar, which makes me think they might be failing because of the changes here. If you do `yarn run cypress:open` and run the `action_bar_spec.js` can you see if those are failing on your end?

**Comment by brianlovin** [comment]
@gdad-s-river I pulled your branch and made a couple small changes to fix the tests and the overall behavior of the flyout (we don't want it to close immediately when the user clicks on something - we have loading states and confirmation states for things like locking the thread, which are useful bits of feedback to users). Anyways, everything is now passing for me locally, we'll see how things hold up here in CI!

**Comment by brianlovin** [comment]
All tests pass! I'm going to get this on alpha.spectrum.chat right now :)

**Comment by gdad-s-river** [comment]
@brianlovin oops, I have no idea how I missed your comment notifications 😅. I had fixed the CI issues 😁. But thank you for doing it yourself! This was my first experience seeing what end to end tests look like, and how they could be so beneficial to enforce required behaviour. I learnt a lot. Thanks to @FezVrasta for helping me out with finding an issue and generously putting time to help me figure things out when I was struggling with React Popper.

Working on this issue, I made a small video explaining a small component [OutsideClicker](https://www.youtube.com/watch?v=45LByCUTl80), which sparked this [twitter thread](https://twitter.com/gdad_s_river/status/987725719215144960) which ultimately (again thanks to another generous person Timur), after numerous twitter DMs led to this [codesandbox](https://codesandbox.io/s/72v0xjxo5j). 

I look forward to contributing more, because spectrum.chat is awesome!

**Comment by brianlovin** [comment]
💜💜

Thanks @gdad-s-river - this is live by the way!

**Pull request merged**
