### PR TITLE
Move thread embeds to automatic embed system

### LINKED ISSUE #4802: Add thread link embeds to thread bodies
We have added embeds for thread links in messages in #4669. We should add the same capability to threads themselves, if a thread is linked from another thread it should show a nice embed!

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

**Related issues (delete if you don't know of any)**
Closes #4802

**Todo**

- [x] Parse all thread URLs in `add-embeds-to-draft-js`
- [x] Figure out data structure difference for internal embeds (threads) vs external embeds (youtube etc)
- [x] Render internal embeds on the frontend

### CODE REVIEW

**Comment by mxstbr** [comment]
@brianlovin the latest commit moves all thread embeds to the automatic embed system (i.e. they now happen at write-time, and we could add functionality to remove them in the future). This also means they are now rendered right below the paragraph with the link, just like the external embeds, and also work for thread bodies.

Unfortunately, the styling got totally messed up and I am not sure how as I did not touch that code at all:

screenshot 2019-03-07 at 11 59 56

Any ideas what could be causing that?

**Comment by brianlovin** [comment]
It broke because the attachments now get wrapped in the `.markdown` class:

screenshot 2019-03-07 08 30 55

So our correct styles are getting overridden. Is there a way to keep the attachments outside of that markdown container? Otherwise we'll have to battle this for all future attachment styles.

**Comment by brianlovin** [comment]
Although...now that I type that I'm not sure how to pull this off except to just...get a higher specificity on the attachment. Because if you have a thread that contains these attachments, it'd be really hard to not wrap those specific things in `.markdown`...

**Comment by mxstbr** [comment]
Yeah there is no way to render them outside the markdown class. Can we disable the markdown styles manually for the attachment? Mind digging into that?

**Comment by brianlovin** [comment]
> Can we disable the markdown styles manually for the attachment? Mind digging into that?

All I can think of is to add a higher specificity to attachments somehow, by wrapping them in a classname or something. Does this sound right to you?

**Comment by brianlovin** [comment]
Hm that won't work...will have to think on this.

**Comment by mxstbr** [comment]
I think we just have to manually reset the styles applied by `.markdown`, right?

**Comment by brianlovin** [comment]
Yeah, which I guess isn't a *terrible* idea if we want to have an attachments style guide anyways...

**Comment by brianlovin** [comment]
Hm, this kind of sucks. We will have to re-implement everything in attachments from scratch. We can't just pull in other components from the apps otherwise there's a chance anything that `.markdown` does will mess it up...

**Comment by brianlovin** [comment]
@mxstbr want to pull that commit and test it out? Honestly this implementation is a bit rough, and I'd rather revisit this hacky css later since we have higher priorities. If these thread attachments feel okay, let's roll forward and iterate here in a followup?

**Comment by mxstbr** [comment]
Looks good to me, I am fine with the hack! 👍  Cleaning up unit tests...

**Comment by mxstbr** [comment]
Unit test fixed, so this should be ready for another review!

**Comment by mxstbr** [comment]
This is ready to go @brianlovin!!

**Comment by brianlovin** [comment]
This is amazing! I was going through and testing the different regexes and it looks like the figma embeds are breaking:

screenshot 2019-03-08 09 40 06

We should somehow catch errors like this and prevent rendering an embed, if possible :/

**Comment by brianlovin** [comment]
Last nit, discussed offline, is that sending messages which contain an external embed doesn't properly trigger the `forceScrollToBottom` or `contextualScrollToBottom` so it can sometimes feel like your message disappeared, even though it's just hidden behind the chat input

**Comment by mxstbr** [comment]
> I was going through and testing the different regexes and it looks like the figma embeds are breaking:

I think Figma disallowes embedding their pages on URLs that don't have `https://` in front of them as far as I can tell? The error is shown by the iframed Figma embed page. /cc @dfield 

I fixed the height thing in the last commit, can you check whether that works for you?

**Comment by brianlovin** [comment]
> I think Figma disallowes embedding their pages on URLs that don't have https:// in front of them as far as I can tell?

Ah, that makes sense. So previewing on localhost won't work. Good to know!

**Comment by brianlovin** [comment]
This didn't work for me locally @mxstbr - for testing I just paste in a youtube link like https://www.youtube.com/watch?v=nKNAZr0QJzs and send the message, and no scrolling happens. Fwiw I think we will have some better solutions to message scrolling in #4798, so maybe this is an edge case we can live with for a little while?

**Comment by M3kH** [comment]
Hi @brianlovin and @mxstbr I think I can help solving the Figma issue by running the project with self signed certificate and traefik.
I already start some work on that direction: https://github.com/withspectrum/spectrum/pull/4846 
That allows to run `http://spectrum.localhost` and should be relative simple add a certificate for it.

**Comment by brianlovin** [comment]
> That allows to run http://spectrum.localhost and should be relative simple add a certificate for it.

That's awesome! Looking forward to learning more there.

**Comment by mxstbr** [comment]
Hmm damn, but the embed at least renders at the right size from the get-go... 😅 

I think the way to fix that would be to check for a message with a type of `optimistic` to be replaced/removed and calling `contextualScrollToBottom` does that sound sensible? Let's definitely fix that before shipping this because it's quite a bad experience.

**Comment by brianlovin** [comment]
> Let's definitely fix that before shipping this because it's quite a bad experience.

Sounds good, let me know when it's ready for another look :)

**Comment by mxstbr** [comment]
Turns out scrolling to bottom contextually was generally broken. Fixed in 900b78f, then tried fixing the embed thing in f2e9338 but that didn't work 😕 

At least it scrolls to bottom again, but the embed is still hidden behind the chat input annoyingly.

**Comment by mxstbr** [comment]
I fixed the scrolling :tada: Turns out the bug was that the embeds are higher than the allowed distance from the bottom for `contextualScrollToBottom` to scroll you to the bottom.

I fixed that by force scrolling you to the bottom if you send a message yourself, no matter where you are—which is the much nicer behaviour anyway:

Kapture 2019-03-11 at 9 41 55

Note how you see the embed after sending the message 😍😍😍

**Comment by brianlovin** [comment]
> I fixed that by force scrolling you to the bottom if you send a message yourself, no matter where you are—which is the much nicer behaviour anyway:

This is the correct behavior; I'm surprised it wasn't working that way in the first place. Good call! I think that functionality was added to #4798 as well

**Review by brianlovin — APPROVED** [review]
Works beautifully!

**Pull request merged**
