### PR TITLE
Clean up pending and blocked users styling and layout

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

**Release notes for users (delete if codebase-only change)**
- Fixes an issue @uberbryn and I discussed last night with the granular user profile where having many actions really messes up the layout; I've moved those actions to a dropdown for now, similar to the community members role management dropdown.

### CODE REVIEW

**Comment by brianlovin** [comment]
Talked to @uberbryn about this offline last night @mxstbr - he agreed with this short term fix to move to dropdowns, and he's mostly offline for the next 2 days in meetings so don't think he'll be able to review this :)

**Review by mxstbr — APPROVED** [review]
Okay then

**Comment by superbryntendo** [comment]
pulling rn 🙃

**Comment by brianlovin** [comment]
I stand corrected :P

**Review by superbryntendo — APPROVED** [review]

**Pull request merged**
