### PR TITLE
Implement fix for profile dropdown bug

### PR DESCRIPTION
**Pull request by rfbotto**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge**
- hyperion (frontend)

**Related issues**

Closes https://github.com/withspectrum/spectrum/issues/4035

**Recording**

kapture 2018-10-12 at 21 54 25

### CODE REVIEW

**Comment by brianlovin** [comment]
Hey @rfbotto - thanks for opening this PR! I'm curious why the dropdown itself has changed? Would it be possible to just keep the dropdown the same and use this PR to fix the broken alignment on the splash pages?

**Review by brianlovin — APPROVED** [review]

**Comment by brianlovin** [comment]
I'm dumb and didn't realize this is the current behavior. I will look into reverting the logged out avatar to show the normal dropdown :)

**Comment by rfbotto** [comment]
@brianlovin Yeah, in the beggining i also tought the same about being some recent change that broke the behaviour of the dropdown, but after some more digging around, came to the same conclusion as you and thats why i changed the placement :D

**Comment by brianlovin** [comment]
Really appreciate the fix regardless!

**Pull request merged**
