### PR TITLE
Dont log server memory to datadog in dev mode

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

Without this we log memory usage of locally running worker servers.

### CODE REVIEW

**Comment by mxstbr** [comment]
`shared/stasd` does not do anything in dev, only log to the console—else we would be logging all the things in development!

**Comment by brianlovin** [comment]
This change stopped the memory debug log when running hermes and athena locally, so if this isn't the fix could you please open the correct fix so that we can run worker servers locally without a zillion consoles?

**Comment by mxstbr** [comment]
Ohh sorry, I thought you meant you wanted to stop the logging to DataDog, I misunderstood the purpose of this PR!

The right fix is to disable statsd logging entirely by adding `-shared:middlewares:statsd` in the `dev:<workers>` scripts, like we do in the `dev:api` script.

Sorry I totally misunderstood :pray:

**Comment by brianlovin** [comment]
`"dev:api": "cross-env FILE_STORAGE=local cross-env NODE_PATH=./ cross-env NODE_ENV=development cross-env DEBUG=build*,api*,shared:rethinkdb:db-query-cache,-api:resolvers cross-env DIR=api backpack"`

I'm not seeing any reference to `statsd` or middlewares. Am I missing something?

**Pull request closed without merging**
