### PR TITLE
Make mobile app run on deviceagain

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [x] WIP
- [ ] Ready for review
- [x] Needs testing

This is still WIP.

### CODE REVIEW

**Comment by homanp** [comment]
@mxstbr I will test this fix today and get back to you ASAP.

**Comment by homanp** [comment]
@mxstbr getting `React Native version mismatch` error. JavaScript version 0.52.0, Native Version: 0.54.2. There is a mismatch in the package.json somewhere.

**Comment by homanp** [comment]
`Warning: Expo version in package.json does not match sdkVersion in manifest.
Warning: Installed version 1.0.0-beta.27 of 'react-navigation' does not satisfy required version ^1.5.8

If there is an issue running your project, please run `npm install` in /Users/ismailp/Projects/spectrum/mobile/ and restart.`

**Comment by mxstbr** [comment]
Run `yarn` in the `mobile/` directory, I think I upgraded some dependencies!

**Comment by homanp** [comment]
@mxstbr I tested the branch and still get redirected to localhost from Google OAuth when running on device. I guess that's because of this line https://github.com/withspectrum/spectrum/blob/alpha/mobile/components/Login/index.js#L11

**Comment by mxstbr** [comment]
Good catch, that last commit might fix that?

**Comment by homanp** [comment]
@mxstbr OK, so now I getting `400 Invalid request`. `device_id` and `device_name` are required for private IP.

**Comment by mxstbr** [comment]
> device_id and device_name are required for private IP.

Required by whom and where?

**Comment by homanp** [comment]
Sorry, that’s the error message google throws. So required by Google OAuth

**Comment by mxstbr** [comment]
Hmm that doesn't sound like something we can fix at the minute. What about Twitter/Facebook auth?

**Comment by homanp** [comment]
Facebook throws `Invalid App ID` error and Twitter seems to work but there seems to be another bug that makes the Expo app rebundle/reload every second after login. 

screen shot 2018-04-19 at 12 01 57

**Pull request merged**
