### PR TITLE
Fix integration tests and refactor CI to properly wait for servers to be started

### LINKED ISSUE #2828: Dont sleep when starting servers prior to running e2e tests in CircleCI
**The Problem**

This line right here is unnecessary: https://github.com/withspectrum/spectrum/blob/alpha/.circleci/config.yml#L110

Effectively even if your servers are ready before 60 seconds, it will wait until at least that long. If for some reason they did take **longer** than 60 seconds, Cypress will insta-fail.

**The Solution**

Use an NPM module like this: https://github.com/jeffbski/wait-on

That will allow you to wait on the servers you expect to boot and the moment they're accessible it will move on. Something like this...

```yml
- run: *start-api
- run: *start-web
- run: wait-on http://localhost:3000
- run: wait-on http://the-other-thing
- run:
    name: Run Unit Tests
    command: yarn run test:ci
```

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [x] Needs testing

Resolves #2828

> Note: This is based on #2838, so until that is merged you'll see those changes in the diff too

### CODE REVIEW

**Comment by mxstbr** [comment]
Waiting for rethinkdb doesn't work yet, will figure out why!

**Comment by mxstbr** [comment]
This works as expected! I'm replacing #2838 with this PR.

**Comment by mxstbr** [comment]
Everything passed!!! :tada: :tada: :tada:

I'm admin-shipping this before it goes out of date.

**Comment by brianlovin** [comment]
YAY!!! 🎉🎉🎉

**Pull request merged**
