### PR TITLE
Run now rm --safe after deploys

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

### CODE REVIEW

**Comment by mxstbr** [comment]
(ignore peril errors)

**Review by brianlovin — COMMENTED** [review]
Unfortunately this won't work for every server. Notice here https://zeit.co/teams/space-program/projects that we have:

- build-api
- build-vulcan
- build-mercury
- build-hermes
- build-chronos

But then we have:

- analytics
- athena
- api

We need to figure out why analytics and athena in particular are missing the `build-` prefix

**Comment by mxstbr** [comment]
Great catch, will investigate tomorrow!

**Comment by mxstbr** [comment]
@brianlovin it was because we had a `name` specified in those package.jsons. I have removed those names, so now they should be set to the folder name—i.e. `build-athena` and `build-analytics`!

I do not know what that stray `api` deploy is, it is actually `build-api` in the dashboard as far as I can tell.

This should be ready 👍

**Comment by brianlovin** [comment]
Ah, great catch!

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
