### PR TITLE
Fix nested modals

### LINKED ISSUE #4792: Prevent infinite nesting of modal routes
If you open the watercooler thread in the thread modal, then click on a thread attachment, it starts to break our routing and overlays content on top of itself. We should prevent this. I think there's a relatively straightforward way to do this. In our `routes.js` file we should indicate that the view is being shown in a modal:

```js
{isModal && (
  <Route
    path="/new/thread"
    render={props => <ComposerFallback {...props} isModal={true} />}
  />
)}
```

And then when we construct the links further down the tree we get that prop and use it to set the modal state:

```
to={{
  pathname: 'foo',
  search: qs.stringify({ bar: 'biz' }),
  state: { isModal: !this.props.isModal })
}}
```

Or something like that...

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

**Related issues (delete if you don't know of any)**
Closes #4792

### CODE REVIEW

**Review by brianlovin — COMMENTED** [review]
I've never used `history.listen` before - do we need to remove a listener during `unmount`? Otherwise this seems to work, it's just admittedly a tiny bit janky to watch the url bar "rewind" itself multiple steps :P

**Comment by mxstbr** [comment]
Just had a thought: what if we cached the last non-modal location (just like we cache the previous location), and then passed that state to the `Modal`? Then the modal could simply go back to that cached location, and we could avoid the unwinding?!?!

**Comment by brianlovin** [comment]
Seems like that could work!

**Comment by mxstbr** [comment]
Well that was an easy fix, this totally works perfectly, no more unwinding!! 👍  This is ready to go

**Review by brianlovin — APPROVED** [review]
Love it!

**Pull request merged**
