### PR TITLE
Use cypress retries

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

### CODE REVIEW

**Review by mxstbr — APPROVED** [review]

**Comment by brianlovin** [comment]
Gonna merge, everything passed, but peril keeps hanging. Who can we ask about that @mxstbr ?

**Comment by mxstbr** [comment]
@orta although I have not touched our Peril setup in... half a year or something like that. I cannot see anything suspicious in the Heroku logs though 🤔

**Comment by orta** [comment]
I don't see anything, did it rm the message?

**Comment by brianlovin** [comment]
screenshot 2019-03-04 10 55 16

@orta basically we've been encountering ^^ this stuck forever on all of our PRs

**Comment by orta** [comment]
Hrm weird, I wonder where that comes from - Peril/Danger never send an ack to indicate that it could report something (just red/green when appropriate) 

Perhaps there's an aspect of how GitHub apps work that I don't get

**Comment by brianlovin** [comment]
You can see it live here @orta https://github.com/withspectrum/spectrum/pull/4612

**Comment by orta** [comment]
Interesting, is it possible Peril is crashing? I don't see anything in my version that could be disabling it on the artsy instance, but we don't see that

**Pull request merged**
