### PR TITLE
Remove use of Google+ APIs

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api

Google is deprecating the Google+ APIs in March, but said that we should expect degradations in service starting in January. I was worried this would be a more involved migration process from Google+ auth to the generic "Google Sign-in" product - turns out, it just requires a change in scopes! Tested locally for creating a new user with Google signin and authenticating with an existing user via Google.

### CODE REVIEW

**Comment by ovflowd** [comment]
Yeah Google+ APIs are being deprecated but only some of the scopes actually will be removed, the whole endpoints and Google Developer Console thing will remain the same 😄

**Comment by brianlovin** [comment]
@ovflowd true! We are using scopes that are being deprecated though, specifically the `plus.profile` scope :)

**Comment by ovflowd** [comment]
Cool! So that's easy to workaround. ✨

**Review by superbryntendo — APPROVED** [review]

**Review by mxstbr — APPROVED** [review]
Coolio!

**Pull request merged**
