### PR TITLE
Fix CD once and for all

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

Hopefully :sweat_smile:

### CODE REVIEW

**Comment by mxstbr** [comment]
This works beautifully! 😍😍😍 @siddharthkp you're a genius

**Comment by siddharthkp** [comment]
I'm glad it's working! ❤️

Let me know if it behaves in the coming weeks, we run into this same issue quite frequently: https://twitter.com/siddharthkp/status/980805543613816832

**Comment by mxstbr** [comment]
We don't use `serve` so we'll probably not run into that :wink:

**Comment by siddharthkp** [comment]
I wonder if it's a problem with `serve` though, I guess we'll find out 😄

**Pull request merged**
