### PR TITLE
Add watercooler to community settings

### LINKED ISSUE #4799: Add button to enable the watercooler
We need to add a button to the community settings that creates a watercooler thread for that community.

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

**Related issues (delete if you don't know of any)**
Closes #4799

**Todo**

- [x] Add `enableCommunityWatercooler` mutation to backend
- [x] Add `disableCommunityWatercooler` mutation to backend
- [x] Add card to community settings with "Enable" button
- [x] Make it possible to disable the watercooler from the frontend
- [x] Make sure toggling the watercooler on and off does not create more than one (will probably require a new index on the thread table)

### CODE REVIEW

**Comment by brianlovin** [comment]
> Make sure toggling the watercooler on and off does not create more than one (will probably require a new index on the thread table)

I wouldn't mind if this is a bit slower if it means we don't have to add another index to the threads table...that table already has a lot of indexes. Why not just a `getAll` by communityId and then filter for `{ watercooler: true }` ? - at most you'd be filtering on a few hundred or a thousand records, right?

**Comment by mxstbr** [comment]
> Why not just a getAll by communityId and then filter for { watercooler: true } ? - at most you'd be filtering on a few hundred or a thousand records, right?

That is much more database intensive than just adding another index 😅 The only tradeoff of using an index is that it uses up more storage, but we are not even close to strapped for hard drive disk space at all, so it should be fine to add another one.

**Comment by brianlovin** [comment]
> The only tradeoff of using an index is that it uses up more storage, but we are not even close to strapped for hard drive disk space at all, so it should be fine to add another one.

Fair, but it does impact writes to that table the more we add there. Although we're probably still small enough that this doesn't matter right now.

**Comment by mxstbr** [comment]
That's fair, but I think given how high our percentage of reads vs. writes is adding an index is a worthy tradeoff in most cases. I have added a `communityIdAndWatercooler` index to the threads table and handled re-enabling watercoolers in the latest commits, last thing here is the disable mutation and then this should be good for a first review 👍

**Comment by mxstbr** [comment]
@brianlovin this is ready for a review! :tada:

**Comment by brianlovin** [comment]
Awesome! @mxstbr can you poke at that e2e failure, and then I'll test :D

**Comment by mxstbr** [comment]
Done, this is ready for a test & review! 👍

**Comment by brianlovin** [comment]
@mxstbr I pushed some tweaks, the biggest of which is I don't auto-redirect when enabled. This was super jarring for me. Instead, let's just show a button so they can open it if they want, otherwise they can keep editing other settings.

**Comment by mxstbr** [comment]
Nice experience polish

**Pull request merged**
