### PR TITLE
Bug basheroo

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

- https://github.com/withspectrum/spectrum/pull/3308/commits/fc63099bd0b1c3fdc16589809f42e52109cc6414 and https://github.com/withspectrum/spectrum/pull/3308/commits/6e590b5e8960302d8d641021c9921a26e4b5c3ba fix https://sentry.io/space-program/spectrum/issues/576355761/?environment=production
- https://github.com/withspectrum/spectrum/pull/3308/commits/287e64301d0c4035469c999946e12f101dbb228d reference #3305 
-  https://github.com/withspectrum/spectrum/pull/3308/commits/94890c2796b5b603878d2801a6c3e9f135c96b58 closes https://sentry.io/space-program/spectrum/issues/574631951/
- https://github.com/withspectrum/spectrum/pull/3308/commits/04827a95bb6924c0b7ad1f6f8c297c083a4f8e55 closes https://sentry.io/space-program/spectrum/issues/570545751/?query=is:unresolved
- https://github.com/withspectrum/spectrum/pull/3308/commits/5451c116efb129b1aee198026a200de69259076a closes https://sentry.io/space-program/spectrum/issues/568523170/?query=is:unresolved
- https://github.com/withspectrum/spectrum/pull/3308/commits/b7ef270632a86a3a96b7387a7cb23d02e404034c closes https://sentry.io/space-program/spectrum/issues/577452414/?query=is:unresolved
- https://github.com/withspectrum/spectrum/pull/3308/commits/44b1b11adf2847097635d66960ff7d0d49165036 may be a fairly significant update https://sentry.io/space-program/spectrum/issues/493442123/?query=is:unresolved + a bunch of other errors were being triggered by apollo cache not properly handling variables updating as lists were paginated. A fix was shipped 14 days ago https://github.com/apollographql/apollo-client/issues/2499
- https://github.com/withspectrum/spectrum/pull/3308/commits/d023ff2739535319d7535d6210e67dc5a93abfe2 should fix https://sentry.io/space-program/spectrum/issues/290995546/?query=is:unresolved - hopefully. This is very hard to debug locally.

### CODE REVIEW

**Comment by mxstbr** [comment]
287e643 won't close #3305—the code you wrote will only ever apply in development. (`module.hot` is not a thing in prod since hot reloading isn't either) The issue is that we're re-creating the store somewhere, meaning we call `createStore` twice and we gotta get rid of that somehow. Will see if I can find the root cause!

**Comment by mxstbr** [comment]
Also, e2e are broken

**Review by mxstbr — APPROVED** [review]
Shipping this anyway but leaving #3305 open

**Comment by brianlovin** [comment]
It fixed #3305 for me locally, so let me know if you're seeing something different on your end. Hot reloading is for dev only, of course - I don't expect it to apply in production, why would I?

**Comment by mxstbr** [comment]
Oh I thought that happened in production, my bad! That's totally fine then 👌

**Comment by brianlovin** [comment]
Yip! Just a local hotreloading issue - sorry that wasn't super clear :)

**Pull request merged**
