### PR TITLE
Prompt users to confirm they want to dismiss the composer when they press `esc`

### LINKED ISSUE #4744: Drafts are still persisted to the composer after a thread is published
After people publish a thread, the draft is still persisted to the composer. Will likely be fixed with #4612

### PR DESCRIPTION
**Pull request by nainarazz**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

PR for Issue #4180 

confirmation-modal

Closes #4744

### CODE REVIEW

**Comment by brianlovin** [comment]
Let's change the copy in the modal to:
- title: "Discard Draft"
- body: "Are you sure you want to discard this draft?"
- secondary action: "Cancel"
- primary action: "Discard" as a red button

**Comment by nainarazz** [comment]
Here is how the modal looks like after the changes:
red buton

**Comment by nainarazz** [comment]
I have a question. When we click the discard button, aren't we suppose to also clear the composer? Right now text is still persisted in the local storage, so even we discard, the text is still retrieved when clicking on new conversation.

**Comment by brianlovin** [comment]
- Can we change the `gradientTheme` to warn? We don't use the `ios` colors anywhere else :)
- Cancel should be gray, and have the `warn` tint on hover
- Re: preserving the draft anyways in localstorage - great question. Perhaps we preserve the localstorage syncing as the user is typing, but explicitly clear it when the user discards the draft so the next time they open the composer they start fresh. Sound good @nainarazz ?

**Comment by nainarazz** [comment]
> * Re: preserving the draft anyways in localstorage - great question. Perhaps we preserve the localstorage syncing as the user is typing, but explicitly clear it when the user discards the draft so the next time they open the composer they start fresh. Sound good @nainarazz ?

sounds good

**Comment by brianlovin** [comment]
@nainarazz will take a look at those changes once tests pass! Looks like maybe just some flow stuff is breaking, although I'm not sure if these changes also break any e2e tests. You should be able to see the circleci output if you click the `test_web` details link above :)

**Comment by brianlovin** [comment]
@nainarazz this is almost ready! Looks like just one last merge conflict there, and I'm not sure exactly what the right merge order should be be. Could you take a look?

**Comment by nainarazz** [comment]
Conflict resolved :)

**Comment by brianlovin** [comment]
@nainarazz testing locally:
- we should prompt if the user clicks outside of the composer or clicks cancel
- we should only prompt for outside click, cancel click, and esc press if there is no title and no body typed. it doesn't make sense to prompt if there is nothing to discard in the first place :)

**Comment by nainarazz** [comment]
@brianlovin yes you're totally right. I was also going to say the same thing ☺️I'll work on it.

**Comment by nainarazz** [comment]
I'm a bit confused about your second remark. Shouldn't it be that we prompt the user if they typed something in the title or body? Basically we are asking them if they want to discard what they have already typed. If the title and body are empty, then we don't show the modal.

I just want to clarify 'coz I think I didn't fully understand your remark ☺️

**Comment by brianlovin** [comment]
> Shouldn't it be that we prompt the user if they typed something in the title or body?

Yep, that's what I meant, sorry for the confusing comment :P If something has been typed, we prompt to confirm that what they typed will be discarded. If nothing was typed, no need to prompt.

**Comment by brianlovin** [comment]
@nainarazz this is coming along great! A couple bugs:

- If you edit a post and cancel, the edited content persists (but is not saved in the backend)
Video: https://www.dropbox.com/s/vboq9jpkz7oxq9k/editbreak.mov?dl=0

- It would be really awesome if we could maintain the same keyboard behavior of modals: esc should close the modal, enter should submit the modal. I tried implementing this but the keyboard event listener seems to be conflicting with the composer's event listeners. Any ideas on how to do this?

**Comment by nainarazz** [comment]
>this is coming along great! A couple bugs:
> 
> * If you edit a post and cancel, the edited content persists (but is not saved in the backend)

Ok I'll check on this.

> * It would be really awesome if we could maintain the same keyboard behavior of modals: esc should close the modal, enter should submit the modal. I tried implementing this but the keyboard event listener seems to be conflicting with the composer's event listeners. Any ideas on how to do this?

I think we can try to implement an keyhandler listener inside the confirmation modal. This will create a conflict with the composer event listener though. In order to avoid the conflict, I think we need to know where the event is coming from. If it is coming from the composer, then we listen to the composer event listerns; otherwise we don't. 

I've already tried something on my local machine, but I'll push it up when it is working.

**Comment by nainarazz** [comment]
> * If you edit a post and cancel, the edited content persists (but is not saved in the backend)
>   Video: https://www.dropbox.com/s/vboq9jpkz7oxq9k/editbreak.mov?dl=0

@brianlovin I have failed to find a solution for this bug. It is related to the state of the thread content editor. 
// src/views/thread/components/threadDetail.js
`<Editor
            readOnly={!this.state.isEditing}
            state={body}
            onChange={this.changeBody}
            editorKey="thread-detail"
            placeholder="Write more thoughts here..."
            editorRef={editor => (this.bodyEditor = editor)}
            version={2}
          />`
The same state (props) is stored whether the post edit is canceled or not. Do you some idea on how to approach it?

**Comment by brianlovin** [comment]
@nainarazz I'm guessing we'll need a new intermediary state variable, something like `editedBody` that gets changed, but when the user cancels and exits edit mode we return the default `body`

**Comment by brianlovin** [comment]
Phew, this is getting really complex huh. Looking through your last commit, the `cancelEdit` state seems particularly complex. We're so close, but I'm worried that if we merge it as-is it's going to be way to hard to reason about what's going on when you edit a thread. Let me think on this for a bit, and maybe we can get @mxstbr's eye on this since he's the editor master

**Comment by nainarazz** [comment]
Agreed

**Comment by brianlovin** [comment]
@nainarazz I'd hate to see this get out of date too quickly, as this is a super useful PR. Any chance we can figure out a simpler way to handle that editing bug?

**Comment by nainarazz** [comment]
@brianlovin Let me see what I can do. I'm sure there's a way of simplifying the logic.

**Comment by nainarazz** [comment]
May I ask which part of the code/logic is difficult to understand?

**Comment by nainarazz** [comment]
A lot has changed already in the component regarding editing post. I will have to update my code again.

**Comment by brianlovin** [comment]
>  May I ask which part of the code/logic is difficult to understand?

https://github.com/withspectrum/spectrum/pull/4612/commits/b395cb128577bb4a97521f6aa517ec6a16502fe9 => this already helped alleviate my concerns :)

**Comment by nainarazz** [comment]
@brianlovin after updating my branch to the latest code in alpha, it seems that the bug issue is resolved. I don't have to make anymore changes. The code is now totally different from the previous one.

**Comment by brianlovin** [comment]
Will review this tomorrow!

**Comment by brianlovin** [comment]
We need to have some tests for this, I'm going to write them now.

**Comment by brianlovin** [comment]
@nainarazz I wrote a bunch of tests to check all of the behavior I think we need covered - mind giving the assertions a quick skim and help me think if I'm missing anything?

https://github.com/withspectrum/spectrum/pull/4612/commits/08de5929416ba90bc44f08ac6f628543ebee77e8

**Comment by brianlovin** [comment]
Seems we've still got some flakiness - all of the failed e2e here pass locally, and when I re-run the workflow it seems different ones fail

**Comment by nainarazz** [comment]
@brian I think there should also be tests regarding editing of messages(comments). When you edit a message, a modal will also show if the content has changed and cancel or ESC was pressed.

**Comment by brianlovin** [comment]
> I think there should also be tests regarding editing of messages(comments). When you edit a message, a modal will also show if the content has changed and cancel or ESC was pressed.

Oh, great call! Would you be up for tackling these tests, given the examples in the previous commit?

**Comment by nainarazz** [comment]
> Oh, great call! Would you be up for tackling these tests, given the examples in the previous commit?

sure

**Comment by brianlovin** [comment]
We're going to ship this in #4965, cc @nainarazz - sorry for the delay!

**Comment by nainarazz** [comment]
> We're going to ship this in #4965, cc @nainarazz - sorry for the delay!

that's great!

**Pull request merged**
