### PR TITLE
Improve watercooler render

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [x] WIP
- [ ] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

This is a very bad first pass at #4690. The tricky thing here is getting the `lastMessage` snippet to update as messages come in, since it requires a different graphql query that won't trigger the cache updates (at least as far as I could test). Want to give that a try to figure out the updating @mxstbr and I can keep working on the design tomorrow?

### CODE REVIEW

**Comment by mxstbr** [comment]
There is no need to add an extra field to the API, let's add an argument to `messageConnection({ last: 1 })` instead?! That should also take care of updating as long as we subscribe from the feed card.

**Comment by brianlovin** [comment]
> There is no need to add an extra field to the API, let's add an argument to `messageConnection({ last: 1 })` instead?! That should also take care of updating as long as we subscribe from the feed card.

I see, I can try that

**Comment by mxstbr** [comment]
Turns out we have already implemented that! Latest commit switches the watercooler thread feed card to use `messageConnection(last: 1)` and removes the `lastMessage` field :tada:

Going to tackle updating now.

**Comment by brianlovin** [comment]
We can safely close this

**Pull request closed without merging**
