### PR TITLE
🎨 Truncate link attachments in thread inbox component

### LINKED ISSUE #2572: Truncate link attachments
screenshot 2018-03-13 10 17 25

### PR DESCRIPTION
**Pull request by dev-drprasad**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

closes #2572

### CODE REVIEW

**Review by mxstbr — APPROVED** [review]
I love this code-wise! :100: If it works let's ship it

**Comment by dev-drprasad** [comment]
In local development, is there any way to mock new messages in thread ?

**Comment by brianlovin** [comment]
Yep! `yarn run dev:athena` in the background, then just have two user accounts in different browser windows

**Comment by brianlovin** [comment]
Lowercase athena in that command - I’m on mobile and can’t edit the comment 😵

**Comment by dev-drprasad** [comment]
I am able to use accounts. chat from each other. but i am unable to see that link at all
screen shot 2018-04-07 at 9 22 22 pm

**Comment by brianlovin** [comment]
Oh I think I misunderstood. To get a link there you need to add a link in the original thread. That will create a link preview

**Comment by dev-drprasad** [comment]
I created new community. added link. but still unable to see
screen shot 2018-04-07 at 10 21 11 pm
screen shot 2018-04-07 at 10 23 29 pm

**Comment by dev-drprasad** [comment]
any way i hardcoded values in codebase. and took screenshot
screen shot 2018-04-07 at 10 26 28 pm
this is how fixed styles looks like.
if there is anything i should do to ship it, let me know

**Comment by brianlovin** [comment]
Awesome! And the way to get the link to appear on its own is to put it in the thread, not in the community :) sorry for any confusion there. Going to review this soon and we can ship it!

**Comment by brianlovin** [comment]
This is working great - thanks so much @dev-drprasad :D

**Pull request merged**
