### PR TITLE
Restrict sign ups to GitHub, work on UX

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

### CODE REVIEW

**Comment by brianlovin** [comment]
@mxstbr this is going to be hard to get right, so please poke around and help me identify where this flow is confusing.

The key changes:
- we reject new users created in the API if the `providerMethod` is not GitHub. If it's the case that a user is trying to create a new account with another provider, it will redirect the user to `/new/user`. On this view, we now render a "sign up" screen if the user is not signed in - the only option provided is GitHub. There is an escape hatch back to `/login` where all signup methods are available for existing users.

Please review carefully and leave feedback! We can follow up later with in-app upsells for people to connect existing non-GitHub authed accounts with a GitHub profile.

**Review by mxstbr — CHANGES_REQUESTED** [review]
Wow I really like how this works, great work! Quick bug reports:

1. Being unauthenticated, going to a community view, then clicking "Join", and then clicking "Sign up" leads to this state, the modal does not close correctly: (also, the header text should match the button text with "Log in")

  Screenshot 2019-06-21 at 09 00 12

2. Am I correct in assuming this removes support for custom login screens?

Some communities are going to be a bit mad—we should link to a "FAQ" section next to this blurb that (in abstract terms) explains why signups are restricted.

Screenshot 2019-06-21 at 08 59 02

**Comment by brianlovin** [comment]
@mxstbr ready for re-review. I've updated `/:communitySlug/login` and the login modal behavior.

**Review by mxstbr — DISMISSED** [review]
LGTM!

**Review by mxstbr — APPROVED** [review]

**Pull request merged**
