### PR TITLE
Updated email wording from ‘mute’ to ‘unsubscribe’

### PR DESCRIPTION
**Pull request by denichodev**
**Status**
- [ ] WIP
- [ ] Ready for review
- [x] Needs testing

**Release notes for users (delete if codebase-only change)**
- Updated email footer wording

Wasn't sure on how to test it properly. Might need some help to test it.

### CODE REVIEW

**Review by mxstbr — CHANGES_REQUESTED** [review]
Let's change these all to "Unsubscribe from xyz" instead? "Unsubscribe all new thread notification emails" sounds kinda weird.

In terms of testing, don't worry about it—we'll test this for you. Thank you for contributing! 💜

**Comment by denichodev** [comment]
@mxstbr Updated it!

Is there a public channel for Spectrum open source development where any contributor can ask things around? Really interested in contributing more 😄

**Review by mxstbr — APPROVED** [review]
This LGTM

**Comment by brianlovin** [comment]
@denichodev - https://spectrum.chat/spectrum/open

**Review by mxstbr — DISMISSED** [review]
@brianlovin mind shipping this and copying the email templates to Postmark? I'm not 100% sure how that works anymore, thanks.

**Comment by brianlovin** [comment]
Super small request: 
- can we also make the `weeklyDigest` template say `Unsubscribe from {{timeframe}} digests`
- can the `newRepliesInThreads` template say `Unsubscribe from all new reply notifications in conversations where I'm active` on line 584
- can the `mentionInThread` and `mentionInMessages` templates say `Unsubscribe from all @mention notifications` on line 490

I think those are the last few needed to bring consistency to the language on those footer actions :)

**Pull request closed without merging**
