### PR TITLE
Enable CSP

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

**TODO**

- ~~Fix nonce being empty~~ Chrome DevTools just hides it for security reasons 🤦‍♂️ 

**Related issues (delete if you don't know of any)**
Rebase of #2943

### CODE REVIEW

**Comment by mxstbr** [comment]
Deploying to alpha, let's see what breaks

**Comment by mxstbr** [comment]
Test failures seem unrelated?

**Comment by mxstbr** [comment]
I think this works! Can you double check me @brianlovin and then ship?

**Review by brianlovin — APPROVED** [review]
This LGTM overall, but will be checking more when we have it in prod context so that we can double check it doesn't interfere with user created content.

**Pull request merged**
