### PR TITLE
Fix some icons, new tab bar icons

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- mobile

Updates tab bar icons to fit HIG spec, fixes send icon. h/t @uberbryn :)

### CODE REVIEW

**Review by mxstbr — APPROVED** [review]
LGTM

**Comment by mxstbr** [comment]
Actually, now that I look at 'em these icons look really weird and don't really fit together:

screen shot 2018-06-12 at 10 30 09

The search icon feels out of place since it doesn't have any fill, and the profile icon feels really bold because it has the wrapper around it. Why did we change them to be the filled versions? If they have to be filled, can we at least make it so all of them have the squircle wrapper like the profile one?

**Comment by superbryntendo** [comment]
1. Apple's standard wants them as filled icons. I personally prefer the stroked icons as well, though.
2. I think they look pretty consistent except that the Messages icon feels off-center vertically and yes - of course the Search icon looks completely out of place, but that should go away asap to be replaced with Explore.

Also, I think we should move Search to the end of the nav bar in the meantime.

**Comment by mxstbr** [comment]
Let's just go with the stroked ones then?

**Comment by brianlovin** [comment]
cc @uberbryn just ping me when you want to swap anything out; assuming you have mobile running locally so you can see it on-device, but lmk if i can help there

**Pull request merged**
