### PR TITLE
Security middleware implementation

### LINKED ISSUE #2775: Use helmet to protect our Node servers
We should use Helmet to protect our servers and users from some common attack vectors: https://expressjs.com/en/advanced/best-practice-security.html#use-helmet

### PR DESCRIPTION
**Pull request by spartDev**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)
- pluto

**Release notes for users (delete if codebase-only change)**
- Create security middleware for different node servers to improve security.
- use of **Helmet** with some configurations: 

     - we don' want to expose any software information to hackers.
     ```js
      server.disable('x-powered-by');
     ```
     - Sets the X-XSS-Protection header to prevent reflected XSS attacks. [more info](https://helmetjs.github.io/docs/xss-filter//)
    - Mitigates clickjacking attacks by setting the X-Frame-Options header. [more info](https://helmetjs.github.io/docs/frameguard/)
   - Sets the X-Download-Options to prevent Internet Explorer from executing downloads in your site’s context. [more info](https://helmetjs.github.io/docs/ienoopen/)
  - Don’t Sniff Mimetype middleware, noSniff, helps prevent browsers from trying yo guess (“sniff”) the MIME type, which can have security implications. [more info](https://helmetjs.github.io/docs/dont-sniff-mimetype/)

- use of [Hpp](https://github.com/analog-nico/hpp) express middleware to protect against HTTP Parameter Pollution attacks

Finally, I prefer to separate things and implement the CSP (Content Security Policy) rules in a future PR

close: #2775

### CODE REVIEW

**Review by mxstbr — COMMENTED** [review]
Overall this looks good to me so far, I'll deploy it to alpha.spectrum.chat and see how well it works!

Notes:

- pluto doesn't need this, only the api and hyperion

**Comment by spartDev** [comment]
I was not sure about **pluto**. 
I made the change

**Comment by mxstbr** [comment]
I'm deploying this to `alpha.spectrum.chat`!

**Review by mxstbr — APPROVED** [review]
Works perfectly, cannot find any bugs! Thanks so much for digging into this, shipping!

**Comment by spartDev** [comment]
👍

**Comment by brianlovin** [comment]
Awesome stuff here @spartDev :D

**Pull request merged**
