### PR TITLE
Convert vulcan worker to redis jobs

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [ ] Ready for review
- [x] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- vulcan

I just need to do some testing on this for a bit to make sure I didn't break anything, but overall this is a much safer and more scalable solution for search indexing than changefeeds :)

### CODE REVIEW

**Review by mxstbr — COMMENTED** [review]
LGTM so far!

**Comment by brianlovin** [comment]
Tested everything, this is working! Ready for final review and I'll ship it @mxstbr :)

**Review by mxstbr — APPROVED** [review]
Code LGTM, if it works let's ship it! Are you sure we didn't miss a place where we need to index?

**Comment by brianlovin** [comment]
> Are you sure we didn't miss a place where we need to index?

I think I got em all, but will do one more check right now.

**Comment by brianlovin** [comment]
I think we've got everything covered. If I discover anything in my content-deletion refactor I'll update it :)

**Pull request merged**
