### PR TITLE
Reduce db connection counts across the board

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [ ] Ready for review
- [x] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)
- athena
- vulcan
- mercury
- hermes
- chronos

Definitely have to test this one on alpha first

### CODE REVIEW

**Comment by mxstbr** [comment]
Deployed to api.alpha, please use that and report any slowness! I don't think you'll see any though, we might have to trial-test this in prod...

**Comment by mxstbr** [comment]
I've aliased to prod API, let's see what happens. I'm ready to revert at any point.

**Review by brianlovin — APPROVED** [review]
Let's keep an eye on this today and if things are holding strong by the afternoon I'll cut it :)

**Comment by mxstbr** [comment]
Now that I look at this again, should we reduce the connection pool max size in workers even more? Most of them don't have changefeeds, and if they slow down for a bit it's not too big a deal if that means the API stays responsive. Might be worth investigating?

**Comment by brianlovin** [comment]
> Now that I look at this again, should we reduce the connection pool max size in workers even more? Most of them don't have changefeeds, and if they slow down for a bit it's not too big a deal if that means the API stays responsive. Might be worth investigating?

Yeah, you're probably right - I mean, these values are already dramatically lower so lets start here and iterate if we keep hitting problems.

**Comment by brianlovin** [comment]
This has been holding up for 6+ hours, going to merge and deploy it with a discrete prod cut here in a few mins for an easy-revert if needed

**Comment by brianlovin** [comment]
This is live on all workers

**Pull request merged**
