### PR TITLE
♻️ Catch queue failed events and report to sentry

### LINKED ISSUE #2768: Get sentry reports for failed worker jobs
We don't appear to be getting failure reports from workers like Hermes (470 failures in last 24hrs) - make sure these are reported to Sentry

### PR DESCRIPTION
**Pull request by dev-drprasad**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- athena

Fixes #2768

### CODE REVIEW

**Comment by brianlovin** [comment]
Great! Can we add this to all workers? cc @mxstbr I *think* this will help us ou

**Comment by dev-drprasad** [comment]
@brianlovin  It works for all workers (if understood correctly).  if you see `shared/bull/queues.js` , we are constructing separate queues for all actions for all workers. That queue constructor imported from `shared/bull/create-queue.js`. here we are catching `failed` events. so its should work for all workers who use `createQueue` from `shared/bull/create-queue.js`. correct me if i am wrong

**Comment by brianlovin** [comment]
Oh, duh - face palm. We'll just have to *deploy* all the workers again :)

**Comment by dev-drprasad** [comment]
But why ?? if we deploy only `athena` , it will kill all existing queues and create news ones, right ??

**Comment by brianlovin** [comment]
Athena isn't a hub for the other works, each worker stands alone in creating its queues, so we'll need to redeploy each one. Not a huge deal!

**Review by mxstbr — DISMISSED** [review]
Looks great to me, thank you so much for contributing! :100:

**Pull request merged**
