### PR TITLE
Closes #2748 - Write test for sending messages in private channels.

### LINKED ISSUE #2748: Write test for sending messages in private channels
Right now our cypress test for sending messages only sends in public threads. Let's add a test to confirm that messages are able to send in private threads when the user has the right permissions.

### PR DESCRIPTION
**Pull request by mikenikles**
1. A new test covers users who have permissions.
2. A second test makes sure users without permissions cannot send messages.

This closes #2748, please let me know what you think. I'm slowly familiarizing myself with the code base - happy to make changes where necessary.

**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**

**Run database migrations (delete if no migration was added)**

**Release notes for users (delete if codebase-only change)**

### CODE REVIEW

**Comment by brianlovin** [comment]
Nice! I think the 2 failures in CI on this branch are random failures we've been plagued with for a while. Going to pull and test real quick

**Comment by brianlovin** [comment]
@mikenikles this is working great locally, but one question on the code itself: we've had a pattern of doing the `cy.auth` and `cy.visit` steps in a `beforeEach` hook for each test - I noticed that in this PR the auth + visits happen inline in the `it` block itself. Did you find this to work better for you? Or would it work just as well to keep the pattern of having auth and initial page visit logic in a `beforeEach` hook?

**Comment by mikenikles** [comment]
Thanks for the review @brianlovin. I agree, keeping the existing pattern makes sense. It meant restructuring the `describe()` blocks a bit, but looking at it now I realize it is more readable than I thought last night. Changes can be seen in 9793c18.

As for the failed tests, they passed in the latest `test_web` [job 4473](https://circleci.com/gh/withspectrum/spectrum/4473). However, another test failed. I noticed random failures locally too, but haven't figured out the root cause. If I find it, I'll open a separate PR.

**Review by mxstbr — APPROVED** [review]
This looks great to me, thank you so much! 😍

**Pull request merged**
