### PR TITLE
Enable yarn workspaces

### PR DESCRIPTION
**Pull request by edorivai**
**Status**
- [x] WIP
- [ ] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)
- athena
- vulcan
- mercury
- hermes
- chronos
- pluto
- mobile

# This is a WIP
Related issue: #2952 
Related PR: #2793 

As discussed in #2952, this PR should migrate to yarn workspaces, as a replacement for the custom installation script.

This PR has some overlap with #2793, but nothing that should lead to serious conflicts, I think.

TODO list:
- [x] Enable workspaces
- [ ] Remove `shared/install-dependencies.js`
- [ ] Review whether CircleCI config needs to be updated
- [ ] Update `Contributing` docs about installing dependencies
- [x] Copy root `yarn.lock` to each of the services at `postbuild`
- [ ] Verify that the setup works with Now

## Opportunity to restructure sharing code
From yarn workspace docs:
> Your dependencies can be linked together, which means that your workspaces can depend on one another while always using the most up-to-date code available. This is also a better mechanism than yarn link since it only affects your workspace tree rather than your whole system.

From `shared/draft-utils.js`:
```
/**
 * This file is shared between server and client.
 * ⚠️ DON'T PUT ANY NODE.JS OR BROWSER-SPECIFIC CODE IN HERE ⚠️
 *
 * Note: This uses Flow comment syntax so this whole file is actually valid JS without any transpilation
 * The reason I did that is because create-react-app doesn't transpile files outside the source folder,
 * so it chokes on the Flow syntax.
 * More info: https://flow.org/en/docs/types/comments/
 */
```

I'm not sure if this would yield enough benefits, but I think we might be able to structure shared code as a "proper" dependency, using yarn workspaces. This way we could split up the shared code into discrete packages, and import them as such in depending packages:

```
import draftUtils from 'spectrum-draft-utils';
```

Thoughts?

### CODE REVIEW

**Comment by mxstbr** [comment]
> I think yarn will respect the dependencies in package.json, and just uses the yarn.lock as a reference to look up the "preferred" version for the packages defined in package.json.

If that's true that'd be great, let's try it! If you add the code to copy the root `yarn.lock` I can try deploying this.

**Comment by edorivai** [comment]
Yeah, what's your preferred way for testing against Now? Are you guys doing that, or is there a public testing environment against which I could test it?

**Comment by mxstbr** [comment]
You'd have to do a bunch of setup to add secrets and stuff, it's probably easier if I just try?

**Comment by edorivai** [comment]
I've added the copy commands for `yarn.lock`. Maybe you could try it already. I'll take a look at the failing mobile tests later.

**Comment by brianlovin** [comment]
Closing because stale, although if this still feels like something useful in the future @mxstbr we can do it later

**Pull request closed without merging**
