### PR TITLE
Upgrade to styled-components v4

### PR DESCRIPTION
**Pull request by mxstbr**
Yeah yeah I know it's in beta but it's so much faster I think we should
just upgrade. Most of the kinks are already worked out.

----

There's one small bug where you'll see warnings for "unknown event
handler props onboarding and onlineSize", I've started a discussion and
PR here
(https://github.com/styled-components/styled-components/issues/1969#issuecomment-426943214)
but that shouldn't hold us back from upgrading since it's just dev warnings!

**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

### CODE REVIEW

**Comment by brianlovin** [comment]
:P almost every test is failing

**Comment by brianlovin** [comment]
This branch, when run locally, absolutely destroys my computer. Spectrum completely locks up and eventually crashes my browser. cc @mxstbr possibly styled-components memory issue?

**Comment by mxstbr** [comment]
Dumb suggestions: can you try turning off flow?

**Comment by followbl** [comment]
@mxstbr @brianlovin I would love to know what the heck in styled-components v4 is causing this..but here's the fix to your laptop/machine feeling like it's about to grow wings ;)

https://github.com/withspectrum/spectrum/pull/4132

**Comment by brianlovin** [comment]
This probably is still worth doing at some point @mxstbr - do you think the latest patches to s-c should clear these problems?

**Comment by mxstbr** [comment]
Yeah but let's start a-new.

**Pull request closed without merging**
