### PR TITLE
Add migration to fix message counts on threads

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Run database migrations (delete if no migration was added)**
YES

cc @mxstbr should be pretty simple like this huh?

### CODE REVIEW

**Review by mxstbr — APPROVED** [review]
Yeah, sorry for being a dummy! :pray:

Why the `nonAtomic` flag?

**Comment by brianlovin** [comment]
> Why the nonAtomic flag?

Just copy-pasta'd yours. Probably not necessary but won't make a difference either way eh?

**Comment by mxstbr** [comment]
Yeah, LGTM!

**Comment by brianlovin** [comment]
> nonAtomic: if set to true, executes the update and distributes the result to replicas in a non-atomic fashion. This flag is required to perform non-deterministic updates, such as those that require reading data from another table.

I think this is why - we're reading from another table

**Comment by brianlovin** [comment]
This migration has been executed :)

**Pull request merged**
