### PR TITLE
Import emails to invite to community

### LINKED ISSUE #4611: Invite users in bulk
**Issue Type**

- [ ] Bug Report
- [x] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description**

Hi, 
I have a list of ~1000 members to invite from a community I currently have on Google+ (which is shutting down).

Is there any way to invite them in bulk, for example uploading a .csv file with the email addresses?

see https://spectrum.chat/spectrum/general/invite-users-in-bulk~17ae92bf-9a6e-42a2-b1b4-cfe19ebdd807

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

**Related issues (delete if you don't know of any)**
Closes #4611 

Adds ability to import JSON file with emails of users to be invited to community. Demo (note that UI is not polished, only the functionality):

spectrum-import-users-emails

<details>
  <summary>Click to see test files</summary>

- users-emails.json:

  ```JSON
  ["hi@bryn.io", "hi@brianlovin.com", "hi@mxstbr.com"]
  ```

- users-with-names.json:

  ```JSON
  [
    { "email": "arnold@schwarzenegger.at", "name": "Arnold" },
    { "email": "elon@musk.com", "name": "Elon" },
    { "email": "notanemail", "name": "Wrong" }
  ]
  ```

</details>

<br />

**Todo**

- [x] Show error when file import fails with parse error
- [x] Button styling
- [x] Add help text somewhere explaining the supported data shape

### CODE REVIEW

**Comment by mxstbr** [comment]
Added error handling (note the selected file names):

screen shot 2019-02-11 at 11 35 56
screen shot 2019-02-11 at 11 36 43

**Comment by mxstbr** [comment]
@brianlovin any ideas where best to put the help text about the supported file type and format? Do we have an existing pattern for that?

**Comment by brianlovin** [comment]
> @brianlovin any ideas where best to put the help text about the supported file type and format? Do we have an existing pattern for that?

We don't have an existing pattern for this. Maybe it could look like this instead:

screenshot 2019-02-11 17 43 49

I don't think we need to describe the optional method of uploading an array of objects; if people find that error message, they can do it, but ideally they just upload the array of emails. What do you think?

**Comment by mxstbr** [comment]
Looks good to me, will clean this up!

**Comment by mxstbr** [comment]
Updated based on your suggestions, ready for another review @brianlovin!

screen shot 2019-02-12 at 11 37 53

**Comment by brianlovin** [comment]
@mxstbr check https://github.com/withspectrum/spectrum/pull/4621/commits/9e9e31aa05f93787c53ca4bb8378254f02baeb95 for some logic changes:

- removes duplicates in the uploaded .json file; also de-duplicates from the existing `state.contacts`
- clears the input value after an upload is processed - this allows a person to upload the same file again if they messed up (eg upload, delete a couple email rows, re-upload)

You can see this in action better by uploading

```json
[
  "hi@bryn.io",
  "hi@brianlovin.com",
  "hi@mxstbr.com",
  "hi@bryn.io",
  "hi@brianlovin.com",
  "hi@mxstbr.com",
  "hi@bryn.io",
  "hi@brianlovin.com",
  "hi@mxstbr.com",
  "bad.email",
  "shouldnt@work.com"
]
```

Then in the frontend, try typing one of the existing emails (like `hi@brianlovin.com`), then upload the file. Duplicates will be removed, and you should see `bad.email` highlighted with a red border.

**Review by mxstbr — COMMENTED** [review]
Super nice, let's ship it!

**Comment by brianlovin** [comment]
Once tests pass I'll merge :)

**Review by brianlovin — DISMISSED** [review]

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
