### PR TITLE
Maybe fix forceScrollToBottom logic

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

@brianlovin can you double-check my thinkinghere? I think we only want to force scroll to bottom on short threads or long threads that don't have any new messages.

If it's a long thread we automatically show the newest message at the top—so we shouldn't scroll the thread to the bottom if there's messages you haven't seen.

### CODE REVIEW

**Comment by brianlovin** [comment]
Will test this locally later, may not have time today

**Comment by brianlovin** [comment]
@mxstbr I feel that we should just simplify this logic; we are introducing too many cases where the thread sometimes scrolls, sometimes it doesn't, sometimes it loads 50 messages, sometimes it only loads 2 based on the user's activity. As a result, the user experience is quite confusing and every thread is kinda like rolling a die to see what experience you'll get.

Let me know if you agree.

https://github.com/withspectrum/spectrum/pull/3486/commits/30becfda86c313e33613a0116f953126ac7e6c3b simplifies things to say:
- If the thread has less than 50 messages, load all of them. If the user has seen the thread before, created it, or has participated in it, force scroll to bottom
- If the thread has more than 50 messages, load only the last 50 *unless* the user has not seen the thread yet, in which case load the first 50.

This feels more predictable, although I understand it might be slightly less performant at times if we are loading messages a user has seen before. I think that's okay, as it's often better to have more context in the thread messages than less when reading a conversation, even if it's a conversation you've read before.

Additionally, this still gives us the flexibility to rework the scroll logic separately to scroll to the `new messages` indicator in the future.

**Comment by mxstbr** [comment]
> If the thread has more than 50 messages, load only the last 50 unless the user has not seen the thread yet, in which case load the first 50.

But what about if the user has seen the thread, but 100 messages have happened since? 🤔 I feel like this is a step backwards?

**Comment by brianlovin** [comment]
> But what about if the user has seen the thread, but 100 messages have happened since?

They will open the thread and be immediately force-scrolled to bottom, triggering a pagination event and then left scrolled halfway.

If we fix the scroll behavior then they stay scrolled to the top and don't know why this particular thread is staying at the top versus most threads which scroll to bottom once they've been active there. This is especially bad if the thread is long enough to push the messages off screen; the person may think the messages are still loading and wait for the force scroll to happen.

I agree that none of these are perfect.

I guess we could try to force scroll to top of the messages in the latter case? This just gets confusing because then we'll have to manage a `forceScrollToBottom`, `forceScrollToTop`, `forceScrollToMessages`

**Comment by brianlovin** [comment]
I feel like we're having this same fundamental design problem with mobile, too. I almost feel there should be a better design to keep the thread content and conversation in separate containers that don't have to battle for scroll position. E.g. a design where the thread content could be visible at all times or dismissed if not needed, and the chat is just a full height container where we can just jump to the `new messages` indicator...

Unfortunately I can't immediately visualize how this should work or look :P

**Comment by brianlovin** [comment]
That last commit moves closer to this desired behavior. There are some weird parts of it though, and one bug:

1. It's very weird to load a thread that has lots of messages, but if only one of them is "new" since the user last saw the thread we only render one message. Then if you leave the thread and come back, suddenly we load 50. Loading 1 message at a time is just...weird, because *all* context is getting lost.
2. The bug is this:
- with user (a) load a thread (1)
- switch away from the thread (1)
- with another user (b), post a message in thread (1)
- with user (a) view thread (1) - because there is only one new message since the last time you saw it, we only fetch one message
- with user (a) leave thread (1)
- with user (a) view thread (1)
- now that there are no new messages, we load the last 50 messages. The problem is that the UI has the original single message cached in the view, so the scroll to bottom function doesn't work because it fires before the rest of the messages get updated and rendered to change the scroll height.

Anyways...all of this still feels kinda crappy.

**Comment by brianlovin** [comment]
@mxstbr tomorrow I'd like to revert that last commit and then ship this; it's not perfect, but already fixes some really annoying scroll behavior in long threads. Would rather get that live and then spend the time to figure out scrolling to unread messages later (the last commit here gets close, but needs a lot more testing and bug fixing)

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
