### PR TITLE
Discord auth provider

### PR DESCRIPTION
**Pull request by Ponjimon**
**Status**
- [x] WIP
- [ ] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

**Run database migrations (delete if no migration was added)**
YES

**Release notes for users (delete if codebase-only change)**
- Adds Discord as a way to sign in

I'm not a designer, so someone would need to create a Glyph out of the Discord logo, if this PR gets accepted 😛 
I tested it, it works like a charm :D
Also the secrets for it need to be changed, the app doesn't exist anymore, I just needed one for testing.

localhost_3000_login

### CODE REVIEW

**Comment by brianlovin** [comment]
@lookapanda - really appreciate you digging into this, but so far we've not heard that this is a requested oauth method from folks, so I'm not sure how much this will get used. Each auth provider we add increases the complexity of our auth in general, and increases the likelihood of people accidentally creating duplicate accounts, so we want to be sure that all the ones we support are for strong reasons backed by people asking for it :)

**Comment by Ponjimon** [comment]
What about adding a config which decides which auth providers are active and which are not? Since Spectrum is a OSS now, some people might want to offer Discord auth on their installation but the official Spectrum could still disable it.

**Comment by brianlovin** [comment]
I see - while I understand that we are OSS and someone running an instance might like this, it will add to our surface area of possible bugs in auth.

At this point it might make the most sense for an individual installation to change the auth providers to whatever they need :)

Just curious: are you running your own installation at this point?

**Comment by Ponjimon** [comment]
No, I'm only running it locally.

**Comment by brianlovin** [comment]
Gotcha :) If it's okay, let's leave this one for down the road in case we find more times when people need different providers and we can find a solution that hopefully won't add too much surface area on our end for maintenance.

**Pull request closed without merging**
