### PR TITLE
Fix dashboard SSR

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

**Related issues (delete if you don't know of any)**
Ref #3303

@brianlovin 63ad628db _should_ fix the `?t` query param even when SSR'ing I think? I haven't been able to verify because I can't seem to log into the SSR'd site locally anymore. (not sure why) Further down below we check `(hasThreadsButNoneSelected || loadedNewThreads)` before selecting the first thread, which means even if one was selected as soon as new ones load in it would select the first one, right? So this new condition should make sure that doesn't happen if we mounted with that thread.

### CODE REVIEW

**Comment by mxstbr** [comment]
Deploying to alpha for testing!

**Comment by brianlovin** [comment]
Hm, looks like this isn't working on alpha, right?

**Comment by mxstbr** [comment]
It does fix one thing: selected threads are now correctly SSR'd! It still selects the first feed thread after loading the feed, but the selected threads now SSR as they should.

Will dig into why it's still selecting the first feed thread.

**Comment by mxstbr** [comment]
Look at these logs:

screen shot 2018-06-25 at 11 14 30

We unset the mounted thread ID before any threads were loaded, so when they finally do load in `mountedThreadId` is null and the app thinks it has the select the first thread! Will figure out how to fix this.

**Comment by mxstbr** [comment]
The last commit fixes it, the dashboard now works beautifully as far as I can tell! 😍 Deploying to alpha for testing again.

**Comment by mxstbr** [comment]
Working on one last problem: the loading state in the thread feed after SSR is finished.



Note how it shows the loading state even though all the threads are already loaded—it should just be doing that in the background.

**Comment by mxstbr** [comment]
Fixed the loading state too!!! 😍 The dashboard is very very nice now:



No loading state no nothin', it all just works as it should!

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
