### PR TITLE
Post new threads to watercooler v2

### LINKED ISSUE #4815: Post new threads to watercoolers v2
We experimented with posting new threads to watercoolers with a new "Spectrumbot" bot account in #4684. 

**Results of the MVP**

After deploying the MVP to production, many busy communities ended up with a watercooler that was nothing but "XYZ posted a new thread" bot messages for pages upon pages, making the watercooler chat useless. People asked how they could turn it off! 😕 

We also got the feedback that getting millions of emails for messages by a bot sucks (especially if one already gets new threads as emails), and that they weren't even sure whether it was a real account or a spammer at first.

Given the work we are doing in #4798 and #4721, hanging out in the watercooler will (hopefully) be a lot more common soon, and the threads lists will be a secondary concern. So, we do want to highlight new threads being posted in the watercooler to make sure folks see them.

**Going forward**

The important question for the next iteration is: how do we make it so that the watercoolers do not end up being useless due to overwhelming bot messages? A couple ideas:

1. Post the automatic messages as the author of the threads ("XYZ posted a new thread"), but still make it clear they were automatically posted with a `bot` label. For example on Slack when an app posts as a person it has an `App` label in the UI, we could do a similar thing:
  screenshot 2019-03-05 at 09 28 30
2. Group many threads together in a single message, something like "Peter, Lukas, Stephan, and Alex posted new threads:" and then limit the amount of embeds per message (group until a human posts a message, and then start a new message?) (we should probably limit the amount of embeds per message generally)
3. Give these automatic messages a different, less important treatment to make them less overwhelming, potentially something like the "XYZ joined" automatic messages in Slack, which are greyed out:
  screenshot 2019-03-05 at 09 33 38

Other ideas?

---- 

Out of these three, option 1 is my favorite. Contrary to posts by "Spectrumbot" it does not make it seem like the watercooler is devoid of humans, it makes it seem like it's full of humans and activity. It also allows us to continue experimenting with embed treatments, potentially putting an input inline or other "Reply" affordances—which would not be possible if we remove the embeds with option two or three.
 
Thoughts?

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

**Related issues (delete if you don't know of any)**
Closes #4815

This is what it looks like now in the watercooler:

screenshot 2019-03-07 at 13 06 47

See #4815 for the reasoning behind this implementation.

### CODE REVIEW

**Review by brianlovin — APPROVED** [review]
LGTM man, good work!

**Comment by brianlovin** [comment]
One followup here @mxstbr - did we want to disable email notifications for user-bot messages?

**Comment by mxstbr** [comment]
We totally can, let me do a quick follow-up before we ship!

**Comment by brianlovin** [comment]
No rush, I'll do a prod cut this afternoon

**Comment by mxstbr** [comment]
Done: #4836

**Pull request merged**
