### PR TITLE
Fix mobile onpress handler

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- mobile

So this somehow fixes the infinite loop thing

### CODE REVIEW

**Comment by brianlovin** [comment]
Whoa whoa, I'm finding some bugs with the `withNavigation` hoc...pretty sure it's introducing an infinite rerender

**Comment by brianlovin** [comment]
Lol what in the actual fuck. Using the `withNavigation` hoc breaks everything....

**Comment by brianlovin** [comment]
I FOUND THE PROBLEM. Sort of.

Using `withNavigation` to pass a `navigation` prop into the `InfiniteList` breaks the infinite list. But if you pass `navigation` as a prop directly (without the hoc) then things are fine. Pushing the fix now.

**Comment by brianlovin** [comment]
@mxstbr you can see the insanity here: https://github.com/withspectrum/spectrum/pull/3261/commits/88597d953ea427215a8aeb792e3659084b20f133

When viewing a thread the `Messages` component was triggering an infinite loop because it was using the `withNavigation` hoc and then rendering an `InfiniteList` - by removing the hoc and passing navigation down to `Messages` as a prop from the parent component, things are fixed.

**Comment by brianlovin** [comment]
Anyways - I don't think that `withNavigation` is inherently bad - we are using it in a ton of other places and it doesn't seem to be causing problems. It seems as though it was having issues with our `InfiniteList` component if they ever interacted, so removing those instances seems to have fixed all the problems we were experiencing and the app is back to normal.

**Comment by brianlovin** [comment]
Also note: in https://github.com/withspectrum/spectrum/pull/3261/commits/bbde15b918e008b81038bf0740c558240fd72873 I was able to get rid of all the `shouldComponentUpdate` logic!

**Comment by brianlovin** [comment]
Okay, sorry for the comment storm - I'm going to admin merge this now so I can work on other things tonight!

**Comment by brianlovin** [comment]
Not going to admin merge since it's kinda late here, may as well leave this open for you to review @mxstbr :)

**Review by mxstbr — DISMISSED** [review]
Oh my, no way! Thanks so much for finding that—will get Peril cleaned up and ship this

**Comment by mxstbr** [comment]
We've got a real e2e test failure, but it's not got anything to do with this PR, so I'll ship this and fix the e2e test in another one!

**Review by mxstbr — APPROVED** [review]

**Pull request merged**
