### PR TITLE
Activate last thread after closing new thread composer

### PR DESCRIPTION
**Pull request by denichodev**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

(not sure)

**Release notes for users (delete if codebase-only change)**
- Reopen last active thread after cancelling new thread form.

### CODE REVIEW

**Comment by brianlovin** [comment]
So far so good! For some reason this isn't working if you press the 'esc' key to close the composer :)

**Comment by denichodev** [comment]
@brianlovin My bad, clicking on other thread also fires a race condition behavior with that last code. I've reconsidered where I dispatch the action :)

**Comment by brianlovin** [comment]
This works beautifully, thanks so much for the fix! Going to wait for Danger status to report and then we'll merge this :)

**Comment by denichodev** [comment]
No problem, always happy to help!

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
