### PR TITLE
fix(shared/graphql): not flow typechecked file

### PR DESCRIPTION
**Pull request by ryota-murakami**
**Status**
- [x] Ready for review

**Deploy after merge (delete what needn't be deployed)**
- shared

i figure outed not flow typechecked file.
so i enable flow typeckeck at `shared/graphql/apollo-client-options.js` & add some any type.

this file syntax seems like before es2015, so strange for me:hushed:

### CODE REVIEW

**Review by brianlovin — APPROVED** [review]
In this case the `any` types won't be super useful, as anything can go through here without being enforced. Might be worth typing this based on the arguments being received :)

**Review by brianlovin — CHANGES_REQUESTED** [review]
Whoops.

**Comment by ryota-murakami** [comment]
@brianlovin thanks for your review:grinning:
i'll diging this code & find out properly type.

**Comment by mxstbr** [comment]
Don't worry about this too much, that file is very hard to type because essentially anything can come into it. On top of that, typing it is not very useful as you should never have to touch it—I'd probably just leave it untyped 😅 There's a lot more valuable stuff in the codebase that isn't typed!

**Comment by ryota-murakami** [comment]
@mxstbr oh, i misunderstood flow convention about existing file.(reading [this](https://github.com/withspectrum/spectrum#rules))
thanks:grinning:

**Pull request closed without merging**
