### PR TITLE
Update react router

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

### CODE REVIEW

**Comment by brianlovin** [comment]
Thanks for taking a look @mxstbr! Context is that I was running a prod cut, got stuck because API couldn't install the version of react-router we had specified. So I updated our react-router deps, which then broke react-app-rewired compilation. So I upgraded those packages and now I can't get tests to run because:

```
Error: The "injectBabelPlugin" helper has been deprecated as of v2.0. You can use customize-cra plugins in replacement - https://github.com/arackaf/customize-cra#available-plugins
```

**Comment by mxstbr** [comment]
> So I updated our react-router deps, which then broke react-app-rewired compilation.

That probably means react-router v5 has a breaking change that our frontend is not equipped to handle, not that we need to upgrade to react-app-rewired. Upgrading react-app-rewired would be very hard as there's lots of changes in create-react-app v2, we need to avoid doing that. 😅 

I'll try downgrading to the latest v4 release of react-router and the version of react-app-rewired that we were on and see if that fixes the build.

**Comment by mxstbr** [comment]
15242bf worked but exposed another issue with the `b2a` dependency, which I worked around in c030702. This should pass, let's see what CI says!

**Comment by mxstbr** [comment]
CI passed we all green again!

**Pull request merged**
