### PR TITLE
Use threadIdAndTimestamp index in mercury db query

### PR DESCRIPTION
**Pull request by mxstbr**
Note: Untested

**Status**
- [ ] WIP
- [ ] Ready for review
- [x] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- mercury

@brianlovin I'm not sure how to test whether this returns the exact same result, can you help me with that?

### CODE REVIEW

**Review by brianlovin — APPROVED** [review]

**Comment by mxstbr** [comment]
I hope you tested this... 😅

**Comment by brianlovin** [comment]
Whoops sorry didn't read your comment - the code looks good, but I'll try to test locally as well (I'm sure you tried, too?)

**Comment by mxstbr** [comment]
No I had a call so as I said, I haven't tested this yet... 😅

**Comment by brianlovin** [comment]
The hard ones to test are daily and weekly counts, just since it would require doing some local kung-fu to warp time. However, my initial tests with `remaining` and `hourly` are looking accurate across multiple threads

**Comment by mxstbr** [comment]
Ace

**Pull request merged**
