### PR TITLE
Quieter emails by default

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

Re https://twitter.com/brettlewis/status/1111014739348320256 - @mxstbr this kind of feedback has come up way too often, it's time to change this default behavior.

This PR makes it so that channel notifications are not enabled by default, unless you are the channel creator. I've exposed notifications UI to the channel list items so that members can quickly enable notifications where they care most about knowing when new threads are published.

### CODE REVIEW

**Review by mxstbr — COMMENTED** [review]
I disagree.

Only a tiny (but vocal) minority is complaining about this. Compare the size of the "notifications by default suck" crowd to the crowd that complained about the chat change—it is _tiny_, yet this  accounts (I assume) for a lot of our traffic.

I would love to ship just the nice controls you added so that users can easily opt-out immediately after joining, that makes a lot of sense to me, but I would keep the defaults the same. I think that's a fair middle ground so the vocal minority is happy, yet the broader audience still gets to see all the content that is posted in their communities.

Seems sensible?

**Comment by brianlovin** [comment]
Fair enough, let's start here and then figure out how to either
a) dynamically handle large/super active communities
b) provide granular unsub controls for each channel where you're a member, ideally from a centralized UI in user settings or something

**Review by mxstbr — APPROVED** [review]
LGTM!

**Comment by brianlovin** [comment]
Flaky e2e, unrelated. It's this `channel/edit_spec` and `user_spec` that both randomly fail...

**Pull request merged**
