### PR TITLE
Continuous deployment for desktop app

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

This sets up continuous deployment for the desktop app. The way this works is as follows:

1. We merge the latest changes from `alpha` to `production`
2. This prompts a CircleCI build, which packages all the apps and uploads them to GitHub as a draft release that looks like this:

  screen shot 2018-05-30 at 15 42 22

3. Test the app locally, if you're happy with how it works click the "Edit" button on the draft release and you get to this screen:

  screenshot-2018-5-30 withspectrum spectrum

4. Fill out the title and release notes of the release (like I've already done above), then click "Publish release"

This is what it'll look like once published: https://github.com/withspectrum/spectrum/releases/tag/v1.0.0-beta.1 As soon as it's published, the app will prompt existing users to upgrade to the newest version and download and install it for them.

> Note: I haven't been able to test the CI part of this whole thing, but from my local testing (which is how I generated the release above) it _should_ work!

### CODE REVIEW

**Comment by brianlovin** [comment]
Thank you so much for digging in here! Small favor: could you add these instructions to the docs?

**Comment by brianlovin** [comment]
@mxstbr afaik this is not working:

screenshot 2018-05-30 11 33 13

The CI pipeline never runs

https://circleci.com/gh/withspectrum/spectrum/7520

**Comment by brianlovin** [comment]
I'm not sure if we want to disable that 'only build pull requests' option though, otherwise our ci queue will blow up - right?

**Comment by brianlovin** [comment]
I am going to try and run that job manually

**Comment by mxstbr** [comment]
Ahhh damn fuck. Why does the CD for alpha work then?

**Comment by brianlovin** [comment]
Not sure :/ Anyways, I am going to do a manual release to at least test the auto updater!

**Comment by brianlovin** [comment]
FYI:
screenshot 2018-05-30 11 51 37

Digging into a fix, but we'll need to add docs for this, too

**Comment by brianlovin** [comment]
Just needed to set `GH_TOKEN` as an env var before running `release` - not sure how this will work from CI

**Comment by brianlovin** [comment]
Release published: https://github.com/withspectrum/spectrum/releases/tag/v1.0.0-beta.2 - we'll see if the autoupdater works!

**Comment by brianlovin** [comment]
That release is published - I closed and re-started the Spectrum app and it did not trigger an autoupdate (or at least it didn't detect one from the releases)

**Comment by mxstbr** [comment]
`GH_TOKEN` is set in CI already

**Comment by mxstbr** [comment]
Hmm I haven't gotten an auto update notification either :confused:

**Comment by mxstbr** [comment]
Aha! This is what I found in the CircleCI docs, which is why the alpha CD works:

> Note: For your default branch, we will always build all commits.

You know what we should do? This is a pretty simple fix: just do the desktop CD from the `alpha` branch. Since it won't actually be published until you publish the release on GitHub that should be perfectly fine.

**Pull request merged**
