### PR TITLE
Render embeds for linked threads in messages

### LINKED ISSUE #4669: Render nice embeds for thread links in messages
When a message contains a link to a thread on Spectrum of any kind we should render a nice preview of that thread and, on click, open the thread slider.

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

**Related issues (delete if you don't know of any)**
Closes #4669

This method gets the linked thread IDs from raw text, which means the only thing remaining is to render nice embeds for those IDs! @brianlovin want to tackle that, since it requires a bit of design work?

### CODE REVIEW

**Comment by brianlovin** [comment]
Yep, I can poke at this - seems like I'll just use those ids to fetch threads and render a react component

**Comment by mxstbr** [comment]
Exactly! :100:

**Comment by brianlovin** [comment]
Boom! Give that a pull @mxstbr 😁

**Comment by mxstbr** [comment]
Niice! 😍 

I think showing the author again is unnecessary, since the message is sent by the same author it looks a bit weird: 

screenshot 2019-02-21 at 09 43 49

Also I think we should show the like and reply count. 

I should also add some text to the message to make it clear why the message is there, something like "Published a new thread: <link>" or something.

**Comment by brianlovin** [comment]
> I think showing the author again is unnecessary, since the message is sent by the same author it looks a bit weird:

But we can never know if this is the case, right? You could be linking to any thread by anyone, so it might make sense in most cases?

> Also I think we should show the like and reply count.

Sure, I can add that in; the embeds are just becoming quite big :)

> I should also add some text to the message to make it clear why the message is there, something like "Published a new thread: " or something.

I'm not sure how useful this. Especially because "new" is relative - you could be linking to a thread that's quite old. It seems to me like you're not feeling that this stands out as an obvious "attachment" generate by the link in the message...

**Comment by brianlovin** [comment]
How about this: we don't render the avatar if the thread is by the message sender. This will solve the double avatar thing for watercooler automated posts, but will provide a nice experience for other organic thread url sharing happening on spectrum:

screenshot 2019-02-21 14 48 38

**Comment by mxstbr** [comment]
> I'm not sure how useful this. Especially because "new" is relative - you could be linking to a thread that's quite old.

I meant I add that text to the automatically generated message in #4684, so it does not just post a link it also posts "{so and so} just posted a new thread: <link>". We know that all those threads are new!

We should probably add a little `bot` label a la Slack to these auto-generated messages too...

I like this latest iteration more, looking at it thought I think it looks better with the avatar so let's just render it either way, you were right. 

> It seems to me like you're not feeling that this stands out as an obvious "attachment" generate by the link in the message...

I guess that's the root cause, yeah. Not sure why though 🤔 It might be because it does not give me any "preview" of the content? If you look at Slack embeds, they definitely show more content:

screenshot 2019-02-22 at 08 18 53

Maybe we should show the first n characters of the body a la Slack? I am not too worried about the embeds becoming too big to be honest, I have never thought that was the case with Slack and they render massive embeds.

**Comment by brianlovin** [comment]
> Maybe we should show the first n characters of the body a la Slack? I am not too worried about the embeds becoming too big to be honest, I have never thought that was the case with Slack and they render massive embeds.

Let's iterate on this - seems like there are a zillion edge cases we could hit with this if the first N characters breaks in an image or embed or something like that.

> I like this latest iteration more, looking at it thought I think it looks better with the avatar so let's just render it either way, you were right.

I don't mind it too much without the avatar when it's the same message sender, I agree that the duplication did look weird

**Comment by brianlovin** [comment]
New question:
- can users edit this message after the fact? if we don't want them to delete the history of this thread being published, then maybe it should be posted by a bot so its un-editable?

**Comment by mxstbr** [comment]
> can users edit this message after the fact? if we don't want them to delete the history of this thread being published, then maybe it should be posted by a bot so its un-editable?

Not worried about this at all, let's just let them edit/delete/whatever it for this version and if that starts being a problem we can always add in that bot account.

> Let's iterate on this - seems like there are a zillion edge cases we could hit with this if the first N characters breaks in an image or embed or something like that.

`toPlainText(body)` takes care of only returning plain text (that is how emails work fyi). Just do that and then cut after the first n chars! :100:

**Comment by brianlovin** [comment]
> `toPlainText(body)` takes care of only returning plain text (that is how emails work fyi). Just do that and then cut after the first n chars

Let's do this in a followup PR, since we're about to explore different thread content/layouts in our profile design experiments and can test out there :)

**Comment by mxstbr** [comment]
Does that mean you want to ship this?

**Comment by brianlovin** [comment]
Yes, let's ship this @mxstbr

**Comment by brianlovin** [comment]
Can you grab that merge conflict please? And I'm happy to do the prod cut today

**Comment by brianlovin** [comment]
I cannot get these e2e tests to pass man...rerun this workflow like 3x and waited 20mins each time :/

**Comment by mxstbr** [comment]
Going to merge #4757 into alpha and then into this, which should hopefully fix the flakyness 🤞

**Comment by mxstbr** [comment]
There we go that did it! :tada:

**Pull request merged**
