### PR TITLE
updates privacy policy to specifically address GDPR issues and simpli…

### PR DESCRIPTION
**Pull request by superbryntendo**
…fy language.

**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

**Release notes for users (delete if codebase-only change)**
- Updated Privacy Policy language to specifically address GDPR issues

### CODE REVIEW

**Review by mxstbr — APPROVED** [review]
Sure. We'll need to send an email to all our users notifying them of this change, too.

I really like how Conduit has the non-legally-binding plain english version next to the legalese: https://conduithq.com/legal/privacy/ We should probably do something like that too?

**Comment by brianlovin** [comment]
> We'll need to send an email to all our users notifying them of this change, too.

I hate that we have to do this :( And also that we don't currently have a way to do this and will need to pay a non-trivial amount of $ to set up an email provider to send this to all our users...sad times, GDPR

**Comment by superbryntendo** [comment]
@mxstbr longer term, absolutely. just not something i have time to do rn.

**Comment by ryota-murakami** [comment]
conformity GDPR bunch of rules or lose 20 billion penalty....
this is insanely😵

recently i read `Territorial scope` GDPR document and supposed spectrum case roughly...
https://gdpr-info.eu/art-3-gdpr/

Let's assume that the spectrum head quarter is not in the EU and does not provide localization versions such as French or Spanish to the UE and you are not accepting payment by euros or pounds.

There is a possibility that spectrum is not a target company for GDPR.

**Comment by brianlovin** [comment]
@ryota-murakami thanks for looking into it - we might not be a high priority target for it, but we definitely want to be compliant as we grow :)

**Pull request merged**
