### PR TITLE
add inline toolbar

### PR DESCRIPTION
**Pull request by juliankrispel**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- desktop

**Run database migrations (delete if no migration was added)**
NO

**Release notes for users (delete if codebase-only change)**
-

spectrum-inline-toolbar

### CODE REVIEW

**Comment by juliankrispel** [comment]
cc @mxstbr

**Comment by brianlovin** [comment]
😍😍😍

**Comment by mxstbr** [comment]
@brianlovin let's get this on alpha?

**Comment by juliankrispel** [comment]
Can u please make sure I integrated it right? 😱

**Review by mxstbr — DISMISSED** [review]
You did!

**Comment by juliankrispel** [comment]
I‘m just a little paranoid I guess. Would be nice if someone else tested it
too 🙄

**Comment by brianlovin** [comment]
@juliankrispel I tested it locally and it needs a z-index change and it's not implemented on our second composer (I know, we still maintain 2 separate composers which we need to unify). 

I'm happy to finish these items up, but might need direct access to the package in question. How should we go about publishing the inline editor package under Spectrum? cc @mxstbr

**Comment by brianlovin** [comment]
To clarify on the composers: we have an "inbox composer" which opens when you click the compose icon from the 'home' tab. There's also a "profile composer" which opens when you start a conversation from a community/channel profile e.g. /figma

**Comment by juliankrispel** [comment]
@brianlovin @mxstbr sent you both invites, would probably be good to move this over to your org anyway ...

**Comment by ryota-murakami** [comment]
Awesome!
What's the magic `spectrum-draft-js-inline-toolbar`😀

**Comment by juliankrispel** [comment]
@brianlovin I'd be happy to make the updates meself - if you tell me exactly what they are

**Comment by juliankrispel** [comment]
@brianlovin @mxstbr ping

**Comment by brianlovin** [comment]
Ah thought I replied here, sorry - will get back to this shortly @juliankrispel

**Comment by brianlovin** [comment]
1. We - very painfully - maintain two composers right now. So we just need to add this to both of them: 
- `src/components/composer` 
- and `src/components/threadComposer` 
- the `threadComposer` appears on profile pages, like `spectrum.chat/figma`

2. I noticed a z-index issue when running this locally where it was sitting behind the composer in the inbox view. It might be worthwhile to just bump the zindex to something pretty high - somewhere between `2000` and `3000` looks to be good, according to `src/components/globals/index` where we house our zindex variables.

That's it!

**Comment by juliankrispel** [comment]
Thank you! Will get on that right away!

**Comment by mxstbr** [comment]
Ping :blush:

**Comment by juliankrispel** [comment]
Whoopsie! Sorry, my bad, got drowned in other stuff.

So I think these are the two places you're talking off right @brianlovin ?

composer
thread-composer

**Comment by juliankrispel** [comment]
^ in which case we should be good to go, seems to work alright!

**Comment by brianlovin** [comment]
@juliankrispel it's getting close, but now I'm running into a lot of bugs that we might not have noticed earlier. Here's a video:

https://www.dropbox.com/s/9v4zw40sd8lw9x3/inline-editor.mp4?dl=0

1. You can't click outside the toolbar to close it. This often results in the toolbar getting stuck open
  - This appears to only be happening in the inbox editor. The editor on the community profile view *seems* to be working okay!
2. If you try to make text into a link, but don't insert a link, it shouldn't create linked text - e.g. we should validate that the input contains a url otherwise don't do anything

This first one is the biggest pain point which is currently making the editor unusable.

**Comment by juliankrispel** [comment]
oh shit - it might be I screwed something up when I updated the dependency,
all that was working before.

I'm right on it!

**Comment by brianlovin** [comment]
Thanks @juliankrispel! I suppose one additional thing before we wrap this all up too is: are we cool to migrate this inline repo to the Spectrum organization on GitHub and assign the npm project to @mxstbr ?

**Comment by juliankrispel** [comment]
absolutely, I'll do it asap!

**Comment by juliankrispel** [comment]
sry folks been crazy busy, just tried to squeeze in some time to look at this today but I'm afraid it'll have to wait til the weekend ❤️

**Comment by ryota-murakami** [comment]
@juliankrispel I'm looking forward that feature!!

**Comment by juliankrispel** [comment]
Btw I've been debugging this on and off and have always run into issues 😢 . The refs are causing trouble when they're switched. I'll try my best to fix it, hopefully I'll get another evening tonight or this weekend!

**Comment by juliankrispel** [comment]
@brianlovin finally - fixed all the things! Please test once more, it should be good to go

**Comment by juliankrispel** [comment]
@brianlovin btw I tried transferring ownership of the spectrum inline toolbar repo to `withspectrum` but couldn't because :
image

**Comment by brianlovin** [comment]
@juliankrispel gave this some more testing today and I'm only finding one lingering bug - but I think it will be pretty fast to fix. The checklist option:

screenshot 2018-09-13 17 04 19

has the following bug: if you select text, then choose the checkbox, you can't click to dismiss the toolbar anymore. I can't repro this with any of the other options.

The reason I suggest this should be fast-to-fix is because we can remove that checklist option entirely from the toolbar. Right now it doesn't actually do anything and we don't have any supporting design/components to handle checkboxes anyways.

After that, we're good to go as far as I can tell! 

cc @mxstbr any thoughts on how to get this transferred into our org?

**Comment by juliankrispel** [comment]
@brianlovin on it now! Let's get this done and dusted

**Comment by juliankrispel** [comment]
@brianlovin made the change and bumped the toolbar! No more checkboxes

**Comment by juliankrispel** [comment]
For some reason that circle ci test is now failing @brianlovin @mxstbr any idea?

**Comment by mxstbr** [comment]
No longer relevant as we have moved our thread editor to plaintext + markdown: #4564 

Thanks so much for your work on this anyway @juliankrispel! Sorry we never shipped it :pray:

**Comment by juliankrispel** [comment]
❤️

**Pull request closed without merging**
