### PR TITLE
fix: Improved "on hover" user cards positioning

### PR DESCRIPTION
**Pull request by FezVrasta**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

**Release notes for users (delete if codebase-only change)**
- improved "on hover" user cards positioning

------

Here's a quick gif of the new behavior:

https://imgur.com/a/ly1ZA

### CODE REVIEW

**Review by mxstbr — DISMISSED** [review]
This is great, thank you so much for contributing! 😍💜

**Review by mxstbr — COMMENTED** [review]
Just gotta `flow-typed install react-popper@1.0.0` to fix Flow! (or maybe `flow-typed create-sub react-popper@1.0.0` if you don't have a libdef for it)

**Comment by FezVrasta** [comment]
Umh so... the Flow error happens because your `.flowconfig` is ignoring all the `node_modules` so it doesn't consume the built-in flow typed files of `react-popper`...

I tried to ignore just the modules that give errors (as I usually do in my own projects) but there are some errors in your code that raise.

This is the list I tested:

```
.*/node_modules/expo
.*/node_modules/react-native
.*/node_modules/cypress
.*/node_modules/draft-js
.*/node_modules/graphql
.*/node_modules/protobufjs-no-cli
.*/node_modules/react-navigation
.*/node_modules/reqwest
.*/node_modules/sentry-expo
```

**Comment by mxstbr** [comment]
@FezVrasta that sounds great, if you can find the subset of packages that error and only ignore those I'd love you forever!

**Comment by FezVrasta** [comment]
There is quite some stuff going on actually :-(

<details>
  <summary>Click to expand</summary>
<pre><code>
spectrum git/fix/better-avatar-card-positioning*  85s
❯ flow
Launching Flow server for /Users/federicozivolo/Progetti/spectrum
Spawned flow server (pid=76928)
Logs will go to /private/tmp/flow/zSUserszSfedericozZivolozSProgettizSspectrum.log
Monitor logs will go to /private/tmp/flow/zSUserszSfedericozZivolozSProgettizSspectrum.monitor_log
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ api/loaders/create-loader.js:18:10

Cannot return new DataLoader(...) because:
 • property clear is read-only in DataLoader [1] but writable in Loader [2].
 • property load is read-only in DataLoader [1] but writable in Loader [2].
 • property loadMany is read-only in DataLoader [1] but writable in Loader [2].
 • DataLoader [3] is incompatible with undefined [4] in the return value of property clear.
 • array type [5] is incompatible with string [6] in array element of the first argument of property loadMany.
 • array type [7] is incompatible with string [6] in array element of the first argument of property loadMany.

        api/loaders/create-loader.js
         15│   indexField: string | Function = 'id',
         16│   cacheKeyFn: Function = key => key
    [2]  17│ ) => (options?: DataLoaderOptions): Loader => {
    [1]  18│   return new DataLoader(keys => {
         19│     return batchFn(unique(keys)).then(
         20│       normalizeRethinkDbResults(keys, indexField, cacheKeyFn)
         21│     );
         22│   }, options);
         23│ };
         24│
         25│ // These helper functions were taken from the DataLoader docs

        api/loaders/types.js
    [5]   4│   load: (key: string | Array<string>) => Promise<any>,
    [6]   5│   loadMany: (keys: Array<string>) => Promise<any>,
 [7][4]   6│   clear: (key: string | Array<string>) => void,

        api/node_modules/dataloader/index.js.flow
    [3] 147│   clear(key: K): DataLoader<K, V> {


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ api/loaders/create-loader.js:19:27

Cannot call unique with keys bound to array because string [1] is incompatible with mixed [2] in array element.

     api/loaders/create-loader.js
     16│   cacheKeyFn: Function = key => key
     17│ ) => (options?: DataLoaderOptions): Loader => {
     18│   return new DataLoader(keys => {
     19│     return batchFn(unique(keys)).then(
     20│       normalizeRethinkDbResults(keys, indexField, cacheKeyFn)
     21│     );
     22│   }, options);

     api/loaders/types.js
 [1]  5│   loadMany: (keys: Array<string>) => Promise<any>,

     shared/unique-elements.js
 [2]  5│ const unique = (array: Array<mixed>): Array<mixed> => {


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ api/loaders/create-loader.js:22:6

Cannot call DataLoader with options bound to options because:
 • property batch is missing in DataLoaderOptions [1] but exists in Options [2].
 • property cacheKeyFn is missing in DataLoaderOptions [1] but exists in Options [2].
 • property cacheMap is missing in DataLoaderOptions [1] but exists in Options [2].
 • property maxBatchSize is missing in DataLoaderOptions [1] but exists in Options [2].

     api/loaders/create-loader.js
 [1] 17│ ) => (options?: DataLoaderOptions): Loader => {
     18│   return new DataLoader(keys => {
     19│     return batchFn(unique(keys)).then(
     20│       normalizeRethinkDbResults(keys, indexField, cacheKeyFn)
     21│     );
     22│   }, options);
     23│ };
     24│
     25│ // These helper functions were taken from the DataLoader docs

     api/node_modules/dataloader/index.js.flow
 [2] 46│     options?: Options<K, V>


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ mobile/views/Thread/index.js:16:51

Cannot call getThreadMessageConnection with Messages bound to component because React.StatelessFunctionalComponent [1]
is incompatible with statics of React.Component [2].

     mobile/views/Thread/index.js
      13│
      14│ import { Wrapper } from './style';
      15│
      16│ const ThreadMessages = getThreadMessageConnection(Messages);
      17│
      18│ type Props = {
      19│   isLoading: boolean,

     /private/tmp/flow/flowlib_dd2a209/react.js
 [2] 138│   | Class<React$Component<Props, any>>;

     mobile/components/ViewNetworkHandler/index.js
 [1]  56│ ): ComponentType<$Diff<Props, ViewNetworkHandlerProps>> {


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/mutations/channel/createChannel.js:42:25

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

        shared/graphql/mutations/channel/createChannel.js
        39│         variables: {
        40│           input,
        41│         },
    [3] 42│         refetchQueries: [
        43│           {
        44│             query: getCommunityChannelConnectionQuery,
        45│             variables: {
        46│               id: input.communityId,
        47│             },
        48│           },
        49│         ],
        50│       }),
        51│   }),
        52│ };

        node_modules/react-apollo/react-apollo.umd.js.flow
 [1][2] 65│   refetchQueries?: string[] | PureQueryOptions[];


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/mutations/channel/joinChannelWithToken.js:40:3

Cannot call graphql with joinChannelWithTokenOptions bound to operationOptions because:
 • a callable signature is missing in object literal [1] but exists in OptionDescription [2] in property options.
 • property refetchQueries is missing in OptionDescription [2] but exists in object literal [1] in property options.

     shared/graphql/mutations/channel/joinChannelWithToken.js
 [1]  25│   options: {
      26│     refetchQueries: ['getCurrentUserProfile', 'getEverythingThreads'],
      27│   },
        :
      37│
      38│ export default graphql(
      39│   joinChannelWithTokenMutation,
      40│   joinChannelWithTokenOptions
      41│ );
      42│

     node_modules/react-apollo/react-apollo.umd.js.flow
 [2] 107│   options?: OptionDescription<TProps>;


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/mutations/channel/toggleChannelPendingUser.js:60:25

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

        shared/graphql/mutations/channel/toggleChannelPendingUser.js
        57│         variables: {
        58│           input,
        59│         },
    [3] 60│         refetchQueries: [
        61│           {
        62│             query: getChannelMemberConnectionQuery,
        63│             variables: {
        64│               id: input.channelId,
        65│             },
        66│           },
        67│         ],
        68│       }),
        69│   }),
        70│ };

        node_modules/react-apollo/react-apollo.umd.js.flow
 [1][2] 65│   refetchQueries?: string[] | PureQueryOptions[];


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/mutations/channel/toggleChannelSubscription.js:40:3

Cannot call graphql with toggleChannelSubscriptionOptions bound to operationOptions because:
 • a callable signature is missing in object literal [1] but exists in OptionDescription [2] in property options.
 • property refetchQueries is missing in OptionDescription [2] but exists in object literal [1] in property options.

     shared/graphql/mutations/channel/toggleChannelSubscription.js
 [1]  25│   options: {
      26│     refetchQueries: ['getCurrentUserProfile', 'getEverythingThreads'],
      27│   },
        :
      37│
      38│ export default graphql(
      39│   toggleChannelSubscriptionMutation,
      40│   toggleChannelSubscriptionOptions
      41│ );
      42│

     node_modules/react-apollo/react-apollo.umd.js.flow
 [2] 107│   options?: OptionDescription<TProps>;


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/mutations/directMessageThread/createDirectMessageThread.js:55:3

Cannot call graphql with createDirectMessageThreadOptions bound to operationOptions because:
 • a callable signature is missing in object literal [1] but exists in OptionDescription [2] in property options.
 • property refetchQueries is missing in OptionDescription [2] but exists in object literal [1] in property options.

     shared/graphql/mutations/directMessageThread/createDirectMessageThread.js
 [1]  21│   options: {
      22│     refetchQueries: ['currentUserDirectMessageThreads'],
      23│   },
        :
      52│
      53│ export default graphql(
      54│   createDirectMessageThreadMutation,
      55│   createDirectMessageThreadOptions
      56│ );
      57│

     node_modules/react-apollo/react-apollo.umd.js.flow
 [2] 107│   options?: OptionDescription<TProps>;


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/mutations/notification/markDirectMessageNotificationsSeen.js:21:3

Cannot call graphql with markDirectMessageNotificationsSeenOptions bound to operationOptions because:
 • property data is missing in object type [1] but exists in OptionProps [2] in property props.
 • property ownProps is missing in object type [1] but exists in OptionProps [2] in property props.

     shared/graphql/mutations/notification/markDirectMessageNotificationsSeen.js
 [1]  14│   props: ({ mutate }: { mutate: Function }) => ({
      15│     markDirectMessageNotificationsSeen: () => mutate(),
      16│   }),
      17│ };
      18│
      19│ export default graphql(
      20│   markDirectMessageNotificationsSeenMutation,
      21│   markDirectMessageNotificationsSeenOptions
      22│ );
      23│

     node_modules/react-apollo/react-apollo.umd.js.flow
 [2] 108│   props?: (props: OptionProps<TProps, TResult>) => any;


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/mutations/notification/markNotificationsSeen.js:37:3

Cannot call graphql with markNotificationsSeenOptions bound to operationOptions because:
 • property data is missing in object type [1] but exists in OptionProps [2] in property props.
 • property ownProps is missing in object type [1] but exists in OptionProps [2] in property props.

     shared/graphql/mutations/notification/markNotificationsSeen.js
 [1]  15│   props: ({ mutate }: { mutate: Function }) => ({
        :
      34│
      35│ export default graphql(
      36│   markNotificationsSeenMutation,
      37│   markNotificationsSeenOptions
      38│ );
      39│

     node_modules/react-apollo/react-apollo.umd.js.flow
 [2] 108│   props?: (props: OptionProps<TProps, TResult>) => any;


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/mutations/notification/markSingleNotificationSeen.js:24:3

Cannot call graphql with markSingleNotificationSeenOptions bound to operationOptions because:
 • property data is missing in object type [1] but exists in OptionProps [2] in property props.
 • property ownProps is missing in object type [1] but exists in OptionProps [2] in property props.

     shared/graphql/mutations/notification/markSingleNotificationSeen.js
 [1]  12│   props: ({ mutate }: { mutate: Function }) => ({
        :
      21│
      22│ export default graphql(
      23│   markSingleNotificationSeenMutation,
      24│   markSingleNotificationSeenOptions
      25│ );
      26│

     node_modules/react-apollo/react-apollo.umd.js.flow
 [2] 108│   props?: (props: OptionProps<TProps, TResult>) => any;


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/mutations/user/downgradeFromPro.js:27:29

Cannot call mutate because:
 • property optimisticResponse is missing in undefined [1] but exists in MutationOpts [2].
 • property refetchQueries is missing in undefined [1] but exists in MutationOpts [2].
 • property update is missing in undefined [1] but exists in MutationOpts [2].
 • property updateQueries is missing in undefined [1] but exists in MutationOpts [2].
 • property variables is missing in undefined [1] but exists in MutationOpts [2].

     shared/graphql/mutations/user/downgradeFromPro.js
     24│
     25│ const downgradeFromProOptions = {
     26│   props: ({ mutate }) => ({
 [1] 27│     downgradeFromPro: () => mutate(),
     28│   }),
     29│ };
     30│

     node_modules/react-apollo/react-apollo.umd.js.flow
 [2] 50│   opts: MutationOpts,


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/queries/community/getCommunityThreadConnection.js:75:46

Cannot get ownProps.community because property community is missing in object type [1].

      72│             const updatedThread = subscriptionData.data.threadUpdated;
      73│             if (!updatedThread) return prev;
      74│
      75│             const thisCommunityId = ownProps.community.id;
      76│             const updatedThreadShouldAppearInContext =
      77│               thisCommunityId === updatedThread.community.id;
      78│
        :
 [1] 137│   options: ({ id, after }: { id: string, after?: ?string }) => ({


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/queries/composer/getComposerCommunitiesAndChannels.js:110:3

Cannot call graphql with getComposerCommunitiesAndChannelsOptions bound to operationOptions because:
 • a callable signature is missing in object literal [1] but exists in OptionDescription [2] in property options.
 • property fetchPolicy is missing in OptionDescription [2] but exists in object literal [1] in property options.

     shared/graphql/queries/composer/getComposerCommunitiesAndChannels.js
 [1] 105│   options: { fetchPolicy: 'cache-first' },
     106│ };
     107│
     108│ export default graphql(
     109│   getComposerCommunitiesAndChannelsQuery,
     110│   getComposerCommunitiesAndChannelsOptions
     111│ );
     112│

     node_modules/react-apollo/react-apollo.umd.js.flow
 [2] 107│   options?: OptionDescription<TProps>;


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/queries/directMessageThread/getCurrentUserDMThreadConnection.js:113:3

Cannot call graphql with getCurrentUserDMThreadConnectionOptions bound to operationOptions because:
 • a callable signature is missing in object literal [1] but exists in OptionDescription [2] in property options.
 • property fetchPolicy is missing in OptionDescription [2] but exists in object literal [1] in property options.
 • property variables is missing in OptionDescription [2] but exists in object literal [1] in property options.

     shared/graphql/queries/directMessageThread/getCurrentUserDMThreadConnection.js
 [1]  38│   options: {
      39│     variables: {
      40│       after: '',
      41│     },
      42│     fetchPolicy: 'cache-and-network',
      43│   },
        :
     110│
     111│ export default graphql(
     112│   getCurrentUserDMThreadConnectionQuery,
     113│   getCurrentUserDMThreadConnectionOptions
     114│ );
     115│

     node_modules/react-apollo/react-apollo.umd.js.flow
 [2] 107│   options?: OptionDescription<TProps>;


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/queries/notification/getDirectMessageNotifications.js:103:3

Cannot call graphql with getDirectMessageNotificationsOptions bound to operationOptions because:
 • a callable signature is missing in object literal [1] but exists in OptionDescription [2] in property options.
 • property fetchPolicy is missing in OptionDescription [2] but exists in object literal [1] in property options.

     shared/graphql/queries/notification/getDirectMessageNotifications.js
 [1]  42│   options: {
      43│     fetchPolicy: 'network-only',
      44│   },
        :
     100│
     101│ export default graphql(
     102│   getDirectMessageNotificationsQuery,
     103│   getDirectMessageNotificationsOptions
     104│ );
     105│

     node_modules/react-apollo/react-apollo.umd.js.flow
 [2] 107│   options?: OptionDescription<TProps>;


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/queries/user/getCurrentUserEverythingFeed.js:71:24

Cannot get ownProps.dispatch because property dispatch is missing in undefined [1].

 [1] 36│   options: () => ({
     37│     fetchPolicy: 'cache-and-network',
     38│   }),
       :
     68│             const newThreads = parseRealtimeThreads(
     69│               prev.user.everything.edges,
     70│               updatedThread,
     71│               ownProps.dispatch
     72│             );
     73│
     74│             // Add the new notification to the data


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/queries/user/getCurrentUserEverythingFeed.js:124:3

Cannot call graphql with getCurrentUserEverythingOptions bound to operationOptions because function type [1] requires
another argument from function [2] in property options.

     shared/graphql/queries/user/getCurrentUserEverythingFeed.js
 [2]  36│   options: () => ({
      37│     fetchPolicy: 'cache-and-network',
      38│   }),
        :
     121│
     122│ export default graphql(
     123│   getCurrentUserEverythingQuery,
     124│   getCurrentUserEverythingOptions
     125│ );
     126│

     node_modules/react-apollo/react-apollo.umd.js.flow
 [1] 100│ export type OptionDescription<P> = (props: P) => QueryOpts | MutationOpts;


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/queries/user/getCurrentUserRecurringPayments.js:25:62

Cannot call graphql with object literal bound to operationOptions because:
 • property fetchPolicy is missing in OptionDescription [1] but exists in object literal [2] in property options.
 • a callable signature is missing in object literal [2] but exists in OptionDescription [1] in property options.

     shared/graphql/queries/user/getCurrentUserRecurringPayments.js
      22│   ${userRecurringPaymentsFragment}
      23│ `;
      24│
      25│ export default graphql(getCurrentUserRecurringPayemntsQuery, {
 [2]  26│   options: { fetchPolicy: 'network-only' },
      27│ });
      28│

     node_modules/react-apollo/react-apollo.umd.js.flow
 [1] 107│   options?: OptionDescription<TProps>;


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/queries/user/getCurrentUserSettings.js:29:48

Cannot call graphql with object literal bound to operationOptions because:
 • property fetchPolicy is missing in OptionDescription [1] but exists in object literal [2] in property options.
 • a callable signature is missing in object literal [2] but exists in OptionDescription [1] in property options.

     shared/graphql/queries/user/getCurrentUserSettings.js
      26│   ${userSettingsFragment}
      27│ `;
      28│
      29│ export default graphql(getCurrentUserSettings, {
 [2]  30│   options: { fetchPolicy: 'network-only' },
      31│ });
      32│

     node_modules/react-apollo/react-apollo.umd.js.flow
 [1] 107│   options?: OptionDescription<TProps>;


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/queries/user/getUser.js:72:60

Cannot call graphql with object literal bound to operationOptions because:
 • property fetchPolicy is missing in OptionDescription [1] but exists in object literal [2] in property options.
 • a callable signature is missing in object literal [2] but exists in OptionDescription [1] in property options.

     shared/graphql/queries/user/getUser.js
      69│   ${userInfoFragment}
      70│ `;
      71│
      72│ export const getCurrentUser = graphql(getCurrentUserQuery, {
 [2]  73│   options: { fetchPolicy: 'cache-first' },
      74│ });
      75│

     node_modules/react-apollo/react-apollo.umd.js.flow
 [1] 107│   options?: OptionDescription<TProps>;


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ shared/graphql/queries/user/getUserCommunityConnection.js:49:3

Cannot call graphql with object literal bound to operationOptions because:
 • property fetchPolicy is missing in OptionDescription [1] but exists in object literal [2] in property options.
 • a callable signature is missing in object literal [2] but exists in OptionDescription [1] in property options.

     shared/graphql/queries/user/getUserCommunityConnection.js
      46│
      47│ export const getCurrentUserCommunityConnection = graphql(
      48│   getCurrentUserCommunityConnectionQuery,
 [2]  49│   { options: { fetchPolicy: 'cache-and-network' } }
      50│ );
      51│
      52│ export const getUserCommunityConnection = graphql(

     node_modules/react-apollo/react-apollo.umd.js.flow
 [1] 107│   options?: OptionDescription<TProps>;



Found 49 errors

Only showing the most relevant union/intersection branches.
To see all branches, re-run Flow with --show-all-branches
</code></pre>
</details>

**Comment by mxstbr** [comment]
Oh damn, we should probably fix those! Gimme a second, I'll dig into them and see how many I can resolve.

**Comment by FezVrasta** [comment]
If you add this, they go away
```
.*/node_modules/react-apollo
.*/node_modules/dataloader
```

But these are most likely real problems that, as you said, should be fixed.

**Comment by mxstbr** [comment]
Awesome, that totally works for me. I'll dig into the remaining errors!

**Comment by mxstbr** [comment]
Still seems to fail with the original "Cannot find module `react-popper`" error for me locally with the latest changes?

**Comment by FezVrasta** [comment]
image


🤷‍♂️

**Comment by FezVrasta** [comment]
Oh I see what's happening, you have a problem in the flowconfig that I had as well in my own projects, here:

```
module.system.node.resolve_dirname=node_modules
module.system.node.resolve_dirname=spectrum
```

This should be:
```
module.system.node.resolve_dirname=node_modules
module.system.node.resolve_dirname=./spectrum
```

Source:
https://github.com/facebook/flow/issues/5180#issuecomment-341888566


**edit**: nevermind, unrelated, I can't neither find the `spectrum` folder, anyway that should be changed if you are still using it.

**Comment by mxstbr** [comment]
Oh damn, new commit very welcome ❤️

**Comment by FezVrasta** [comment]
Do you still use it or should I just get rid of that line?

**Comment by mxstbr** [comment]
No we definitely use that, we have a NODE_PATH set to the root folder to be able to import without `../../` and we use that everywhere. That line is there so flow understands those imports.

**Comment by FezVrasta** [comment]
The thing is that `module.system.node.resolve_dirname` to work must point to an existing directory, that will be added to the resolver of Flow.

I can't seem to find any `spectrum` directory in the root of the project. I'm sure I'm not seeing something...

**Comment by mxstbr** [comment]
Oh you're right, that should probably be `./`? I'm not sure why we set it to spectrum, can you try that?

**Comment by FezVrasta** [comment]
`.` it is

**Review by mxstbr — APPROVED** [review]
Amazing, thank you for digging into those Flow errors and for contributing! 💜

**Comment by FezVrasta** [comment]
You're welcome!

**Pull request merged**
