### PR TITLE
Upgrade to Cypress 3.0

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

### CODE REVIEW

**Review by mfix22 — DISMISSED** [review]

**Review by brianlovin — DISMISSED** [review]

**Comment by brianlovin** [comment]
Lol every attempt I've made to fix this merge conflict locally fails or times out. Want to give it a try @mxstbr ?

**Comment by mxstbr** [comment]
Managed to resolve locally, will admin ship this!

**Comment by brianlovin** [comment]
The tests fail/time out though on CI - maybe worth pausing on shipping this?

**Comment by brianlovin** [comment]
Replacing with #4170

**Pull request closed without merging**
