### PR TITLE
Don't double-load raven-js

### PR DESCRIPTION
**Pull request by mxstbr**
We were already loading raven via a script tag in the SSR template, but then still including the `raven-js` package in the frontend.

This fixes it by only using the global raven from the script tag.

Should definitely be tested on alpha first.

**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

### CODE REVIEW

**Review by brianlovin — DISMISSED** [review]
LGTM, will do an alpha cut this morning

**Comment by brianlovin** [comment]
Happy to ignore peril and remove console logs before prod cut

**Comment by brianlovin** [comment]
Actually @mxstbr want to just throw this up on alpha quickly to see that the context setting works, and then remove the consoles in a new commit?

**Comment by mxstbr** [comment]
Deploying to alpha now!

**Pull request merged**
