### PR TITLE
fix 「 post your first thread 」Button in emptyThreadFeed on mobile .

### PR DESCRIPTION
**Pull request by tuoxiansp**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

image

gif: https://static.ucloud.cn/23f9e2c28bda4b78b23bbbf9522a29c0.gif

### CODE REVIEW

**Review by mxstbr — APPROVED** [review]
Thank you! :100:

**Comment by mxstbr** [comment]
Also, how did you internationalize Spectrum? Is that something you are going to submit a PR for? We would love internationalize spectrum.chat properly!

**Comment by tuoxiansp** [comment]
> Also, how did you internationalize Spectrum? Is that something you are going to submit a PR for? We would love internationalize spectrum.chat properly!

Hard code . Maybe some hundred lines .  :-D

**Comment by mxstbr** [comment]
Oh 😅 I would love to find a proper solution to this so all Chinese users of spectrum.chat can benefit from your translations!

**Pull request merged**
