### PR TITLE
Fix E2E memory shortage on CircleCI 

### LINKED ISSUE #3096: All web e2e tests fail on ci
This memory error seems to be stopping all e2e tests in ci:

screenshot 2018-05-15 14 26 00

### PR DESCRIPTION
**Pull request by ryota-murakami**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

## overview

fixed https://github.com/withspectrum/spectrum/issues/3096

currently, circle ci still faild by timeout [this build](https://circleci.com/gh/withspectrum/spectrum/6514?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), but following is result of `channel profile as owner should render settings button` test, this is specific test spec issue.

```
  10) channel profile as owner should render settings button:
     CypressError: Timed out retrying: Expected to find element: '[data-cy="channel-settings-button"]', but never found it.
      at Object.cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:66781:11)
      at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:66746:18)
      at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:66773:17)
      at retry (http://localhost:3000/__cypress/runner/cypress_runner.js:60782:16)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:53285:18
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:6846:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:4868:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:4925:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:4970:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:5045:18)
      at Async._drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:1778:16)
      at Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:1788:10)
      at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:1662:14)
      at <anonymous>
```

one more thing, i runed `yarn test:2e2` for this PR investigation.
therefore cypress generated video capture.

I am glad if you can freely download from here if there is demand!
https://www.dropbox.com/s/wlj59yvi0t6admv/kctz2.mp4?dl=0

- my os environment
screen shot 2018-05-20 at 1 01 43

thanks🙏

### CODE REVIEW

**Comment by ryota-murakami** [comment]
@brianlovin @mxstbr in additional, i attempted to fix [still failing 2 tests without caused momory shartage problem](https://circleci.com/gh/withspectrum/spectrum/6514?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), 
and [this](https://circleci.com/gh/withspectrum/spectrum/6558?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) is working now.

I repplaced DB setup script, but is there any problem with this way?

**Comment by brianlovin** [comment]
Oh awesome! cc @mxstbr this look good to you? Would <3 to get CI back on track

**Review by mxstbr — APPROVED** [review]
Damn that works? Great job, thank you so much for investigating—let's ship this!!!

**Comment by mxstbr** [comment]
Oh my god, felt so good not having to admin merge :100:

**Pull request merged**
