### PR TITLE
[A11Y] - Add empty alt to Avatar component

### PR DESCRIPTION
**Pull request by AgtLucas**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

Another small PR regarding A11Y, I'm adding an empty alt attribute to the Avatar component, so assistive technologies (e.g.: screen readers) can treat the image as presentation only and skip reading the image source.

### CODE REVIEW

**Review by brianlovin — APPROVED** [review]

**Comment by brianlovin** [comment]
I'm surprised we had no yarn locks in those directories :P Thanks @AgtLucas 💜

**Comment by AgtLucas** [comment]
@brianlovin No worries! :)

Regarding the locks, that's because I used `node shared/install-dependencies.js`. :)

**Comment by Luciaisacomputer** [comment]
This looks good to me, it no longer reads out the image path in NVDA. Adding in a `<span>` with some text describing where that link goes to might add some extra context to a user. Are there any visually hidden or screen reader classes that can be used to do that?

**Comment by mxstbr** [comment]
Not yet, I'd love to have a `<VisuallyHidden />` component! Mind submitting a PR for that?

**Comment by mxstbr** [comment]
Also, thanks so much for contributing! 💜

**Pull request merged**
