### PR TITLE
Combine thread and message renderer

### LINKED ISSUE #4804: Combine thread and message renderers
As of #4797 the only real difference between the thread and message renderers is that threads have automatic embeds and support headings.

We should combine those two renderers together to 1) add automatic embeds to messages (but disable headings) and 2) add the thread link embeds from #4683 to the existing embed system for threads so both content types have the same capabilities. Ref #4802

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

**Related issues (delete if you don't know of any)**
Closes #4804 

Mostly a bit of code cleanup, side effect feature addition is that we now support automatic embeds in messages too.

Only difference between threads and messages now is that messages do not support headings:

screenshot 2019-03-06 at 14 35 18

screenshot 2019-03-06 at 14 35 24

### CODE REVIEW

**Comment by brianlovin** [comment]
This is amazing!!! We should change the blockquote styling so it feels more "inline" - eg smaller text - and this will be perfect. People are going to be so happy man, this is great.

**Comment by mxstbr** [comment]
That is what blockquotes look like right now in messages on prod, let's do that as a followup PR?

**Comment by mxstbr** [comment]
Note: What this does not do yet is move the thread embeds to the embed system, will tackle that in a follow-up PR!

**Comment by brianlovin** [comment]
> That is what blockquotes look like right now in messages on prod, let's do that as a followup PR?

Of course!

> Note: What this does not do yet is move the thread embeds to the embed system, will tackle that in a follow-up PR!

Sounds good! Is this good to merge?

**Review by brianlovin — APPROVED** [review]
🔥🔥🔥

**Pull request merged**
