### PR TITLE
Rework hyperion deployment

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

**Changes**

- Adds a hash to the `bootstrap.js` file to hopefully avoid hashes not changing correctly on new deploys
- Reworks the hyperion deployment to work like any other worker, i.e.  build locally then deploy the build folder

Hyperion is deployed like any other worker now (I have adjusted the deployment script to match):

```sh
yarn run build:hyperion
now build-hyperion
```

Either of those changes might fix our ongoing deployment issues, let's try them out!

### CODE REVIEW

**Comment by mxstbr** [comment]
Ignore the Peril failure, the console.log's in the deployment script are supposed to be there! 👍

**Comment by mxstbr** [comment]
Fixing flow...

**Comment by mxstbr** [comment]
This is ready!

**Review by brianlovin — APPROVED** [review]
This is great. I'm going to take a stab at the thread SSR loading state issue, and if I can fix that I'll do a deploy with this new script

**Pull request merged**
