### PR TITLE
use styled-components@dev

### PR DESCRIPTION
**Pull request by quantizor**
Testing out SSR and ensuring nothing broke.

**Status**
- [ ] WIP
- [ ] Ready for review
- [x] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

### CODE REVIEW

**Review by mxstbr — APPROVED** [review]
On merge this will be deployed to alpha.spectrum.chat! (takes ~20 mins for e2e tests)

**Comment by brianlovin** [comment]
Why are we switching to dev?

**Comment by mxstbr** [comment]
@probablyup reworked the build system to drop the bundle size, but isn't sure whether that broke SSR or not, so I offered to test the new version on alpha :blush: Going to sit on this a bit though seeing that the messages redesign is on alpha rn

**Comment by mxstbr** [comment]
Sorry that we never got around to this, it's unnecessary now

**Pull request closed without merging**
