### PR TITLE
🐛 Fix code block styling in quoted message

### LINKED ISSUE #3098: Fix code block styling in quotes
They don't look very nice:

screen shot 2018-05-16 at 09 16 11

### PR DESCRIPTION
**Pull request by dev-drprasad**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

Before             |  After
:-------------------------:|:-------------------------:
screen shot 2018-05-21 at 11 13 44 pm | screen shot 2018-05-21 at 11 10 06 pm
screen shot 2018-05-21 at 11 13 28 pm | screen shot 2018-05-21 at 11 10 22 pm
screen shot 2018-05-21 at 11 13 17 pm| screen shot 2018-05-21 at 11 10 45 pm
screen shot 2018-05-21 at 11 36 19 pm| screen shot 2018-05-21 at 11 35 41 pm

Fixes #3098

### CODE REVIEW

**Comment by dev-drprasad** [comment]
@brianlovin @mxstbr i have added screenshots of quoted message before and after changes. the current changes affecting both received and sent messages. i thought its looks good for sent messages also, but i need your opinion on this.

**Review by brianlovin — APPROVED** [review]

**Comment by dev-drprasad** [comment]
@brianlovin @mxstbr @uberbryn if design for sent messages looks fine, i can move to ready for review

**Comment by brianlovin** [comment]
Yeah, go ahead and do that - I think we'll wait for a final approve from @uberbryn and we can ship :)

**Comment by superbryntendo** [comment]
Text contrast is too low, otherwise good changes. If you make the contrast ratio at least 2.5 (ideally AA), we can ship it.

**Comment by dev-drprasad** [comment]
@uberbryn 
text in quoted sent message has contrast ratio ~ 2.77
text in quoted received message has contrast ratio ~ 2.73
though both are below AA level

currently we are using colours from theme `theme.brand.default` , `theme.generic.default`,  `theme.text.alt` , so i am not sure how to increase contrast, because changing theme values will affect everywhere

i am thinking of using css `filter: brightness()`. though only latest browsers support this
what do you think ?? is there any way to increase contrast ??

**Comment by brianlovin** [comment]
If those are above 2.5 let's ship them; I think we'll have to do another pass down the road and potentially add some higher contrast colors below our `text.alt` level :)

**Comment by superbryntendo** [comment]
I misread this as changing from light bg to dark bg *and* adding spacing. that light bg is much higher contrast, so maybe we should just make both bgs that color. (not high priority)

**Comment by brianlovin** [comment]
Good point @uberbryn - since they are both in a quote reply might as well be the same color

**Pull request merged**
