### PR TITLE
Add debug to deploy script to catch rate limits

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

We keep hitting rate limits while deploying; adding the debug flag should help to get info for the ZEIT team

### CODE REVIEW

**Review by mxstbr — APPROVED** [review]
Probably not high prio but it would be nice for this to be opt-in to avoid tons of logs on regular deployments!

**Comment by brianlovin** [comment]
Not quite sure how to do that @mxstbr  but one way could be just just pass any additional arguments from the command to the `now` line. Would that be better? `yarn run deploy hyperion --prod --debug` ?

**Comment by brianlovin** [comment]
Although, just for the time being we want to leave `--debug` on because ZEIT is trying to help us understand why we keep getting rate limited :)

**Comment by brianlovin** [comment]
test

**Review by mxstbr — APPROVED** [review]

**Pull request merged**
