### PR TITLE
Fix list items overflows

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [x] WIP
- [ ] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

Wow, so it turns out that it's harder than it looks to build a generic component for list items that can contain text and actions, where the text properly truncates and the number of action children is unknown. I think I've got it figured out for channels, will port a similar solution to user list items to try and fix bad wrapping on badges.

### CODE REVIEW

**Comment by brianlovin** [comment]
@mxstbr would love your feedback on https://github.com/withspectrum/spectrum/pull/3766/files#diff-5a2588d8e2fb3027a26633522f4711fa specifically.

I'm finding that the whole paradigm of being a channel member is confusing, especially when there's a separate option to toggle notifications. It seems like those should basically be the same thing, right? Either you care about the channel or you don't. I know that we had originally envisioned a user might want to join a channel to get threads in their feed, but turn off notifications to not get emails. I'm just wondering if that's a common pattern of usage at all, or if we could simplify this a lot more:

- People are members of communities
- People subscribe to channels within a community

If we like this direction, as started on that diff above, we can do a followup PR later to simplify the backend mutations for all of this.

**Comment by brianlovin** [comment]
oh, cc @mxstbr if you have feedback on the above

**Comment by mxstbr** [comment]
Yeah I like that concept a lot! Especially now that channel thread notifications aren't really a thing anymore, or at least not as much as they used to be.

I do think we shouldn't worry about changing the backend mutations, since any change we have to do backwards-compatible and it's just going to be a pita, if the UI just shows a better interface that's 100% good let's just keep the mutations as is?

**Comment by mxstbr** [comment]
This would be really useful for #2992 too 🙈

**Comment by brianlovin** [comment]
Nothing is perfect, but this is incrementally better, at least until we redo the entire profile page. So I don't want to sink more time into this as a lot of these components will change with the new profile :)

**Review by mxstbr — APPROVED** [review]
Shipit

**Pull request merged**
