### PR TITLE
Fix ESLint warn react/no-deprecated

### PR DESCRIPTION
**Pull request by ryota-murakami**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

Replace React UNSAFE lifecycle method name by [react-codemod](https://github.com/reactjs/react-codemod).
thanks😀

screen shot 2018-07-19 at 21 15 51

### CODE REVIEW

**Comment by brianlovin** [comment]
Would prefer to migrate these lifecycles to the new ones instead, if that's okay :) No rush on it, and we'll likely have to do quite a bit of testing as we work through them, but should end up in a better place when R17 comes out

**Comment by ryota-murakami** [comment]
@brianlovin Yeah, we have to migrate sooner or later!
And i think it's fine gradually migrate to prevent put pressure development resources.

Even though `UNSAFE_` prefix will be useful whether is it unsafe method or not.

I planning migrate plan as following.

- [ ] Merge PR
- [ ] List up using unsafe method components on a issue
- [ ] Migrate the components one by one, create a PR, merge safely after testing

What do you think about above😀

**Comment by brianlovin** [comment]
> What do you think about above

What do you think of just starting the migrations one by one instead?

**Comment by ryota-murakami** [comment]
@brianlovin I agree with you! can I close this PR?

**Comment by brianlovin** [comment]
Yep :)

**Pull request closed without merging**
