### PR TITLE
Add reputation information back to digest emails

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- chronos

**Related issues (delete if you don't know of any)**
Based on #2846

Reworks the reputation copy in digest emails, adds tests for it and adds the information back into the digest emails!

### CODE REVIEW

**Review by brianlovin — CHANGES_REQUESTED** [review]
I think the strings are a little too excited and energetic, I think every sentence ends with an `!` - can we tone it down just a bit?

**Comment by mxstbr** [comment]
Sure, feel free to push to your liking!

**Comment by mxstbr** [comment]
Yes that "!" was on purpose :trollface:

**Comment by mxstbr** [comment]
@brianlovin latest commit tones it down, if you're happy with this let's ship it and iterate later!

**Comment by brianlovin** [comment]
Perfect, thank you! Small nit: could you update the snapshots so future tests don't fail?

**Comment by mxstbr** [comment]
Arg forgot to update the snapshots!

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
