### PR TITLE
Enable API caching of profiles

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [x] WIP
- [ ] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api

**Related issues (delete if you don't know of any)**
Based on the Apollo Server v2 upgrades (#3855), until that's merged you'll also see those changes here.

This enables in-memory caching of API responses for all profiles (users, communities, channels,...). Depending on their sensitivity I set the caching to be between 15 and 30 minutes, and cached responses are only returned to un-signed-in users.

~~On top of that, if this works how I think it should work the Now CDN will also pick up these cache hints and cache and serve the responses from all around the world. I have to test that hypothesis first though, that part might not work, but the in-memory caching is definitely working.~~ Nevermind this doesn't work, the Now CDN does not cache POST requests. /cc @javivelasco feature requestttttt plsssss

I'd like to be able to store the cached data in Redis so we get a higher cache hit rate (since that would be shared between all instances of the API), but afaik Apollo Engine only has support for Memcached and not Redis. Will dig into that too.

### CODE REVIEW

**Review by brianlovin — APPROVED** [review]
Wow things are crazy fast locally. Going to merge and do an alpha deploy so we can do further testing.

**Comment by brianlovin** [comment]
If tests pass...

**Comment by brianlovin** [comment]
There are ~20 e2e tests that fail for me when I ran all of them locally. I'm not totally sure what's going on here, but my hunch is that caching here is breaking quite a lot or persisting things between tests when it shouldn't.

Also, if you pull this branch and create content it is very buggy. Here's an example: https://www.dropbox.com/s/f2g0gk74lrsct5b/caching-bug.mov?dl=0 - the flow of creating channels is buggy, but also it says things don't exist when they do (I open the dev tools and things appear, close dev tools and they disappear). 

Some repro steps: go to community settings, create a private channel, then from community settings try to navigate to the private channel settings. It will say the private channel does not exist.

**Review by brianlovin — CHANGES_REQUESTED** [review]
Tests are broken and locally it's hard to get things to work properly when creating things like new channels.

**Comment by mxstbr** [comment]
Oh no, Engine also returns publicly scoped cached data for signed in users. 

I thought `PRIVATE` scope would mean the data is only cached for that user, and `PUBLIC` scope (the default) would mean the data is only cached for public users—but apparently `PUBLIC` scope means the data is cached for all users.

Will see if there's a scope that does what I want here.

**Comment by mxstbr** [comment]
We've removed Engine, so this is irrelevant.

**Pull request closed without merging**
