### PR TITLE
feat(thread): implement message permalink

### PR DESCRIPTION
**Pull request by ryota-murakami**
**Status**
- [x] Ready for review

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

## overview
@mxstbr response to https://spectrum.chat/?thread=2c26c5b2-da4d-43a6-96d3-4c69ef3b2550
probably, that is not react or react-router desirable way.
first i thought take a react-router appropriate way, but i don't understand😅

but i figure out article which relative this concern.
that might be provide any help for you🙂

- https://medium.com/@gajus/making-the-anchor-links-work-in-spa-applications-618ba2c6954a
- https://github.com/ReactTraining/react-router/issues/394#issuecomment-220221604

- watch this video💻(click message -> set permalink to url area -> copy it -> access at other window)
https://youtu.be/cXEfDs6hjcw

### CODE REVIEW

**Comment by ryota-murakami** [comment]
#### note
this PR was sending to `withspectrum:selected-message-to-url` branch because this work is the one part of `Permalink to comments`.

**Comment by ryota-murakami** [comment]
ping👉

**Comment by brianlovin** [comment]
Cursory review: we need a way for people to get the url to share the link to the message in the first place. Tbh I don't know how this should be designed; our message layout isn't very great at handling many actions, and we've already put in 'reply' and 'delete' actions - adding a third might break some layouts. Will think on this.

**Comment by ryota-murakami** [comment]
@brianlovin I think the function behavior was almost decide on https://github.com/withspectrum/spectrum/pull/3093.
The draft is Sync selected message to URL, so which does not affect existing UI i guess.

**Pull request closed without merging**
