### PR TITLE
✨ Add signin link in navbar for loggedout user

### LINKED ISSUE #3481: Add signin button to logged-out navbar
Not sure when this went missing, I know for a fact we used to have that:

screen shot 2018-07-04 at 09 44 54

We should really add it back, right now it's really hard to sign in from some views.

### PR DESCRIPTION
**Pull request by dev-drprasad**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

**Related issues (delete if you don't know of any)**
Closes #3481

screen shot 2018-07-10 at 11 24 04 pm
screen shot 2018-07-10 at 11 24 29 pm
In mobile, "signin" link is hidden. is it fine 🤔 ??

### CODE REVIEW

**Comment by dev-drprasad** [comment]
@mxstbr any blockers ??

**Comment by brianlovin** [comment]
@dev-drprasad we should probably have sign in on mobile, but I'm not sure what icon makes sense in the tab bar. To be honest, the signed out tab bar is a weird experience anyways. The smallest iteration to ship this would be to keep the desktop sign in link but remove the grid gap on the mobile tab bar.

**Review by mxstbr — APPROVED** [review]
This is great, I love it! Thanks so much for digging into this, shipping :100:

**Comment by mxstbr** [comment]
> we should probably have sign in on mobile, but I'm not sure what icon makes sense in the tab bar

The way @dev-drprasad built it looks fine to me as a first iteration, honestly. Let's just ship this and then iterate later:

screen shot 2018-08-06 at 13 30 50

**Pull request merged**
