### PR TITLE
Install Cosmos with some sample fixtures

### PR DESCRIPTION
**Pull request by ovidiuch**
**Status**
- [x] WIP
- [x] Ready for review
- [x] Needs testing

Per [@mxstbr's tweet](https://twitter.com/mxstbr/status/983970245487611904), here is a sample Cosmos integration into the Spectrum codebase.

Just run `yarn` (install) and `yarn cosmos`, and you'll see this,

cosmos-spectrum2

A few notes:
- `cosmos.proxies.js` is basically a provider config which gets applied to all components when loaded in isolation. Although some proxies require _activation_, like the Redux proxy, which only gets activated when the fixture contains `reduxState` (use `{}` to use default reducer state).
- I only included a proxy for ThemeProvider (required by Button) and ReduxProvider (required by Badge). Based on your index file you have another three providers that would eventually need proxies configured for. Cosmos has core proxies for ReactRouter and Apollo, and HelmetProvider seems very basic so the remaining config should be trivial.
- You can see that Redux is fully functional when clicking on the _logged in_ badge by watching the Redux dev tools in the gif.
- I wanted to write a few tests on top of these fixtures as well (eg. to test that clicking on the logged in Badge populates `modals.modalProps.user` with `users.currentUser`), but it seems like I need to config the databases before I can run Jest so I wanted to get feedback before investing more time.

What do you think?

### CODE REVIEW

**Review by mxstbr — COMMENTED** [review]
As a general note, the goal of a tool like this in my mind should be to help us solidify our component lib for the frontend, which at the moment is mostly "Components everywhere!!11!!". Cosmos looks very neat and similar to where Nik and I wanted to take Carte Blanche (albeit more manual :wink:) Some questions:

- Does cosmos let me document components in markdown? (like styleguidist)
- Does cosmos work with ReactNative?
- How easy is it to write tests based on the Cosmos fixtures? That would be a killer feature when compared to styleguidist/storybook, who have custom APIs that don't let one reuse the same fixtures for testing easily.

**Comment by brianlovin** [comment]
First of all, this is really awesome. Getting running was super easy. I echo Max's comments, especially regarding running tests against these.

I have a couple other observations/questions as well - pardon my ignorance here on these, as I'm new to Cosmos and may be missing something obvious :)

1. I noticed Firefox rendering buttons with this weird half outline in Firefox:
screenshot 2018-04-11 08 46 59

Buttons don't show up that way in-app on Firefox, nor do they have that border issue on Chrome. So I'm just curious if this could be related to Cosmos in some way?


2. What's your recommendation on using Cosmos in a day to day workflow? i.e. is it just a visual inspector? Can I copy a component code with the test props applied so I can paste it directly into my code? Can it help warn us if fixture props become out of sync with the component props as a developer is working within a component file?

**Comment by mxstbr** [comment]
> Can it help warn us if fixture props become out of sync with the component props as a developer is working within a component file?

I think ideally for us it'd integrate with Flow, right?

**Comment by superbryntendo** [comment]
@brianlovin that half outline is webkit-appearance: button-face. it probably doesn't account for our reset that clears that?

**Comment by ovidiuch** [comment]
Great questions! I'll answer one by one.

> Does cosmos let me document components in markdown? (like styleguidist)

No

> Does cosmos work with ReactNative?

No. But it's a high priority feature. If you decide to use Cosmos and are working on your RN app, it would be an extra boost to make React Cosmos Native happen. I know some people ported it a while ago, and some are writing headless tests using Cosmos fixtures for RN components, but I need to take a deep dive for a complete integration.

> How easy is it to write tests based on the Cosmos fixtures? That would be a killer feature when compared to styleguidist/storybook, who have custom APIs that don't let one reuse the same fixtures for testing easily.

Surely I'm subjective, but I'd say *easy*! If you're interested, let me know which components you'd like to see tested, and I can do the whole Spectrum repo setup (hopefully it's not complicated) and I'll write some demo tests for you.

> I noticed Firefox rendering buttons with this weird half outline in Firefox:

That's because the CSS reset file wasn't included by Cosmos. I added it to `config.globalImports` and it looks better now

image

> What's your recommendation on using Cosmos in a day to day workflow? i.e. is it just a visual inspector?

More than a visual inspector. Here are some use cases:
- Component design. Write one or more fixtures to describe wanted component API, potentially before implementation. Similar to writing db schema before creating something on the backend.
- TDD. Ties in into previous point. Write fixtures and add some assertions on top of them. Then write implementation. Order is not so important as TDD is not so useful in exploratory development, but it's always useful to have a clear API definition (fixture) as you're developing
- "State bookmarks". Notice that a component behaves wierdly with a given data sample? Maybe a list with many items, an item with a long title, etc. Create a fixture and you can always go back to that scenario, even if you don't have time to address it then. Either visually, or by writing a regression test. Because fixtures work with plugins. The state "bookmark" can be defined by props, local state, Redux state, an API response, etc.
- Isolated dev environment. Want to work on a form that is only visible on page X under some modal triggered by button Y, no need to load the entire app and manually navigate there. Especially useful when working on a module that isn't represented by a URL. Just pop up that component and ignore the rest.
- Isolated dev environment (2). Think your component is reusable? Maybe it depends on a parent component creating some weird context stuff, or some cousin component massaging some global state. Load it in Cosmos and you'll know how reusable a component is :)
- Onboarding. Navigating a new codebase is pretty terrifying. The Cosmos UI requires no server or db to set up, works as soon as you have npm modules installed, and reveals _a lot_ about a codebase to newcomers.
- Design & develop interop. Want to build a new feature and reuse as much of the existing components? No problem. Fire up Cosmos for a spin and quickly discover which primitives you have at your disposal. The fact that you have each component's prop/state/etc input requirements makes it even better.
- ... there's probably more but these are the first that came to mind

> Can I copy a component code with the test props applied so I can paste it directly into my code?

Not really. If components only relied on props, that'd be easy. The fixture would make more sense as JSX and you'd just copy that. In reality, though, components depend on much more (eg. logged in Redux state). So it's hard to "copy paste" a component's input, as it's not always explicit props that you can put inside a render method of a parent component.

But it's a good question and for many simple components it would make sense to just say "I want this fixture here (render method of another component)". Something to think about.

> Can it help warn us if fixture props become out of sync with the component props as a developer is working within a component file?

YES. Still a bit experimental, but I added Flow support to the Button fixtures and this is how it looks like:

cosmos-spectrum-typesafe

Note that I reverted this commit because the Cosmos build stopped working. Reason: `react-cosmos-flow` package contains Flow types so needs to be Babal-parsed. Since it's inside `node_modules` the CRA webpack config doesn't include it in the list of files to compile for `babel-loader`. Any idea to fix this is welcome!

Two possible workarounds:
- Copy the `createFixture` helper in the codebase. [It's only a few lines of code](https://github.com/react-cosmos/react-cosmos/blob/faacf7efb60e9d40a2fa95c884b0e77fd0b93cce/packages/react-cosmos-flow/fixture.js)
- Tweak the webpack config to parse `react-cosmos-flow`. The [default webpack config generated by Cosmos does out of the box](https://github.com/react-cosmos/react-cosmos/blob/faacf7efb60e9d40a2fa95c884b0e77fd0b93cce/packages/react-cosmos/src/server/default-webpack-config.js#L25-L32)

---

Hope this answer your questions. Looking forward to hear more thoughts!

**Comment by brianlovin** [comment]
@skidding thanks so much for this thorough reply - overall those points make a ton of sense and this seems like a huge win for us. It would be a bonus if we can get flow typings figured out on top of our fixtures, but I understand that will take a bit more work and could be a separate PR. One place to look would be in `config-overrides.js` in the root directory; we run that with `create-react-app-rewired` to get around CRAs parsing rules.

I'm going to approve and get this into the codebase; realizing how few fixtures we could write at this point is telling me we don't have that strong of a reusable component system yet :)

**Review by brianlovin — DISMISSED** [review]

**Comment by brianlovin** [comment]
@skidding would you mind giving that a quick re-yarn to fix any merge conflicts then we'll ship this in?

**Comment by ovidiuch** [comment]
> @skidding thanks so much for this thorough reply - overall those points make a ton of sense and this seems like a huge win for us.

With pleasure!

> It would be a bonus if we can get flow typings figured out on top of our fixtures, but I understand that will take a bit more work and could be a separate PR. One place to look would be in config-overrides.js in the root directory; we run that with create-react-app-rewired to get around CRAs parsing rules.

Thanks for the pointer. We can probably add `/react-cosmos-flow/` [here](https://github.com/withspectrum/spectrum/blob/bbd9f81d0a9cc8c629a929bda50e9714ba3745a9/config-overrides.js#L66). But it's a good idea to leave this for a subsequent PR. I'll take this opportunity to think of a better way for Cosmos to pick up the overridden webpack config, as right now it's using the raw CRA one without the customizations from `config-overrides.js`. 

> I'm going to approve and get this into the codebase;

Great!

>  realizing how few fixtures we could write at this point is telling me we don't have that strong of a reusable component system yet :)

Hmm, when you have some time I'd like to hear more about the components you think are hard to mock / write fixtures for...

> @skidding would you mind giving that a quick re-yarn to fix any merge conflicts then we'll ship this in?

Done.

**Comment by mxstbr** [comment]
Also, we'd love love love ReactNative support!

**Comment by ovidiuch** [comment]
@mxstbr yes! 2018 coming soon in a theater near you!

@brianlovin anything else I can do to get this merged? 

Already working on an elegant way to integrate with Flow in next PR 👌

**Comment by mxstbr** [comment]
> If you're interested, let me know which components you'd like to see tested, and I can do the whole Spectrum repo setup (hopefully it's not complicated) and I'll write some demo tests for you.

I'd love to see how this looks :blush: Any chance you could add some demo tests for either of the already integrated components?

**Comment by ovidiuch** [comment]
> I'd love to see how this looks 😊 Any chance you could add some demo tests for either of the already integrated components?

Sure thing. I'll submit some demo tests and the Flow integration later this week. I'm curious to see how they all fit in the Spectrum codebase and what other testing opportunities we discover!

**Comment by brianlovin** [comment]
Closing, but will use this for reference if we ever come back to explore Cosmos :)

**Pull request closed without merging**
