### PR TITLE
Higher res cover photos

### LINKED ISSUE #4685: Send higher quality cover photos to large screens
This should be doable with imgix I think: https://spectrum.chat/spectrum/general/header-image-low-quality~b51bd603-c78d-4a40-a8c9-ba108443ccc4

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

@mxstbr this should close #4685 - I'm not going to spend a lot of time with dynamic sizing and media queries, this feels like a lower pri ship and this is the quickest win. Note that I've set profile views to have a max-width of 1280px which is our cover photo size. We should have done this a long time ago anyways to not have such a weird stretched experience for people on wide screens 😅

### CODE REVIEW

**Comment by brianlovin** [comment]
Note that I also changed some settings in our imgix source profile. Specifically, we were compressing *every* image by default that imgix served. I've removed that and added the `auto: 'compress'` to profile photos so that those can be compressed, but cover photos won't be.

**Review by mxstbr — APPROVED** [review]
I like quick fixes and I cannot lie

Are we sure we do not want to compress cover photos? It seems like we might send people 50MB images if they upload them... If we compress them with that specific size, won't they look good?

**Comment by brianlovin** [comment]
> Are we sure we do not want to compress cover photos? It seems like we might send people 50MB images if they upload them... If we compress them with that specific size, won't they look good?

Imgix already saves a ton of data down the wire with the size options, so we're never sending a full-size image. Also we cap image upload sizes during upload, which is still a generous limit but nothing crazy like 50mb.

**Comment by brianlovin** [comment]
I tested locally to prove this: I uploaded a 1mb cover photo. With the resizing parameters provided to imgix, the final file delivered to the client is 284kb. That's still fairly large, so I tested with the compression flag and it brings it down to 30kb, but dramatically degrades the quality.

**Comment by brianlovin** [comment]
> the final file delivered to the client is 284kb

Note, of course, that this gets cached - so big files will only download once

**Comment by brianlovin** [comment]
`test_web` failure is just a flakey run. Will re-run workflow.

**Comment by brianlovin** [comment]
Going to merge this for now @mxstbr - not perfect, but incrementally correct™

**Pull request merged**
