### PR TITLE
Frontend bundle size improvements

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

----

The main goal of this PR is to improve the size of our main JS bundle for the frontend by doing more efficient code splitting, removing rogue modules that we don't need to ship and enabling more sophisticated webpack options. **Each commit adds a relevant optimization, so the best way to review this would be to go commit-by-commit.**

Some big todos I'd like to tackle, we'll see if I get to all of them:

- [x] Thread bundle
- [x] RichTextEditor bundle
- [x] Commons chunk
- [ ] ~~Figure out how to properly code-split icons so we don't ship all of them all the time~~
- [ ] ~~Figure out how to get DraftJS + ImmutableJS out of the main bundle~~

| Bundle | Before | After |
| ------ | ------ | ----- |
| **Total** | 611.39 KB | 588.4 KB |
| main.js | 450.45 KB | 380.25 KB |
| commons.chunk.js | | 40.3 KB |
| Splash.chunk.js | 21.85 KB | 21.63 KB |
| communitySettings.chunk.js | 19.79 KB | 18.5 KB |
| Thread.chunk.js | | 17.33 KB |
| DirectMessages.chunk.js | 8.72 KB | 16.32 KB |
| Dashboard.chunk.js | 16.04 KB | 13.71 KB |
| ChannelView.chunk.js | 17.59 KB | 11.14 KB |
| NewCommunity.chunk.js | 11.53 KB | 11.04 KB |
| CommunityView.chunk.js | 16.23 KB | 9.83 KB |
| Search.chunk.js | 11.19 KB | 9.34 KB |
| RichTextEditor.chunk.js | | 9.12 KB |
| UserSettings.chunk.js | 8.37 KB | 7.88 KB |
| channelSettings.chunk.js | 9.45 KB | 7.42 KB |
| Explore.chunk.js | 6.6 KB | 6.39 KB |
| UserView.chunk.js | 9.92 KB | 4.47 KB |
| Notifications.chunk.js | 2.3 KB | 2.3 KB |
| bootstrap.js | 1.04 KB | 1.09 KB |
| Error.chunk.js | 336 B | 336 B |

### CODE REVIEW

**Comment by mxstbr** [comment]
@jamiebuilds roast me

screen shot 2018-04-27 at 11 23 06

**Review by brianlovin — DISMISSED** [review]
AFAICT this looks good and works locally! We'll get this on alpha for a few days though before prod cut to be sure :)

**Comment by brianlovin** [comment]
There were a ton of e2e failures; going to re-run now to see if they are related or random :)

**Review by brianlovin — CHANGES_REQUESTED** [review]
Failing tests

**Comment by brianlovin** [comment]
screenshot 2018-04-27 08 01 49

Looks like some of the e2e failures are legit - if you run the `action_bar_spec` you'll see this one right away

**Comment by brianlovin** [comment]
@mxstbr I'm guessing to code split the icons, we'd just have to do a big refactor like:

```
src/
  components/
    icons/
      index.js // containers wrapping functions for svg, coloring, tooltips, etc
      iconA.js // contains an individual glyph svg, like SettingsIcon.js
```

and then in files instead of doing:
```
import Icon from 'src/components/icons'

...
<Icon glyph={'foo'} size={32} />
...
```
we'd do
```
import FooIcon from 'src/components/icons/FooIcon`
...
<FooIcon size={32} />
...
```

Right? Or is there a better way?

That should be a separate PR either way because it'd touch so many files.

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
