### PR TITLE
Support hyperlinks in messages

### PR DESCRIPTION
**Pull request by Chiamaka**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

preview

### CODE REVIEW

**Comment by Chiamaka** [comment]
Fix for #4541

**Comment by brianlovin** [comment]
!! This is awesome! Gonna have @mxstbr take a look :)

**Review by mxstbr — APPROVED** [review]
Oh wow @Chiamaka I should have checked my notifications first, look at this: #4549!!!!

Thank you so much, this is a better than my implementation. Great job! :100:

**Comment by Chiamaka** [comment]
@mxstbr you are way too nice. It's basically the same lol

**Comment by mxstbr** [comment]
I was lazy and did not add proper types in my PR, you did! 😊 Thanks for the contribution

**Pull request merged**
