### PR TITLE
Set up GraphQL response caching

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api

**Todo**

- [x] Upgrade to Apollo server alpha
- [x] Set up Apollo Server Cache Control
- [x] Set up the full response caching plugin
- [x] Set up caching in Redis
- [x] Add `@cacheControl` directives throughout the schema

The most important bit for review here (as soon as its done) will be to make sure we set `scope: PRIVATE` for all fields that are either private (e.g. `User.email`) or adjusted depending on who views them (e.g. `Community.threadConnection`), and to set `maxAge: 0` to any fields we do not want to cache at all.

### CODE REVIEW

**Comment by mxstbr** [comment]
@brianlovin this is ready for a review!

**Comment by brianlovin** [comment]
Every e2e test is failing :/ @mxstbr

**Comment by mxstbr** [comment]
Hmm, the e2e test failures seem pretty random. I wonder what's going on with them...

**Comment by brianlovin** [comment]
@mxstbr looks like it is never able to access a signed-in view . see https://dashboard.cypress.io/#/projects/6a92uk/runs/3641/specs

**Comment by mxstbr** [comment]
I can repro, working on it.

**Comment by brianlovin** [comment]
Based on the new failures it seems like caching issues during mutations?

**Comment by mxstbr** [comment]
Not necessarily it's just stale cached data that's returned even for logged-in users... Have to figure out why cached data is returned for logged-in users!

**Comment by mxstbr** [comment]
Latest commit fixes it hopefully 🤞 by only reading and writing to the cache if there is an authenticated user. That way, only public data will ever be cached, allowing us to remove all `scope: PRIVATE` declarations for now and just caching all the things!

**Comment by brianlovin** [comment]
E2E passes! Amazing! Great work @mxstbr

**Comment by brianlovin** [comment]
Should we cache `messageConnection`s? Right now signed out users don't see new messages in threads

Edit: i guess the cache time isn't that long actually, so maybe not a big deal

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
