### PR TITLE
Update blacklist with routes currently in use

### PR DESCRIPTION
**Pull request by datio**
**Status**
- [ ] WIP
- [X] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)
- athena
- vulcan
- mercury
- hermes
- chronos
- mobile

### CODE REVIEW

**Comment by brianlovin** [comment]
Some of the ones added there just map to component names, not routes. Maybe we can safely remove:
- channelsettings
- channelview
- communityloginview
- communitysettings
- communityview
- directmessages
- errorfallback
- newcommunity
- userssettings
- userview

All the other additions are good catches, especially `thread` !!! 

Can we also add:
- user
- users
- settings
- code-of-conduct
- features

Thanks @datio :D

**Comment by datio** [comment]
**Status**
- [ ] WIP
- [X] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)
- athena
- vulcan
- mercury
- hermes
- chronos
- mobile

**Review by mxstbr — APPROVED** [review]
Awesome, thank you! :heart:

**Comment by brianlovin** [comment]
Thanks so much @datio :)

**Pull request merged**
