### PR TITLE
Rework athena buffering

### LINKED ISSUE #2471: Athena scaling breaks message notification batching

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- athena

Closes #2471 once done, see that issue for more information. This is based on #2710.

### CODE REVIEW

**Comment by mxstbr** [comment]
This almost works, except for bull not replacing jobs with the same jobId, instead dropping new additions with the same jobId. Trying to figure out how to work around that.

**Comment by mxstbr** [comment]
This works as far as I can tell!!! 😍 @brianlovin mind giving this a good review and test locally? This'd be great to ship so we can start scaling athena to multiple instances again.

**Review by brianlovin — DISMISSED** [review]

**Comment by brianlovin** [comment]
This works for me locally, properly buffering the notifications up. Let's see how this fares on athena with scaling rules!

**Comment by brianlovin** [comment]
Ah, looks like you have one more flow error. Try adding the type def at the callsite, ref https://github.com/facebook/flow/issues/5294

**Comment by mxstbr** [comment]
Fixed that error and did some more code cleanup, this is ready to ship!

**Review by brianlovin — APPROVED** [review]
LGTM - are you cool to ship this and test that notifs are working with the new buffering after scaling?

**Comment by mxstbr** [comment]
Yeah I will!

**Pull request merged**
