### PR TITLE
fix upload images tooltip hover state

### LINKED ISSUE #3113: [thread message] image upload hover effect was cut off
**Issue Type (check one)**

- [x] Bug Report

**Description (type any text below)** 

**screen shot**🙂

img

### PR DESCRIPTION
**Pull request by alejandronanez**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

**Release notes for users (delete if codebase-only change)**
- Fix hover state when the user hovers on the `Upload Image` icon

Closes #3113 

## Before
before

## After
hover-upload-button

### CODE REVIEW

**Comment by ryota-murakami** [comment]
@alejandronanez wow, this is i opened issue, thank you so much!

**Review by mxstbr — COMMENTED** [review]
Yeah that makes sense to me, but I don't know if that wasn't there to fix some other bug. Mind doing a git blame to make sure we aren't breaking anything else by removing this?

**Comment by alejandronanez** [comment]
@mxstbr you’re right. Will check and let you know 👌🏼

**Review by brianlovin — APPROVED** [review]

**Comment by brianlovin** [comment]
This is working great as far as I can test!

**Pull request merged**
