### PR TITLE
Media type and file size server validation

### PR DESCRIPTION
**Pull request by yuanchenxi95**
**Status**
- [ ] WIP
- [x] Ready for review
- [x] Needs testing

**Deploy after merge**
- api

### CODE REVIEW

**Comment by yuanchenxi95** [comment]
@brianlovin @mxstbr
Issue: [Prevent zip file uploads](https://github.com/withspectrum/spectrum/issues/2494)
Hello,

I have finished adding the media type validation on server side. The server now checks the mimetype of the file before upload it to s3. It will throw a new error if the mimetype is not in the list ['image/gif', 'image/jpeg', 'image/png', 'video/mp4'] which is corresponding to the frontend [mediaUploader](https://github.com/withspectrum/spectrum/blob/alpha/src/components/chatInput/components/mediaUploader.js#L104) component accept files.

The files below are modified to catch the error and to convert the error to a UserError:
addMessage.js
createDirectMessageThread.js
editThread.js
publishThread.js

The files below use uploadImage() method, but they originally do not have a catch statement as uploadImage throws an error if it fails to upload the file to s3:
community.js
user.js

**Comment by brianlovin** [comment]
> The files below use uploadImage() method, but they originally do not have a catch statement as uploadImage throws an error if it fails to upload the file to s3:

Hey @yuanchenxi95  this is all looking amazing! Could you clarify what you mean here? And which `community.js` and `user.js` files are you referring to?

**Comment by yuanchenxi95** [comment]
[community.js](https://github.com/withspectrum/spectrum/blob/alpha/api/models/community.js#L202)
[user.js](https://github.com/withspectrum/spectrum/blob/alpha/api/models/user.js#L282)
It seems that both models use uploadImage() method, but they do not try to catch the error thrown out by uploadImage(). Method [uploadImage()](https://github.com/withspectrum/spectrum/blob/alpha/api/utils/s3.js#L71) will throw an error if it fails to upload the file to s3.
```javascript
export const uploadImage = async (
  file: FileUpload,
  entity: EntityTypes,
  id: string
): Promise<string> => {
  return await upload(file, entity, id).catch(err => {
    throw new Error(err);
  });
};
```

**Comment by brianlovin** [comment]
Thanks for the clarification @yuanchenxi95  - first of all, I'm so sorry for how bad that code is in community.js and user.js - some of the earliest stuff we wrote, and woof, it's hard to read XD

Anyways, do you think it would be okay to just try/catch the uploadFile calls in those two files? If an error happens at that stage, the user and community will be unaffected based on the initial edits, and the only thing that will fail is applying the new profile/cover photos, which the user will receive an error for and can retry.

**Comment by mxstbr** [comment]
Oopsie, looks like I messed up the merge here somehow! One second...

**Review by mxstbr — DISMISSED** [review]
I went ahead and added those catch blocks, this LGTM—thank you so much for contributing!

**Comment by yuanchenxi95** [comment]
I am so sorry. I am having a busy week. I was planning to add those catch block this weekend.

**Comment by mxstbr** [comment]
Oh no worries at all @yuanchenxi95, I didn't do anything 😅 This is all your work, I just unblocked us from merging it!

Thanks so much for your contribution 💜

**Review by brianlovin — DISMISSED** [review]

**Comment by brianlovin** [comment]
Hmm @mxstbr - in your changes, I don't think we'll get notified on sentry about upload failures in your catches, right?

**Comment by mxstbr** [comment]
No we wouldn't be—I figured we wouldn't want to be if somebody uploads an invalid file?

**Comment by brianlovin** [comment]
I think it might be worth getting notified about invalid files just in case we notice they were able to bypass our client restrictions in some way, or S3 reported an error during upload

**Comment by brianlovin** [comment]
@mxstbr do you have any thoughts on if we should get sentry reports for invalid files or not?

**Comment by brianlovin** [comment]
@yuanchenxi95 only thing left here is:
- we have a merge conflict, I think because of https://github.com/withspectrum/spectrum/pull/2928
- can we report errors to sentry for invalid files, just so we can start learning about what people are trying so we cane improve our validation checks

**Comment by yuanchenxi95** [comment]
I solved the merge conflict. 
I am not sure how to use sentry. Not sure how to report errors using sentry. Sorry.

**Comment by johnnynotsolucky** [comment]
@yuanchenxi95 you can call `Raven.captureException(err)` directly from your code:

```javascript
import Raven from 'shared/raven'

...

const myError = new Error('foobar');
Raven.captureException(myError);
throw myError;
```

**Comment by yuanchenxi95** [comment]
@brianlovin Hi, I added the raven catcher to s3.js. The code will report to raven before it throws the error. Thanks for @johnnynotsolucky's help.

**Comment by brianlovin** [comment]
@yuanchenxi95 thanks so much (+ @johnnynotsolucky for the raven support here!)

I'll have this on alpha.spectrum.chat shortly so we can have a few days of real world testing with image uploads 😁

**Review by brianlovin — APPROVED** [review]

**Pull request merged**
