### PR TITLE
Image signing

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [x] WIP
- [ ] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- api
- hyperion (frontend)

### CODE REVIEW

**Comment by brianlovin** [comment]
Investigating why e2e are mostly failing...

**Comment by brianlovin** [comment]
Somehow something in this PR is causing an infinite loop to be triggered on channel settings views. I'm at a loss for why, but will figure this out tomorrow when I have more energy .

**Comment by brianlovin** [comment]
Ah, I figured it out. ccing @mxstbr for some brain juice on this. The problem is that when we sign image urls we are attaching an expiration timestamp. If that expiration timestamp changes during the same request, it blows up Apollo and causes infinite refetches.

Seems like the solution to this will be to have a single expiration time *per request* that gets set on *all* resolved images...perhaps this could be achieved by setting an `imageExpirationTime` field in `context` - would that make sense to you?

**Comment by brianlovin** [comment]
> Seems like the solution to this will be to have a single expiration time per request that gets set on all resolved images...perhaps this could be achieved by setting an imageExpirationTime field in context - would that make sense to you?

Ugh, I tried this but it still breaks because of Apollo's caching mechanism detecting changes *between* api requests and infinitely reloading.

Next thing to try would be futzing with Apollo's caching options to ignore `profilePhoto` and `coverPhoto` field changes...not sure about this.

**Comment by brianlovin** [comment]
Uhhhh...it's entirely possible that this breaks SSR entirely, as well. Shit.

**Review by mxstbr — APPROVED** [review]

**Review by mxstbr — DISMISSED** [review]

**Review by mxstbr — DISMISSED** [review]

**Review by mxstbr — APPROVED** [review]
YAS

**Comment by brianlovin** [comment]
Finally lol

**Pull request merged**
