### PR TITLE
Maybe fix mobile infinite loop

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [ ] Ready for review
- [x] Needs testing

### CODE REVIEW

**Comment by mxstbr** [comment]
For some reason infinite scrolling doesn't work anymore, but as far as I can tell it also wasn't working before this patch 🤔 @brianlovin any potential clues why?

**Comment by brianlovin** [comment]
@mxstbr thread feeds still fail to paginate on this branch for me :/

**Comment by brianlovin** [comment]
I do not have any clues why, but I used to be able to paginate thread feeds so we broke something in some recent pull requests. Will look into it today, too

**Comment by brianlovin** [comment]
Hoookay spent a long time digging in here. I think I broke something along the way, mainly found this by checking out commit 1b850fd6f63e320dd4812ad0a432f1ffe3346e22 (from https://github.com/withspectrum/spectrum/pull/3156/commits/1b850fd6f63e320dd4812ad0a432f1ffe3346e22) and at this commit the infinite scroll works just fine

Additionally, infinite scroll works just fine in the notifications view, which tells me that it's the `ThreadItem` component itself that is bugging out not the list itself. Will figure out where I broke things along the way.

**Comment by brianlovin** [comment]
Something in here broke it: https://github.com/withspectrum/spectrum/pull/3156/commits/f20dbf586c699a53742453af8132b9af34185b57

**Comment by mxstbr** [comment]
@brianlovin do we still need this after #3261? Probably not, right?

**Comment by brianlovin** [comment]
Nope, sorry for not clarifying. This isn't needed anymore.

**Pull request closed without merging**
