### PR TITLE
[Mobile] Tab navigation styling

### PR DESCRIPTION
**Pull request by ArturKlajnerok**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

Updated tabs styling to mach the mobile web style:
screen shot 2018-05-01 at 8 50 27 pm

- [x] Explore, Home, Message, Notification & Profile SVG Icons for tabs
- [x] Bold tab label
- [x] Enabled swipe between tabs (disabled after feedback review)

**Before:**
screen shot 2018-05-01 at 8 55 44 pm

**After :**
screen shot 2018-05-01 at 8 53 02 pm

Parent Issue: #1803

### CODE REVIEW

**Review by mxstbr — COMMENTED** [review]
Yess, this is great! :tada:

I don't think we should go with swipe-between-tabs—it's only expected on Android (no app supports it on iOS), and even there it's only expected for top navs,not bottom navs. I'd vote we keep it disabled?

**Comment by ArturKlajnerok** [comment]
Tabs swipe is quite useful, but it's true that it's not common on iOS. We could also enable it on Android and disable on iOS, let me know what you think about that? For now I've changed it back here  : 29073b9

**Review by mxstbr — APPROVED** [review]

**Comment by mxstbr** [comment]
@orta huh this is interesting, it seems like `pull_request.synchronize` also runs on merge/close events, so it's not quite a replacement for Danger ootb 🤔 Maybe I need to manually filter to not include those events somehow?

**Comment by orta** [comment]
I think this might be common enough to warrant a new key type

**Comment by mxstbr** [comment]
Yeah I feel like if Peril is meant to replace Danger, it'd be neat to be able to do

```JS
{
  "pull_request.opened": "dangerfile.js",
  "pull_request.edited": "dangerfile.js",
  "pull_request.pushed": "dangerfile.js"
}
```

or something

**Comment by orta** [comment]
Maybe 

```json
{
  "pr": "dangerfile.js",
}
```

Because that notes a strong difference between `pr` and `pull_request.*`, where pr is a special case in comparison to the others.

**Pull request merged**
