### PR TITLE
E2E Tests for Inbox view

### PR DESCRIPTION
**Pull request by tadasant**
Five tests, as per #1804:
- [X] Infinite scrolling threads list
- [X] Filtering by community in the sidebar
- [X] Filtering by channel within a community in the sidebar
- [X] Sidebar has link to the community when filtered by a community
- [X] Sidebar has link to community settings when filtered by a community and owner or moderator of the community

This is my first try at Cypress -- let me know if I'm doing anything fundamentally awful :) And all feedback super welcome.

Some assumptions I made (if any of these aren't true or might not be true in the future, tests are brittle):
* The threads a user can see in their inbox are all those that are attached to a community which s/he is a member of && are isPublished (no other conditions)
* Infinite scroll results in x2 and x3 number of initial threads on two scrolldowns
* The anchor tag on a community filter will always have an href of the form `/<community slug>`
* The anchor tag on a clickable thread will have an href that contains a `t` search parameter with value equal to the thread ID
* `General` channels are safe to hardcode as ~having that name~ **having a `general` slug**

Notes:
* I tried to use a different user for the admin vs. non-admin test suites, but looked like I was getting some undefined GraphQL server-side error when trying to access the `/` route with `BRIAN_ID`. Looked like a rabbit hole so didn't investigate, but happy to take a look again if that sounds weird

**Status**
- [ ] WIP
- [X] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
N/A

**Related issues (delete if you don't know any existing issue(s) that could be related to this PR)**

Progress on #1804

### CODE REVIEW

**Comment by brianlovin** [comment]
> General channels are safe to hardcode as having that name

People can change the name of the general channel, they just can't change the slug. So I don't think this is a safe assumption.

> I tried to use a different user for the admin vs. non-admin test suites, but looked like I was getting some undefined GraphQL server-side error when trying to access the / route with BRIAN_ID. Looked like a rabbit hole so didn't investigate, but happy to take a look again if that sounds weird

Not totally sure about this - what admin vs non admin test suites do you mean?

Other assumptions look good so far, will look at the code in a bit!

**Comment by tadasant** [comment]
CI build had failed, looks like only due to Jest snapshots (I added 20 mock threads and didn't update the snapshots) -- [fixed and pushed](https://github.com/withspectrum/spectrum/pull/3229/commits/2842fe67e3afcf63e8c78c622d775fc135ca8c9d).

> People can change the name of the general channel, they just can't change the slug. So I don't think this is a safe assumption.

Makes sense! Pushed [a fix](https://github.com/withspectrum/spectrum/pull/3229/commits/e65d90cd0d7f2086441eb8bd379fb4d0bc74255d) so that we rely on `.slug === 'general'` instead of `.name === 'General'`. I want this filter there because general channels' labels are hidden, and harder to rely on them to identify an unfiltered thread. 

> Not totally sure about this - what admin vs non admin test suites do you mean?

I'm referring to the two suites I added, `describe('Inbox view' ...)` and `describe('Inbox view, when logged in as owner of a community' ...)`. My intent was to use a user that was not an owner/admin of a community for the first one, and use the admin/owner only for the second, but ended up using the admin/owner for both.

Some more color on the issue as I recall it: inbox was showing as "you have no threads" despite the `BRIAN_ID` user clearly having communities and threads in the mock data. Looking at the network requests, seemed as if there was an unhelpful GraphQL error on the `/api` call where it should have received the threads.

**Comment by brianlovin** [comment]
> Some more color on the issue as I recall it: inbox was showing as "you have no threads" despite the BRIAN_ID user clearly having communities and threads in the mock data. Looking at the network requests, seemed as if there was an unhelpful GraphQL error on the /api call where it should have received the threads.

I'll pull this branch and see if I can repro!

**Comment by tadasant** [comment]
Rebase didn't work - moved to WIP, will look into the fixes later

@brianlovin I spent some trying to figure out that server side GraphQL error. Didn't quite get to the bottom of it 😞 Here's what I found:

The error occurs when calling `/api` with the `getEverythingThreads` query, only when auth'd with `BRIAND_ID` (ID 2), not `MAX_ID` (ID 1). It oscillates, presumably due to arbitrary return order of promises, between two errors:
* `Error: Cannot return null for non-nullable field Thread.community.`
* `Error: Cannot return null for non-nullable field Thread.channel.`

The error is happening after the DB query (defined in `user.js`'s `getEverything`) returns successfully. Here's the JSON (from a debug session): [gist link](https://gist.github.com/tadasant/656a7602a151d7c73671ebba44f6fe02)

So it seems that it's failing to resolve one of those `channelId` and/or `communityId` references in the ensuing step. Could it be due to some missing pieces of mock data in `usersChannels` and/or `usersCommunities`, or one of the permissions booleans (e.g. `isOwner`) preventing GraphQL from resolving? If that seems plausible, can find some more time to fiddle with the data there to see if I can narrow it down.

Here's the full stack trace of the errors:

```api:utils:error-formatter ---GraphQL Error--- +7s
  api:utils:error-formatter Error: Cannot return null for non-nullable field Thread.community.
  api:utils:error-formatter     at completeValue (/Users/admin/WebstormProjects/spectrum/node_modules/graphql/execution/execute.js:596:13)
  api:utils:error-formatter     at /Users/admin/WebstormProjects/spectrum/node_modules/graphql/execution/execute.js:582:14
  api:utils:error-formatter     at <anonymous> +0ms
  api:utils:error-formatter query getEverythingThreads($after: String) +1ms
  api:utils:error-formatter variables {"after":null} +0ms
  api:utils:error-formatter path user.everything.edges[3].node.community +0ms
  api:utils:error-formatter -------------------
  api:utils:error-formatter  +0ms
Error: Cannot return null for non-nullable field Thread.community.
    at completeValue (/Users/admin/WebstormProjects/spectrum/node_modules/graphql/execution/execute.js:596:13)
    at /Users/admin/WebstormProjects/spectrum/node_modules/graphql/execution/execute.js:582:14
    at <anonymous>
```

```
api:utils:error-formatter ---GraphQL Error--- +2m
  api:utils:error-formatter Error: Cannot return null for non-nullable field Thread.channel.
  api:utils:error-formatter     at completeValue (/Users/admin/WebstormProjects/spectrum/node_modules/graphql/execution/execute.js:596:13)
  api:utils:error-formatter     at /Users/admin/WebstormProjects/spectrum/node_modules/graphql/execution/execute.js:582:14
  api:utils:error-formatter     at <anonymous> +0ms
  api:utils:error-formatter query getEverythingThreads($after: String) +0ms
  api:utils:error-formatter variables {"after":null} +0ms
  api:utils:error-formatter path user.everything.edges[3].node.channel +0ms
  api:utils:error-formatter -------------------
  api:utils:error-formatter  +1ms
Error: Cannot return null for non-nullable field Thread.channel.
    at completeValue (/Users/admin/WebstormProjects/spectrum/node_modules/graphql/execution/execute.js:596:13)
    at /Users/admin/WebstormProjects/spectrum/node_modules/graphql/execution/execute.js:582:14
    at <anonymous>
```

**Comment by mxstbr** [comment]
This was fixed and just needs a rebase, right?

**Comment by brianlovin** [comment]
@mxstbr I believe so!

**Comment by tadasant** [comment]
Right - but when I tried to do a quick one, it looked messy (I think some of the components under test had significant changes, which broke some of the `data-cy`'s I had added and there was no quick fix). I will finish it up hopefully later this week!

**Comment by tadasant** [comment]
@brianlovin @mxstbr this is ready now!

Differences between this and pre-rebase PR:
- Resolved rebase conflicts (reworked the `data-cy`'s)
- Took advantage of the #3499 fix to be able to [test non-owner vs. owner behavior](https://github.com/withspectrum/spectrum/pull/3229/commits/303f1b521d4799ff417055e3bc5d570b0d55a65c)

**Pull request closed without merging**
