### PR TITLE
Mobile polish day

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

Some cleanup work and upgraded deps to get ahead of the curve :)

### CODE REVIEW

**Review by mxstbr — DISMISSED** [review]
Raaad, will fix Peril and shipit!

**Review by mxstbr — APPROVED** [review]

**Comment by mxstbr** [comment]
Oh my god so green 😍 

screen shot 2018-05-26 at 10 48 54

**Comment by mxstbr** [comment]
Oh fuck, I know why e2e tests have started passing—only a single one runs:

screen shot 2018-05-26 at 10 49 34

/cc @ryota-murakami

**Comment by ryota-murakami** [comment]
hmm, so strange.

**Comment by ryota-murakami** [comment]
when i was fix Circle CI memory problem, all E2E tests were running.
https://circleci.com/gh/withspectrum/spectrum/6558?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

screen shot 2018-05-26 at 20 08 33

**Pull request merged**
