### PR TITLE
Update DM Thread last seen from mobile

### LINKED ISSUE #3364: [Mobile] Mark DM as read when viewing the DM thread view

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- mobile

**Related issues (delete if you don't know of any)**
Closes #3364

### CODE REVIEW

**Comment by brianlovin** [comment]
It's possible that this will result in a flicker of the unread state when the user navigates back to their DM list, right? Since it's executing on unmount.

Should we also call it once on mount so that the thread will get marked as read in the background while they are viewing it

**Comment by mxstbr** [comment]
> Should we also call it once on mount so that the thread will get marked as read in the background while they are viewing it

The issue is that that would hide the "New messages" indicator, right? That's why I put it into the `unmount` lifecycle, so it only updates once you navigate away—you're totally right about the flicker though, so maybe the solution is an optimistic client-side update so that it happens synchronously and you don't get that flicker but also see the "New messages" indicator?

**Comment by brianlovin** [comment]
> The issue is that that would hide the "New messages" indicator, right?

Ah. Maybe for DMs that's okay? I don't know...a DM seems very natural to just jump to the end of the conversation, but I understand why we built out the 'New messages' indicator...

**Comment by mxstbr** [comment]
I mean we have it, right? I don't mean to imply that this should change the scroll position or something, all I'm saying is it's nice to know where I last left the conversation. It's a nice UX thing.

**Comment by brianlovin** [comment]
Yeah, agreed. My request for changes then will be to make sure we can avoid the flicker of unread state when the user navigates back to the dm list :)

**Pull request closed without merging**
