### PR TITLE
Show team badge more quickly on optimistic message sending

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

### CODE REVIEW

**Comment by brianlovin** [comment]
@mxstbr have a demo of this working? Locally this seems to be rendering the team badge on new messages slower than on alpha

**Comment by mxstbr** [comment]
Wat? I swear it was faster for me locally, dammit. Apolloooooooo why u no worky workyyyyyyyy

**Comment by brianlovin** [comment]
Think this is a symptom of a bad data model? Bad gql schema? Or just a tough hack around the Apollo tooling?

**Comment by mxstbr** [comment]
Not necessarily, we just don't have the threadparticipant data in that mutation. We gotta get it from the component somehow...

**Comment by brianlovin** [comment]
@mxstbr want to double check me to see if it's actually faster for you? Otherwise let's close this and re-approach it differently down the road :)

**Pull request closed without merging**
