### PR TITLE
fixed mention regex to respect dots in usernames

### PR DESCRIPTION
**Pull request by dan-weaver**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- desktop

**Release notes for users (delete if codebase-only change)**
- Bug fix: mention regexp wasn't honoring `.` within usernames

**Related issues**
tangentially related to #3793 #2649 

before this fix:
screen shot 2018-08-18 at 7 59 40 pm

after this fix:
screen shot 2018-08-18 at 7 58 52 pm

### CODE REVIEW

**Review by mxstbr — CHANGES_REQUESTED** [review]
Does this tag `Hey @mxstbr.` as "mxstbr." being the mention? That's what I was trying to avoid with not tagging the dot.

**Comment by dan-weaver** [comment]
@mxstbr thanks for pointing that out. I think this fixes it, but I'm not super confident in my regexfoo.  This may also become irrelevant depending on some things in #3793 (assuming the mention plugin is used).

screen shot 2018-08-20 at 10 00 22 am

**Comment by mxstbr** [comment]
Can you try `Hey @dan.weaver... What's up?`? I think that'll still break... I'm going to look at that PR today!

**Comment by dan-weaver** [comment]
Looks like it still works.  I added a test case as well.  Didn't mean to open a can of works though! Trying to think of any other edge cases 🤔 .  Can revisit when and if that other PR is done maybe.
screen shot 2018-08-20 at 10 47 24 am

**Review by mxstbr — COMMENTED** [review]
Ohh, thank you for adding a test case :+1:

One last question: do we need the `\b`?

**Comment by dan-weaver** [comment]
No it looks like we do not need the `\b`! Removed

**Review by mxstbr — COMMENTED** [review]
Okay one last nitpick I swear: can we also add a test case for the original edge case (username with a dot in it) in combination with the trailing period one? :angel:

Thank you!!

**Comment by dan-weaver** [comment]
Not a nit pick at all.  This is embarrassing 😊.  I don't think I've had my recommended dose of coffee yet.  The changes to the regex I've introduced allow for other trailing punctuation.  I've updated it again to specify allowed characters instead of disallowed.  this of course means that `_ -` won't be allowed as trailing chars in a mention which I think is a good thing?  They were before though. Let me know if those should be allowed and I can add them.  Also updated the test case.


screen shot 2018-08-20 at 11 26 05 am

**Review by mxstbr — COMMENTED** [review]
> this of course means that _ - won't be allowed in the mention which I think is a good thing?

I think we want those? Usernames can include `-` or `_`!

**Comment by dan-weaver** [comment]
@mxstbr this latest changes still allows them it just doesn't allow them to be the **last** character of the username.  Which I think is normal for usernames, wasn't sure what your rules were though.
screen shot 2018-08-20 at 11 31 16 am

**Comment by brianlovin** [comment]
> it just doesn't allow them to be the last character of the username

I believe we allow those characters to be the last character of a username

**Review by mxstbr — APPROVED** [review]
This LGTM!!! 

Sorry for the slow reply @dan-weaver, thanks so much for the contribution :100:

**Pull request merged**
