### PR TITLE
Refactor and simplify thread feed cards

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

Trying to clean up the thread feed cards after today's hasty refactor. Here's my working figma file: https://www.figma.com/file/GCFyVa4Hm2Wosgrd5m0mo6zC/Untitled

Here's how I approached it:

Thread feed cards must succinctly represent all possible combinations of state/props/context/interaction. These are as follows:

**State:**
- new thread
- thread with new messages
- thread i've liked
- thread i've not liked

**Properties:**
- pinned
- locked
- watercooler

**Context:**
- inbox
- filtered community / community profile
- filtered channel / channel profile

**Interaction:**
- hovered
- active

The core underlying information that we would like to expose is:
- community (when relevant)
- channel (when relevant)
- last active
- author
- title
- number of likes
- number of messages

My figma file above captures the matrix of these requirements and this PR implements them. Open to feedback and ideas :)

### CODE REVIEW

**Comment by mxstbr** [comment]
Quick thoughts:

- Like this direction a lot a lot, thanks for formalizing this
- "New messages" is much higher signal than "New thread" (there's lots of new threads I don't care about, but if there's new messages in a conversation I've previously been in I care about that 95% of the time), so it should be more in your face
- I dearly miss the author avatar, it's a big part of recognizing "Oh a person I know posted this thread!" even while skimming
- This kinda ties into the previous point:the average number of communities a person is a member of is between two and three, so the community information isn't extremely valuable to most users. (it's more valuable to power users like you and me with 500 memberships) It seems to me like the author information is a lot more so, so maybe we just switch those around?
- We should show the like count next to the "New thread" indicator, it's kinda jarring to click on it and realize it already has 10 likes, just nobody has replied to it

**Comment by mxstbr** [comment]
Here's a Figma file with the community and person info switcharood: https://www.figma.com/file/SCmrgnjUy0utvchooIvTdE/Untitled-Copy?node-id=20%3A2 Screenshot:

inbox everything

This is imho much better, thoughts?

**Comment by brianlovin** [comment]
Can you pull that latest commit and see where I iterated towards this evening? Easy to revert back if needed. I'm exhausted and spent way too long on this :P

**Comment by brianlovin** [comment]
> "New messages" is much higher signal than "New thread" (there's lots of new threads I don't care about, but if there's new messages in a conversation I've previously been in I care about that 95% of the time), so it should be more in your face

See latest commit - I'm trying not to jam *too* much into the card; latest commit has a dot. Current problem is I remove that top row of the card if you're filtered down to a channel level, so if we keep down this path I'll fix that.

> I dearly miss the author avatar, it's a big part of recognizing "Oh a person I know posted this thread!" even while skimming

Agree, but I'm not really sure if it outranks the community context in the inbox view. Also will require a significantly forked component on the user profile view, but obv we can figure that out if we go this direction.

> We should show the like count next to the "New thread" indicator, it's kinda jarring to click on it and realize it already has 10 likes, just nobody has replied to it

See latest commit

**Comment by mxstbr** [comment]
More quick thoughts about latest changes:

- Really like the dot
- Really like the timestamp
- It feels weird to hide the timestamp for "New thread", since it can be up to 24h old. Maybe that should just be a green dot?

> I'm not really sure if it outranks the community context

Imo it does. Most users are a member of maybe three communities with potentially large overlap in membership, so it matters more who posted a thread than where it was posted. That becomes relevant once I think I'm interested and want to check it out/potentially reply, at which point I can take a closer look at the card and then at the thread view.

**Comment by mxstbr** [comment]
What about something like this?

screen shot 2018-06-28 at 08 51 42

In context:

screen shot 2018-06-28 at 08 51 02

A bit weird with an open thread and all those avatars maybe 🤔

**Pull request merged**
